USE Trump
GO

INSERT INTO Business VALUES ('100 Pierrepoint Street LLC')
INSERT INTO Business VALUES ('115 East 87, LLC (Contingent Right To Ownership Interest In Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('118-120 East Fourth Owner LLC')
INSERT INTO Business VALUES ('120 Macdougal Street Realty LLC')
INSERT INTO Business VALUES ('125 Algonquin Associates, LLC')
INSERT INTO Business VALUES ('128 Bauer Drive Associates, LLC')
INSERT INTO Business VALUES ('144 Willow Street LLC')
INSERT INTO Business VALUES ('145 Algonquin Associates, LLC')
INSERT INTO Business VALUES ('15-00 Pollitt Drive Associates, LLC')
INSERT INTO Business VALUES ('156 Algonquin Associates, LLC')
INSERT INTO Business VALUES ('156 Sullivan Street Realty LLC')
INSERT INTO Business VALUES ('17-01 Pollitt Drive Associates, LLC')
INSERT INTO Business VALUES ('175-225 Third Owner LLC')
INSERT INTO Business VALUES ('18 Sydney Place LLC')
INSERT INTO Business VALUES ('184 Kent Associates, LLC (Residential Real Estate In Brooklyn, NY)')
INSERT INTO Business VALUES ('19-00 Pollitt Drive Associates, LLC')
INSERT INTO Business VALUES ('19-05 Nevins Road Associates, LLC')
INSERT INTO Business VALUES ('195 East Fourth Owner LLC')
INSERT INTO Business VALUES ('199-203 East Fourth Owner LLC')
INSERT INTO Business VALUES ('2 Rector Kushner Member LLC (Commercial Real Estate In New York, NY)')
INSERT INTO Business VALUES ('2 Rector Kushner Member, LLC')
INSERT INTO Business VALUES ('20 De Bariloche Lp (Real Estate In Argentina)')
INSERT INTO Business VALUES ('200 East 62Nd 25A, LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('200 East 62Nd 25B, LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('200 East 62Nd 26D, LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('212 5Th 7C, LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('212 5Th 8C, LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('212 5Th 9C, LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('21St Century Fox')
INSERT INTO Business VALUES ('25-30 Columbia Heights (Brooklyn) Venture, LLC')
INSERT INTO Business VALUES ('267 East 10Th Street Realty LLC')
INSERT INTO Business VALUES ('27 Monroe Place LLC')
INSERT INTO Business VALUES ('29 Second Avenue Realty, LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('30 Florham Associates, LLC (Commercial Real Estate In Florham Park, NJ)')
INSERT INTO Business VALUES ('30 Journal Square Partners, LLC')
INSERT INTO Business VALUES ('30 Leslie Associates, LLC')
INSERT INTO Business VALUES ('315 East 10Th Street LLC')
INSERT INTO Business VALUES ('318 East 11Th Street Realty LLC')
INSERT INTO Business VALUES ('318 East 6Th Street Realty LLC')
INSERT INTO Business VALUES ('340 Flatbush Lender, LLC')
INSERT INTO Business VALUES ('38 Monroe Place LLC')
INSERT INTO Business VALUES ('40 Potash Road Associates, LLC')
INSERT INTO Business VALUES ('40 Wall Street Commercial LLC (Payroll Company)')
INSERT INTO Business VALUES ('401 Mezz Venture LLC (Residential &Amp; Commercial Real Estate In Chicago, Il)')
INSERT INTO Business VALUES ('401 North Wabash Venture LLC (Residential &Amp; Commercial Real Estate In Chicago, Il)')
INSERT INTO Business VALUES ('411 West Putnam Avenue (Commercial Real Estate In Greenwich, Ct)')
INSERT INTO Business VALUES ('42Floors (Real Estate Company)')
INSERT INTO Business VALUES ('435 East 9Th Street Realty LLC')
INSERT INTO Business VALUES ('44Th Street Realty Associates, LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('4T Holdings One LLC (Holding Company For Future Interests In Trump Hotel Manager Entities; New York, NY)')
INSERT INTO Business VALUES ('4T Holdings Two LLC (Holding Company For Future Interests In Scion And Szion Manager Entities; New York, NY)')
INSERT INTO Business VALUES ('5 Thornton Road Associates, LLC')
INSERT INTO Business VALUES ('502 6G LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('54 Barrow Street Associates LLC')
INSERT INTO Business VALUES ('55 Challenger Road Associates, LLC')
INSERT INTO Business VALUES ('55 Challenger Road Associates, LLC (Commercial Real Estate In Ridgefield Park, NJ)')
INSERT INTO Business VALUES ('55 Challenger, LLC')
INSERT INTO Business VALUES ('570 West Mount Pleasant Associates, LLC')
INSERT INTO Business VALUES ('570 West Mount Pleasant Realty Corp. (Residential Real Estate In Livingston, NJ)')
INSERT INTO Business VALUES ('570 West Mt. Pleasant Associates, LLC (Residential Real Estate In Livingston, NJ)')
INSERT INTO Business VALUES ('65 Bay, LLC (F/K/A Gaia Jc, LLC) (Residential Real Estate In Jersey City, NJ)')
INSERT INTO Business VALUES ('666 Kc Management, LLC (Management Company; New York, NY)')
INSERT INTO Business VALUES ('715 Park Avenue Associates, Lp (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('80 Maid LLC')
INSERT INTO Business VALUES ('80 Ml, LLC')
INSERT INTO Business VALUES ('80 Ml, LLC (Commercial Real Estate In New York, NY)')
INSERT INTO Business VALUES ('809 North Canon LLC (Residential Real Estate In Los Angeles, Ca)')
INSERT INTO Business VALUES ('809 North Canon Member Corporation (Pass-Thru Company For 809 North Canon LLC (Residential Real Estate In Los Angeles, Ca))')
INSERT INTO Business VALUES ('89 Hicks Street LLC')
INSERT INTO Business VALUES ('95 Bauer Drive Associates, LLC')
INSERT INTO Business VALUES ('99 East 7Th Street Realty LLC')
INSERT INTO Business VALUES ('A&Amp;Q Long/Short Strategies Fund LLC')
INSERT INTO Business VALUES ('A&Amp;Q Long/Short Strategies Fund LLC Promissory Note')
INSERT INTO Business VALUES ('Alabama St Public Sch &Amp; Clg Auth Cap Impt, Bonds')
INSERT INTO Business VALUES ('Apollo Global Management')
INSERT INTO Business VALUES ('Artwork')
INSERT INTO Business VALUES ('Astoria 21-80 38Th LLC (Residential Real Estate In Astoria, NY)')
INSERT INTO Business VALUES ('Astoria 21-81 38Th LLC (Residential Real Estate In Astoria, NY)')
INSERT INTO Business VALUES ('Astoria 23-05 30Th LLC (Residential Real Estate In Astoria, NY)')
INSERT INTO Business VALUES ('Astoria 23-15 30Th LLC (Residential Real Estate In Astoria, NY)')
INSERT INTO Business VALUES ('Astoria Portfolio Member LLC (Residential Real Estate In Astoria, NY)')
INSERT INTO Business VALUES ('B Monmouth Mall, LLC')
INSERT INTO Business VALUES ('B Monmouth Mall, LLC (Commercial Real Estate In Eatontown, NJ)')
INSERT INTO Business VALUES ('Bank Of America')
INSERT INTO Business VALUES ('Battery Park City NY Auth Senior Ser A, Bonds')
INSERT INTO Business VALUES ('Bavarian Woods Owner LLC')
INSERT INTO Business VALUES ('Bfps Ventures, LLC (Holding Company; New York, NY)')
INSERT INTO Business VALUES ('Blackstone Strategic Alliance Fund Ii Lp')
INSERT INTO Business VALUES ('Bls Associates LLC')
INSERT INTO Business VALUES ('Bls Investors LLC (Residential Real Estate In Brooklyn, NY')
INSERT INTO Business VALUES ('Bls Manager, LLC (Residential Real Estate In Brooklyn, NY)')
INSERT INTO Business VALUES ('Boeing Company')
INSERT INTO Business VALUES ('Boston Ma, Bonds')
INSERT INTO Business VALUES ('Broadband Proliferation Partners, LLC (Wiredscore; New York, NY)')
INSERT INTO Business VALUES ('Bruckner P Corp. (Commercial Real Estate In New York, NY)')
INSERT INTO Business VALUES ('Bruckner Plaza Center Corp.')
INSERT INTO Business VALUES ('Bruckner Plaza Center Corp. (Commercial Real Estate In New York, NY)')
INSERT INTO Business VALUES ('Bruckner Plaza Center, LLC (Commercial Real Estate In New York, NY)')
INSERT INTO Business VALUES ('Brynwood Gardens (Residential Real Estate In Old Bridge, NJ)')
INSERT INTO Business VALUES ('Busy Boys Investments LLC')
INSERT INTO Business VALUES ('C Development Ventures LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('C Development Ventures Member Corp (Pass-Thru Company For C Development Ventures LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('C-Iii Recovery Fund I Lp (Financial Investments; Irving, Tx)')
INSERT INTO Business VALUES ('Cadre (See Also Quadro Partners)')
INSERT INTO Business VALUES ('Cadre Astoria 21-80 38Th LLC (Residential Real Estate In Astoria, NY)')
INSERT INTO Business VALUES ('Cadre Astoria 21-81 38Th LLC (Residential Real Estate In Astoria, NY)')
INSERT INTO Business VALUES ('Cadre Astoria 23-05 30Th LLC (Residential Estate In Astoria, NY)')
INSERT INTO Business VALUES ('Cadre Astoria 23-15 30Th LLC (Residential Real Estate In Astoria, NY)')
INSERT INTO Business VALUES ('California St Dept Of Wtr Resources Pwr Sply Revenue Ser M, Bonds')
INSERT INTO Business VALUES ('California St, Bonds')
INSERT INTO Business VALUES ('Cambridge Who&#39;S Who')
INSERT INTO Business VALUES ('Cedarwood Riverbend Owner LLC')
INSERT INTO Business VALUES ('Cedarwood Village Apartments I &Amp; Ii Owner LLC')
INSERT INTO Business VALUES ('Cedarwood Village Apartments Iii Owner LLC')
INSERT INTO Business VALUES ('Charleston Naval Hospital')
INSERT INTO Business VALUES ('Charlotte Nc Rfdg, Bonds')
INSERT INTO Business VALUES ('Chatham Hill Associates, LLC')
INSERT INTO Business VALUES ('Chatham Hill Associates, LLC (Residential Real Estate In Chatham, NJ)')
INSERT INTO Business VALUES ('Chatham Hill Holdings, LLC')
INSERT INTO Business VALUES ('Cherry Pines Apartments (Residential Real Estate In Elizabeth, NJ)')
INSERT INTO Business VALUES ('Cisco Sys Inc Sr Nt, Bonds')
INSERT INTO Business VALUES ('Citi Group')
INSERT INTO Business VALUES ('Citigroup')
INSERT INTO Business VALUES ('Ck Bergen Associates, LLC (Industrial Real Estate In Fairlawn &Amp; Oakland, NJ)')
INSERT INTO Business VALUES ('Ck Livingston Esplanade, LLC (Westminster Hotel; Livingston, NJ)')
INSERT INTO Business VALUES ('Ck Realty Holdings, LLC (Commercial Real Estate In New York, NY And Wippany, NJ)')
INSERT INTO Business VALUES ('Claremount Iv Associates Lp (Financial Investments; New York, NY)')
INSERT INTO Business VALUES ('Cna Finl Corp, Bonds')
INSERT INTO Business VALUES ('Colonial Heights, LLC (Residential Real Estate In Parsippany, NJ)')
INSERT INTO Business VALUES ('Colts Neck Building Associates, LLC (Undeveloped Real Estate In Colts Neck, NJ)')
INSERT INTO Business VALUES ('Colts Neck Building Corp. (Undeveloped Real Estate In Colts Neck, NJ)')
INSERT INTO Business VALUES ('Columbia Corporate Center Building Corp. (Commercial Real Estate In Florham Park, NJ)')
INSERT INTO Business VALUES ('Columbia Corporate Center Development Associates, LLC')
INSERT INTO Business VALUES ('Columbia Corporate Center Development Associates, LLC (Commercial Real Estate In Florham Park, NJ)')
INSERT INTO Business VALUES ('Columbia Windows, LLC (Investment In Dhd Windows And Doors; New York, NY)')
INSERT INTO Business VALUES ('Columbus Park Property Owner LLC')
INSERT INTO Business VALUES ('Contingent Rights To Ownership Interests In Entities Holding Real Estate Directly Or Indirectly (Value Not Readily Ascertainable) (Entities Listed In Endnote)')
INSERT INTO Business VALUES ('Coppertree Properties Owner LLC')
INSERT INTO Business VALUES ('Cranbury Building Associates, LLC (Undeveloped Real Estate In Cranbury, NJ)')
INSERT INTO Business VALUES ('D B Pace Acquisition Member Corp (Land, Building And Ff&Amp;E)')
INSERT INTO Business VALUES ('Dartmouth Village, LLC (Residential Real Estate In Parsippany, NJ)')
INSERT INTO Business VALUES ('Deer Tree Building Associates, LLC (Undeveloped Real Estate In Hardyston Township, NJ)')
INSERT INTO Business VALUES ('Delaware Diversified Floating Rate Fund')
INSERT INTO Business VALUES ('Delaware Vip Reit Series')
INSERT INTO Business VALUES ('Deutsche Bank')
INSERT INTO Business VALUES ('Development Corporation For Israel/Israel Bonds')
INSERT INTO Business VALUES ('Dimensional International Core Equity Fund')
INSERT INTO Business VALUES ('Dimensional U.S. Core Equity 2 Fund')
INSERT INTO Business VALUES ('Djnj Frito, LLC')
INSERT INTO Business VALUES ('Djnj Frito, LLC (Insurance Brokerage License; Florham Park, NJ)')
INSERT INTO Business VALUES ('Djt Aerospace LLC (Aircraft)')
INSERT INTO Business VALUES ('Djt Holdings LLC (Holding Company)')
INSERT INTO Business VALUES ('Djt Holdings Managing Member LLC (Pass-Thru Company For Djt Holdings LLC (Holding Company))')
INSERT INTO Business VALUES ('Dominion Resources Inc VA')
INSERT INTO Business VALUES ('Donka Soho Member LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Dt App Warrant Holding LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Dt Bali Golf Manager LLC')
INSERT INTO Business VALUES ('Dt Bali Golf Manager Member Corp (Pass-Thru Company For Dt Bali Golf Manager LLC)')
INSERT INTO Business VALUES ('Dt Bali Hotel Manager LLC')
INSERT INTO Business VALUES ('Dt Bali Hotel Manager Member Corp (Pass-Thru Company For Dt Bali Hotel Manager LLC)')
INSERT INTO Business VALUES ('Dt Bali Technical Services Manager LLC')
INSERT INTO Business VALUES ('Dt Bali Technical Services Manager Member Corp (Pass-Thru Company For Dt Bali Technical Services Manager LLC)')
INSERT INTO Business VALUES ('Dt Dubai Golf Manager LLC (Management Company)')
INSERT INTO Business VALUES ('Dt Dubai Golf Manager Member Corp (Pass-Thru Company For Dt Dubai Golf Manager LLC (Management Company))')
INSERT INTO Business VALUES ('Dt Dubai Ii Golf Manager LLC')
INSERT INTO Business VALUES ('Dt Dubai Ii Golf Manager Member Corp (Pass-Thru Company For Dt Dubai Ii Golf Manager LLC)')
INSERT INTO Business VALUES ('Dt India Venture LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Dt Lido Golf Manager LLC')
INSERT INTO Business VALUES ('Dt Lido Golf Manager Member Corp (Pass-Thru Company For Dt Lido Golf Manager LLC)')
INSERT INTO Business VALUES ('Dt Lido Hotel Manager LLC')
INSERT INTO Business VALUES ('Dt Lido Hotel Manager Member Corp (Pass-Thru Company For Dt Lido Hotel Manager LLC (License Deal))')
INSERT INTO Business VALUES ('Dt Lido Technical Services Manager LLC')
INSERT INTO Business VALUES ('Dt Lido Technical Services Manager Member Corp (Pass-Thru Company For Dt Lido Technical Services Manager LLC)')
INSERT INTO Business VALUES ('Dt Marks Baku LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Dt Marks Baku Managing Member Corp (Pass-Thru Company For Dt Marks Baku LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('Dt Marks Bali LLC (License Deal)')
INSERT INTO Business VALUES ('Dt Marks Bali Member Corp (Pass-Thru Company For Dt Marks Bali LLC (License Deal))')
INSERT INTO Business VALUES ('Dt Marks Dubai LLC (License Deal)')
INSERT INTO Business VALUES ('Dt Marks Dubai Member Corp (Pass-Thru Company For Dt Marks Dubai LLC (License Deal))')
INSERT INTO Business VALUES ('Dt Marks Gurgaon LLC (License Deal)')
INSERT INTO Business VALUES ('Dt Marks Gurgaon Managing Member Corp (Pass-Thru Company For Dt Marks Gurgaon LLC (License Deal))')
INSERT INTO Business VALUES ('Dt Marks Jersey City LLC (License Deal)')
INSERT INTO Business VALUES ('Dt Marks Lido LLC (License Deal)')
INSERT INTO Business VALUES ('Dt Marks Lido Member Corp (Pass-Thru Company For Dt Marks Lido LLC (License Deal))')
INSERT INTO Business VALUES ('Dt Marks Pune Ii LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Dt Marks Pune Ii Managing Member Corp (Pass-Thru Company For Dt Marks Pune Ii LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('Dt Marks Pune LLC (License Deal)')
INSERT INTO Business VALUES ('Dt Marks Qatar LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Dt Marks Qatar Member Corp (Pass-Thru Company For Dt Marks Qatar LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('Dt Marks Rio LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Dt Marks Rio Member Corp (Pass-Thru Company For Dt Marks Rio LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('Dt Marks VAncouver Lp (License Holder)')
INSERT INTO Business VALUES ('Dt Marks VAncouver Member Corp (Pass-Thru Company For Dt Marks VAncouver Lp (License Holder))')
INSERT INTO Business VALUES ('Dt Marks Worli LLC (License Deal)')
INSERT INTO Business VALUES ('Dt Marks Worli Member Corp (Pass-Thru Company For Dt Marks Worli LLC (License Deal))')
INSERT INTO Business VALUES ('Dt Tower Gurgaon LLC')
INSERT INTO Business VALUES ('Dt Tower Gurgaon Managing Member Corp (License Holder)')
INSERT INTO Business VALUES ('Dt Tower Kolkata LLC (License Holder)')
INSERT INTO Business VALUES ('Dt Tower Kolkata Managing Member Corp (Pass-Thru Company For Dt Tower Kolkata LLC (License Holder))')
INSERT INTO Business VALUES ('Dttm Operations LLC (Pass-Thru Entity)')
INSERT INTO Business VALUES ('Dttm Operations Managing Member Corp (Pass-Thru Company For Dttm Operations LLC (Pass-Thru Entity))')
INSERT INTO Business VALUES ('Durham Cnty N C Rfdg, Bonds')
INSERT INTO Business VALUES ('Dutchess Cnty NY, Bonds')
INSERT INTO Business VALUES ('East 9Th Manager LLC')
INSERT INTO Business VALUES ('Easton North Associates, Lp (Residential Real Estate In Franklin Township, NJ)')
INSERT INTO Business VALUES ('Eaton VAnce Atlanta Cap Smid Cap Fund Class I (Eismx)')
INSERT INTO Business VALUES ('Eaton VAnce Global Macro Absolute Return Adv Fund (Egrix)')
INSERT INTO Business VALUES ('Eatontown Monmouth Mall (Junior Mezz) LLC')
INSERT INTO Business VALUES ('Eatontown Monmouth Mall (Senior Mezz) LLC')
INSERT INTO Business VALUES ('Eatontown Monmouth Mall Holdings LLC')
INSERT INTO Business VALUES ('Eatontown Monmouth Mall LLC')
INSERT INTO Business VALUES ('Ecolab Inc, Bonds')
INSERT INTO Business VALUES ('Elmwood Chicago Associates, LLC')
INSERT INTO Business VALUES ('Elmwood Chicago Holding, LLC')
INSERT INTO Business VALUES ('Elmwood Chicago Member, LLC')
INSERT INTO Business VALUES ('Elmwood NYt Holdings, LLC')
INSERT INTO Business VALUES ('Elmwood NYt Mezz, LLC')
INSERT INTO Business VALUES ('Elmwood NYt Owner, LLC')
INSERT INTO Business VALUES ('Elmwood NYt Principal, LLC')
INSERT INTO Business VALUES ('Elmwood V. Associates, Lp (Commercial Real Estate In Chicago, Il)')
INSERT INTO Business VALUES ('Erie Cnty NY Fiscal Stability Auth Sales Tax &Amp; St Aid Secd A, Bonds')
INSERT INTO Business VALUES ('Europacific Growth Fund - 529-A (1016) (Ceuax)')
INSERT INTO Business VALUES ('Ev 1St Avenue Property Owner, L.P.')
INSERT INTO Business VALUES ('Ev Avenue A Property Owner, L.P.')
INSERT INTO Business VALUES ('Ev Jv Gp LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('Ev Jv Partnership, L.P.')
INSERT INTO Business VALUES ('Exxon Mobil Corporation, Bonds')
INSERT INTO Business VALUES ('Fabfitfun (Beauty And Wellness Subscription Service)')
INSERT INTO Business VALUES ('Felmore Associates (Residential Real Estate In South River, NJ)')
INSERT INTO Business VALUES ('Fidelity Dividend Growth Fund (Fdgfx)')
INSERT INTO Business VALUES ('Fidelity Freedom 2040 Fund (Ffffx)')
INSERT INTO Business VALUES ('Fidelity Growth Company (Fdgrx)')
INSERT INTO Business VALUES ('Fidelity Overseas Fund (Fosfx)')
INSERT INTO Business VALUES ('Fidelity VAlue Fund (Fdvlx)')
INSERT INTO Business VALUES ('Fifth Associates, LLC (Commercial Real Estate In New York, NY)')
INSERT INTO Business VALUES ('Fifth K Two LLC')
INSERT INTO Business VALUES ('First Eagle Global Funds Class I (Sgiix)')
INSERT INTO Business VALUES ('Five Acre Jv (Industrial Real Estate In Union, NJ)')
INSERT INTO Business VALUES ('Flatbush 340 Lender LLC (Loan Receivable From 9 Dekalb Owner LLC; Brooklyn, NY)')
INSERT INTO Business VALUES ('Flatbush 340 Lender, LLC (Loan Receivable From 9 Dekalb Owner LLC; Brooklyn, NY)')
INSERT INTO Business VALUES ('Florham Park Developers Corp. (Commercial Real Estate In Florham Park, NJ)')
INSERT INTO Business VALUES ('Florham Park Realty Associates, LLC (Commercial Real Estate In Florham Park, NJ)')
INSERT INTO Business VALUES ('Ford Mtr Cr Co Nt, Bonds')
INSERT INTO Business VALUES ('Friends Of Idf (Non-Profit)')
INSERT INTO Business VALUES ('Gallant Funding, Lp (Lending To Real Estate Developers For Real Estate Projects In New York And New Jersey)')
INSERT INTO Business VALUES ('Gcm Trust')
INSERT INTO Business VALUES ('Gellert 80 West End, LLC')
INSERT INTO Business VALUES ('Gellert 80 West End, LLC (Residential And Commercial Real Estate In Long Branch, NJ And Astoria, NY)')
INSERT INTO Business VALUES ('Georgetown Village I Owner LLC')
INSERT INTO Business VALUES ('Georgetown Village Ii Owner LLC')
INSERT INTO Business VALUES ('Georgetown Village Iii Owner LLC')
INSERT INTO Business VALUES ('Georgetown Village Iv Owner LLC')
INSERT INTO Business VALUES ('Georgia St, Bonds')
INSERT INTO Business VALUES ('Global Gateway Alliance (Advocacy Organization)')
INSERT INTO Business VALUES ('Goldman Sachs Group Inc Sr Global Nt, Bonds')
INSERT INTO Business VALUES ('Golf Productions LLC (Golf Video Production Company)')
INSERT INTO Business VALUES ('Golf Productions Member Corp (Pass- Thru Company For Golf Productions LLC (Golf Video Production Company))')
INSERT INTO Business VALUES ('Gowan Associates, LLC')
INSERT INTO Business VALUES ('Gowan Associates, LLC (Undeveloped Real Estate In Brooklyn, NY)')
INSERT INTO Business VALUES ('Greenburgh NY, Bonds')
INSERT INTO Business VALUES ('Hartford World Bond Fund I (Hwdix)')
INSERT INTO Business VALUES ('Hennessy Gas Utility Index Fund Investor Class Shares (Gasfx)')
INSERT INTO Business VALUES ('Home Depot Inc')
INSERT INTO Business VALUES ('Honest Buildings (Real Estate Software Company)')
INSERT INTO Business VALUES ('Hot Potato')
INSERT INTO Business VALUES ('Hunters Ridge Property Owner LLC')
INSERT INTO Business VALUES ('Idb Bank')
INSERT INTO Business VALUES ('Iholdings Corp (Dormant/Inactive)')
INSERT INTO Business VALUES ('Iholdings Madison LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Internet Week New York')
INSERT INTO Business VALUES ('Investors Savings Bank')
INSERT INTO Business VALUES ('Iroqouis Properties, Lp (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('Iroquois Properties Realty Corp. (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('Ishares 20+ Year Treas Bond Etf (Tlt)')
INSERT INTO Business VALUES ('Ishares Msci Eafe Etf')
INSERT INTO Business VALUES ('Ishares Msci Eafe Etf (Efa)')
INSERT INTO Business VALUES ('Ishares Russell 1000 Etf (Iwb)')
INSERT INTO Business VALUES ('It Apparel Ii LLC')
INSERT INTO Business VALUES ('It Apparel Ii Managing Member Corp')
INSERT INTO Business VALUES ('It Apparel LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('It Apparel Member Corp (Pass-Thru Company For It Apparel LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('It Baby Home LLC')
INSERT INTO Business VALUES ('It Baby Home Member Corp')
INSERT INTO Business VALUES ('It Collection LLC')
INSERT INTO Business VALUES ('It Eyewear LLC')
INSERT INTO Business VALUES ('It Eyewear Manager Corp')
INSERT INTO Business VALUES ('It Fashion Jewelry LLC')
INSERT INTO Business VALUES ('It Fashion Jewelry Member Corp')
INSERT INTO Business VALUES ('It Fragrance LLC')
INSERT INTO Business VALUES ('It Fragrance Manager Corp')
INSERT INTO Business VALUES ('It Handbags LLC (Licensing Contracts For Handbags; New York, NY)')
INSERT INTO Business VALUES ('It Handbags Member Corp')
INSERT INTO Business VALUES ('It Home Marks LLC')
INSERT INTO Business VALUES ('It Home Marks Managing Member Corp')
INSERT INTO Business VALUES ('It International I LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('It International I Member Corp (Pass- Thru Company For It International LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('It Investors I LLC (Held Investments)')
INSERT INTO Business VALUES ('It Operations LLC (All Assets Reflected In The Ivanka M. Trump Business Trust) (Income For Period January 1, 2016 - March 8, 2017)')
INSERT INTO Business VALUES ('It Operations LLC (F/K/A It Swimwear LLC)')
INSERT INTO Business VALUES ('It Operations LLC (Management Company In New York, NY)')
INSERT INTO Business VALUES ('It Operations Managing Member Corp (F/K/A It Swimwear Managing Member Corp)')
INSERT INTO Business VALUES ('It Outerwear LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('It Outwear Member Corp (Pass-Thru Company For It Outerwear LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('It Promotions LLC')
INSERT INTO Business VALUES ('It Properties Holding Company LLC (Held Investments)')
INSERT INTO Business VALUES ('It Www Pub LLC')
INSERT INTO Business VALUES ('It Www Wri LLC (Received Writer Fee For Women Who Work)')
INSERT INTO Business VALUES ('Itjk Investors LLC (Held Investments)')
INSERT INTO Business VALUES ('Ivanka M. Trump Business Trust (It Collection LLC, Holding Company In New York NY)) (Income For Period March 9, 2017 - May 31, 2017)')
INSERT INTO Business VALUES ('Ivanka Marks Holding Corp')
INSERT INTO Business VALUES ('Ivanka Opo Hotel Manager LLC (Management Of Dc Hotel)')
INSERT INTO Business VALUES ('Ivanka Opo LLC')
INSERT INTO Business VALUES ('Ivanka Trump Marks Ii LLC')
INSERT INTO Business VALUES ('Ivanka Trump Marks Ii Member Corp')
INSERT INTO Business VALUES ('Ivanka Trump Marks Jewelry LLC')
INSERT INTO Business VALUES ('Ivanka Trump Marks Jewelry Member Corp')
INSERT INTO Business VALUES ('Ivanka Trump Marks LLC')
INSERT INTO Business VALUES ('Janus Enterprise Fund Class 1 (Jmgrx)')
INSERT INTO Business VALUES ('Jck Cadre LLC (Prior Holding Company For Quadro Partners; New York, NY)')
INSERT INTO Business VALUES ('Jibe (F/K/A Localbacon)')
INSERT INTO Business VALUES ('Jk Thrive Iv LLC (Interest In Venture Capital Fund; New York, NY)')
INSERT INTO Business VALUES ('Jk Thrive V LLC (Interest In Venture Capital Fund; New York, NY)')
INSERT INTO Business VALUES ('Jk Thrive V, LLC (Interest In Venture Capital Fund; New York, NY)')
INSERT INTO Business VALUES ('Jk2 Westminster, LLC (Management Company, New York, NY)')
INSERT INTO Business VALUES ('Jkm Capital, LLC (Interest In Venture Capital Fund; New York, NY)')
INSERT INTO Business VALUES ('Jp Morgan Chase &Amp; Co, Bonds')
INSERT INTO Business VALUES ('Jp Morgan Chase Bank, Bonds')
INSERT INTO Business VALUES ('Jp Morgan Core Bond Fund Select (Wobdx)')
INSERT INTO Business VALUES ('Jp Morgan High Yield Fund')
INSERT INTO Business VALUES ('Jpmorgan High Yield Fund')
INSERT INTO Business VALUES ('Jupiter Golf Club LLC (Golf Club)')
INSERT INTO Business VALUES ('Jupiter Golf Club Managing Member Corp (Pass-Thru Company For Jupiter Golf Club LLC (Golf Club))')
INSERT INTO Business VALUES ('K 26 Journal Square, LLC')
INSERT INTO Business VALUES ('K 26 Journal Square, LLC (Commercial Real Estate In Jersey City, NJ)')
INSERT INTO Business VALUES ('K 30 Journal Manager Corp. (Commercial Real Estate In Jersey City, NJ)')
INSERT INTO Business VALUES ('K 30 Journal Manager Corp. (Undeveloped Real Estate In Jersey City, NJ)')
INSERT INTO Business VALUES ('K 30 Journal Square Manager Corp. (Commercial Real Estate In Jersey City, NJ)')
INSERT INTO Business VALUES ('K 30 Journal Square, LLC')
INSERT INTO Business VALUES ('K 30 Journal Square, LLC (Undeveloped Real Estate In Jersey City, NJ)')
INSERT INTO Business VALUES ('K Astoria I LLC (Residential Real Estate In Astoria, NY)')
INSERT INTO Business VALUES ('K Astoria, LLC')
INSERT INTO Business VALUES ('K Astoria, LLC (Residential Real Estate In Astoria, NY)')
INSERT INTO Business VALUES ('K Gaia Village 1 Associates, LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('K Gaia Village 2 Associates, LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('K Maryland Associates, LLC (Residential Real Estate In Baltimore &Amp; Prince George’S County, Md)')
INSERT INTO Business VALUES ('K Maryland Associates, LLC (Residential Real Estate In Baltimore, Garrett &Amp; Prince George, Md)')
INSERT INTO Business VALUES ('K Morgan Street Construction Manager Corp. (Residential Real Estate In Jersey City, NJ)')
INSERT INTO Business VALUES ('K Morgan Street Manager Corp (Residential Real Estate In Jersey City, NJ)')
INSERT INTO Business VALUES ('K Morgan Street Property Manager Corp. (Residential Real Estate In Jersey City, NJ)')
INSERT INTO Business VALUES ('K One Journal Square LLC')
INSERT INTO Business VALUES ('K One Journal Square Manager Corp. (Residential Real Estate In Jersey City, NJ)')
INSERT INTO Business VALUES ('K One Journal Square, LLC (Undeveloped Real Estate In Jersey City, NJ)')
INSERT INTO Business VALUES ('K Stonehage Village 1 Associates, LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('K-Bls Portfolio LLC')
INSERT INTO Business VALUES ('K/S Westwood Gp, LLC (Residential Real Estate In Westwood And River VAle, NJ)')
INSERT INTO Business VALUES ('K2 26Js Member LLC')
INSERT INTO Business VALUES ('K2 One Journal Square Member LLC')
INSERT INTO Business VALUES ('K2w2 26Js Holdings LLC')
INSERT INTO Business VALUES ('Kaszek Ventures Ii (Venture Capital Fund)')
INSERT INTO Business VALUES ('Kay &Amp; Arr Realty Associates (Residential Real Estate In Elizabeth, NJ)')
INSERT INTO Business VALUES ('Kc Dumbo Hotel, LLC (Option To Purchase Commercial Real Estate In Brooklyn, NY)')
INSERT INTO Business VALUES ('Kc Dumbo Office, LLC (Commercial Real Estate In Brooklyn, NY)')
INSERT INTO Business VALUES ('Kc Profit Participation, LLC (Holding Company For Entities Holding Contingent Rights To Ownership Interests In Real Estate)')
INSERT INTO Business VALUES ('Kc3 - 101 Macdougal Street, LLC')
INSERT INTO Business VALUES ('Kc3 - 104 East 7Th Street, LLC')
INSERT INTO Business VALUES ('Kc3 - 233 East 82Nd Street, LLC')
INSERT INTO Business VALUES ('Kc3 - 234-238 East 33Rd Street, LLC')
INSERT INTO Business VALUES ('Kc3 - 310 East 83Rd Street, LLC')
INSERT INTO Business VALUES ('Kc3 - 319-321 East 78Th Street, LLC')
INSERT INTO Business VALUES ('Kc3 - 325 East 83Rd Street, LLC')
INSERT INTO Business VALUES ('Kc3 - 354-356 State Street, LLC')
INSERT INTO Business VALUES ('Kc3 - 410 East 64Th Street, LLC')
INSERT INTO Business VALUES ('Kc3 - 438-440 East 13Th Street, LLC')
INSERT INTO Business VALUES ('Kc3 - 504 East 88Th Street, LLC')
INSERT INTO Business VALUES ('Kclw 3Rd Street LLC')
INSERT INTO Business VALUES ('Kclw Acquisition Manager LLC')
INSERT INTO Business VALUES ('Kcof-215 Moore, LLC (Loan Receivable From Heritage Equities; Brooklyn, NY)')
INSERT INTO Business VALUES ('Kf Middle River, LLC (Residential Real Estate In Middle River &Amp; Essex, Md)')
INSERT INTO Business VALUES ('Kf Westwood Partner, LLC (Residential Real Estate In Westwood &Amp; River VAle, NJ)')
INSERT INTO Business VALUES ('Kf- C-Iii Recovery Fund Ii, LLC (Financial Investments In C-Iii Recovery Fund Ii, Lp; Irving, Tx)')
INSERT INTO Business VALUES ('Kf- Faire Fund Ii, LLC (Financial Investments In The Faire Fund Ii, Lp; Israel)')
INSERT INTO Business VALUES ('Kf- Park Street Capital Pe Fund Ix, LLC (Financial Investments In Park Street Capital Private Equity Fund; Boston, Ma)')
INSERT INTO Business VALUES ('Kf- Rcg Longview Debt Fund Iv, LLC (Financial Investments In Rcg Longview Debt Fund Iv Lp; New York, NY)')
INSERT INTO Business VALUES ('Kf-Bls Member, LLC (Residential Real Estate In Brooklyn, NY)')
INSERT INTO Business VALUES ('Kf-Centerview, LLC (Financial Investments In Centerview Capital, Lp; New York, NY)')
INSERT INTO Business VALUES ('Kf-Wip Co. Investors I, LLC (Industrial Real Estate In Middletown, Pa)')
INSERT INTO Business VALUES ('Kff 29 Second Avenue LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('Kff 29 Second Avenue, LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('Kickstarter')
INSERT INTO Business VALUES ('Kkc Associates LLC (Residential Real Estate In Kansas City, Mo)')
INSERT INTO Business VALUES ('Kkc Associates, LLC (Residential Real Estate In Kansas City, Mo)')
INSERT INTO Business VALUES ('Kkc Managing Member LLC (Residential Real Estate In Kansas City, Mo)')
INSERT INTO Business VALUES ('Kushner Companies')
INSERT INTO Business VALUES ('Kushner Companies LLC (Real Estate Company In New York, NY)')
INSERT INTO Business VALUES ('Kushner Credit Opportunity Fund, LLC (Management Company; New York, NY)')
INSERT INTO Business VALUES ('Kushner Family Foundation (Charitable Foundation)')
INSERT INTO Business VALUES ('Kushner Media Ventures, LLC (Financial Investments In Thrive Capital Partners, LLC; New York, NY)')
INSERT INTO Business VALUES ('Kushner Midwest Partner 1, LLC')
INSERT INTO Business VALUES ('Kushner Midwest Partners 1 LLC (Residential Real Estate In Toledo, Middletown, Akron &Amp; Bedford Heights, Oh, Pittsburgh, Pa &Amp; Speedway, In)')
INSERT INTO Business VALUES ('Kushner Philadelphia Member, LLC (Residential Real Estate In Philadelphia, Pa)')
INSERT INTO Business VALUES ('Kushner Skyline Promote, LLC (Contingent Right To Ownership Interest In Skyline Kushner LLC)')
INSERT INTO Business VALUES ('Kushner Village 2 Member LLC (Rental Apartments In New York, NY)')
INSERT INTO Business VALUES ('Kushner Village 3 Spe LLC')
INSERT INTO Business VALUES ('Kushner Village 325 East 10Th LLC')
INSERT INTO Business VALUES ('Kushner Village 329 East 9Th LLC')
INSERT INTO Business VALUES ('Kushner Village 4 Spe LLC')
INSERT INTO Business VALUES ('Lacey Township Building Corp. (Real Estate In Lacey, NJ)')
INSERT INTO Business VALUES ('Landings Apartments, LLC (Commercial Real Estate In Chicago, Il)')
INSERT INTO Business VALUES ('Landings At Caspian Pointe, LLC (Undeveloped Real Estate In Atlantic City, NJ)')
INSERT INTO Business VALUES ('Landings Chicago Associates, LLC')
INSERT INTO Business VALUES ('Landings Chicago Holding, LLC')
INSERT INTO Business VALUES ('Landings Chicago Member, LLC')
INSERT INTO Business VALUES ('Landings NYt Holdings, LLC')
INSERT INTO Business VALUES ('Landings NYt Mezz, LLC')
INSERT INTO Business VALUES ('Landings NYt Owner, LLC')
INSERT INTO Business VALUES ('Landings NYt Principal, LLC')
INSERT INTO Business VALUES ('Leland Point Gp LLC')
INSERT INTO Business VALUES ('Leland Point Partners Gp LLC')
INSERT INTO Business VALUES ('Leland Point Partners Lp LLC')
INSERT INTO Business VALUES ('Lfb Acquisition Member Corp (Pass-Thru Company)')
INSERT INTO Business VALUES ('Lincoln National Life Insurance Company, VAriable Life')
INSERT INTO Business VALUES ('Lincoln National Life Insurance Company, VAriable Life: Ssga Bond Index Fund; Jpmorgan High Yield Fund; Delaware Diversified Floating Rate Fund; Delaware Vip Reit Series; Dimensional International Core Equity Fund; Dimensional U.S. Core Equity 2 Fund')
INSERT INTO Business VALUES ('Lindenlawn Apartment Associates, LLC (Residential Real Estate In Englewood, NJ)')
INSERT INTO Business VALUES ('Livingston Hills Building Associates, LLC (Real Estate Under Construction In Livingston, NJ)')
INSERT INTO Business VALUES ('Livingston Hills Building Corp. (Real Estate Under Construction In Livingston, NJ)')
INSERT INTO Business VALUES ('Lmp Jv (Industrial Real Estate In Edison, NJ)')
INSERT INTO Business VALUES ('Lodi Phillipsburg Apartment Associates (Residential Real Estate In Lodi, NJ)')
INSERT INTO Business VALUES ('Lord Abbett High Yield Fund Class F (Lhyfx)')
INSERT INTO Business VALUES ('Lord Abbett Intermediate Tax Free Fund Class F (Lisfx)')
INSERT INTO Business VALUES ('Lw Investors, LLC (Financial Investments In Leeds Equity Partners Iv, Lp; New York, NY)')
INSERT INTO Business VALUES ('Macrosolve')
INSERT INTO Business VALUES ('Magnolia Building Associates, LLC (Undeveloped Assets In Pemberton, NJ)')
INSERT INTO Business VALUES ('Mar-A-Lago Club, L.L.C. (A/K/A The Mar-A- Lago Club L.C.) (Resort)')
INSERT INTO Business VALUES ('Martha Bell Associates, LLC (Residential Real Estate In Elizabeth, NJ)')
INSERT INTO Business VALUES ('Maryland Apartment Holdings 10-Pack Jv, LLC')
INSERT INTO Business VALUES ('Maryland St Dept Transn, Bonds')
INSERT INTO Business VALUES ('Massachusetts St Wtr Pollutn, Bonds')
INSERT INTO Business VALUES ('Mecklenberg Cnty Nc, Bonds')
INSERT INTO Business VALUES ('Megalith Capital Management (Real Estate Company)')
INSERT INTO Business VALUES ('Merritt Associates, LLC (Residential Real Estate In Dumont, NJ)')
INSERT INTO Business VALUES ('Met Transprtn Auth NY Revenue Rfdg Transprtn Ser C, Bonds')
INSERT INTO Business VALUES ('Met Transprtn Auth NY Revenue Transn Ser A, Bonds')
INSERT INTO Business VALUES ('Metlife')
INSERT INTO Business VALUES ('Mgm/Mark Burnett Productions (Residuals From The Apprentice) (Value Not Readily Ascertainable)')
INSERT INTO Business VALUES ('Microsoft Corp')
INSERT INTO Business VALUES ('Middle River Jv LLC')
INSERT INTO Business VALUES ('Midwest Partners 1 LLC')
INSERT INTO Business VALUES ('Milford Building Corp. (Real Estate In Milford, Pa)')
INSERT INTO Business VALUES ('Millington Bank')
INSERT INTO Business VALUES ('Miracle Manor Property Owner LLC')
INSERT INTO Business VALUES ('Mmll LLC (Liquor License For Restaurant At Monmouth Mall, Eatontown, NJ)')
INSERT INTO Business VALUES ('Monmouth Mall 2, LLC (Commercial Real Estate In Eatontown, NJ)')
INSERT INTO Business VALUES ('Monmouth Mall, LLC (Commercial Real Estate In Eatontown, NJ)')
INSERT INTO Business VALUES ('Morgan Stanley, Bonds')
INSERT INTO Business VALUES ('Morgan Street Developers Joint Venture, LLC')
INSERT INTO Business VALUES ('Mt. Pleasant Jv (Commercial Real Estate In West Orange, NJ)')
INSERT INTO Business VALUES ('Nassau Cnty NY Interim Fin Auth Rfdg Sales Tax Secured Ser A, Bonds')
INSERT INTO Business VALUES ('Netcong Heights Associates, LLC (Residential Real Estate In Netcong, NJ)')
INSERT INTO Business VALUES ('New Jersey Renewable Power Corp.')
INSERT INTO Business VALUES ('New Jersey Renewable Power, LLC (Operation Of Solar Panels; Florham Park, NJ)')
INSERT INTO Business VALUES ('New Puck Corp.')
INSERT INTO Business VALUES ('New Puck Corp. (Commercial Real Estate In New York, NY)')
INSERT INTO Business VALUES ('New Puck Investors, LLC')
INSERT INTO Business VALUES ('New Puck Residential Corp. (Commercial Real Estate In New York, NY)')
INSERT INTO Business VALUES ('New Puck, LLC')
INSERT INTO Business VALUES ('New York City NY Muni Wtr Fin Auth Wtr &Amp; Swr Sys Reven Ser Aa, Bonds')
INSERT INTO Business VALUES ('New York Community Bank')
INSERT INTO Business VALUES ('New York Luxury Publishing')
INSERT INTO Business VALUES ('New York NY Ser B, Bonds')
INSERT INTO Business VALUES ('New York NY Ser E, Bonds')
INSERT INTO Business VALUES ('New York NY VAr Subser L 4, Bonds')
INSERT INTO Business VALUES ('New York Observer')
INSERT INTO Business VALUES ('New York St Dorm Auth Revenues St Supported Debt Third Gen Resolution St Univ Edl Facs Ser A, Bonds')
INSERT INTO Business VALUES ('New York St Dorm Auth Revs Nonst Supported Debt Cornell Univ B, Bonds')
INSERT INTO Business VALUES ('New York St Dorm Auth Sales Tax Revenue Rfdg Ser A, Bonds')
INSERT INTO Business VALUES ('New York St Dorm Auth St Personal Income Tax Revenue Rfdg Ser E, Bonds')
INSERT INTO Business VALUES ('New York St Dorm Auth St Personal Income Tax Revenue Unrefunded Ser A, Bonds')
INSERT INTO Business VALUES ('New York St Environ Facs Corp St Clean Wtr &Amp; Drinking Revolving Fds- NYc Mun Wtr A, Bonds')
INSERT INTO Business VALUES ('New York St Environ Facs Corp St Clean Wtr &Amp; Drinking Revolving Fdsnyc Mun Wtr A, Bonds')
INSERT INTO Business VALUES ('New York St Local Govt Assistance Corp Rfdg Sub Lien Ser A, Bonds')
INSERT INTO Business VALUES ('New York St Ser A, Bonds')
INSERT INTO Business VALUES ('New York St Ser E, Bonds')
INSERT INTO Business VALUES ('New York St Thruway Auth 2Nd Gen Highway &Amp; Bridge Trust Fund Ser A, Bonds')
INSERT INTO Business VALUES ('New York St Urban Dev Corp Rev St Pers Income Tax Ser A1, Bonds')
INSERT INTO Business VALUES ('New York St, Bonds')
INSERT INTO Business VALUES ('New York State Urban Dev Corp Rev Rfdg Svc Contract Ser B, Bonds')
INSERT INTO Business VALUES ('News Corporation')
INSERT INTO Business VALUES ('Nextera Energy Inc')
INSERT INTO Business VALUES ('Nitto World Co., Limited (Dormant/Inactive)')
INSERT INTO Business VALUES ('Nk 80 Maiden Holdings LLC')
INSERT INTO Business VALUES ('Nuveen Enhanced Amt-Free Municipal Credit Opportunities Fund (Nvg)')
INSERT INTO Business VALUES ('O Townhomes Kff, Lp (Loan Originating Entity, New York, NY)')
INSERT INTO Business VALUES ('Oakwood Chicago Associates, LLC')
INSERT INTO Business VALUES ('Oakwood Chicago Holding, LLC')
INSERT INTO Business VALUES ('Oakwood Chicago Member, LLC')
INSERT INTO Business VALUES ('Oakwood Garden Associates, LLC (Commercial Real Estate In Chicago, Il)')
INSERT INTO Business VALUES ('Oakwood NYt Holdings, LLC')
INSERT INTO Business VALUES ('Oakwood NYt Mezz, LLC')
INSERT INTO Business VALUES ('Oakwood NYt Owner, LLC')
INSERT INTO Business VALUES ('Oakwood NYt Principal, LLC')
INSERT INTO Business VALUES ('Observer Capital Sm Spv, LLC (Shares Of Corp. Stock In Source Media Holdings Inc.; New York, NY)')
INSERT INTO Business VALUES ('Observer Capital Sm Spv, LLC (Shares Of Corporate Stock In Source Media Holdings Inc.; New York, NY)')
INSERT INTO Business VALUES ('Observer Media, LLC (New York Observer &Amp; Commercial Observer)')
INSERT INTO Business VALUES ('Oc Partners, LLC (Cash; New York, NY)')
INSERT INTO Business VALUES ('One Journal Square Partners Holdings LLC')
INSERT INTO Business VALUES ('One Journal Square Tower North Holdings LLC')
INSERT INTO Business VALUES ('One Journal Square Tower South Holdings LLC')
INSERT INTO Business VALUES ('Onondaga Cnty NY, Bonds')
INSERT INTO Business VALUES ('Opo Hotel Manager LLC (Management Of Dc Hotel)')
INSERT INTO Business VALUES ('Opo Hotel Manager Member Corp (Pass-Thru Company For Opo Hotel Manager LLC)')
INSERT INTO Business VALUES ('Oppenheimer Developing Markets (Odvyx)')
INSERT INTO Business VALUES ('Oppenheimer Developing Markets Class Y (Odvyx)')
INSERT INTO Business VALUES ('Oregon St Dept Of Transprtn Highway User Tax Revenue Ser A, Bonds')
INSERT INTO Business VALUES ('Oscar Health')
INSERT INTO Business VALUES ('Owo Developer LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Oxford Arms Associates Limited Partnership (Residential Real Estate In Edison, NJ)')
INSERT INTO Business VALUES ('P.V. Development, LLC (Undeveloped Real Estate In Long Branch, NJ)')
INSERT INTO Business VALUES ('Panama Ocean Club Management LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Panama Ocean Club Management Member Corp (Pass-Thru Company For Panama Ocean Club Management LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('Park Lake Village (Residential Real Estate In Parsippany, NJ)')
INSERT INTO Business VALUES ('Park Lane Mobile Home Park (Residential Real Estate In Union, NJ)')
INSERT INTO Business VALUES ('Partnership For New York City (Advocacy And Economic Development Organization)')
INSERT INTO Business VALUES ('Penguin Random House LLC')
INSERT INTO Business VALUES ('Pepsico, Inc. (28 Shares)')
INSERT INTO Business VALUES ('Pier Village Ii Urban Renewal Company LLC')
INSERT INTO Business VALUES ('Pier Village Iii Jv LLC')
INSERT INTO Business VALUES ('Pimco Enhanced Short Mat Active Etf (Mint)')
INSERT INTO Business VALUES ('Pimco Rae Fundamental Advantage Plus Fund Class P (Pfatx)')
INSERT INTO Business VALUES ('Pimco Total Return Fund Class P (Pttpx)')
INSERT INTO Business VALUES ('Pine Hill Development LLC (Golf Club)')
INSERT INTO Business VALUES ('Pine Hill Development Managing Member Corp (Pass-Thru Company For Pine Hill Development LLC (Golf Club))')
INSERT INTO Business VALUES ('Pinecrest Building Corp. (Undeveloped Real Estate In Tobyhanna Township, Pa)')
INSERT INTO Business VALUES ('Pinecrest Lake Building Associates, Lp (Undeveloped Real Estate In Tobyhanna Township, Pa)')
INSERT INTO Business VALUES ('Pinefield Manor, LLC (Residential Real Estate In Denville, NJ)')
INSERT INTO Business VALUES ('Poker Venture LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Poker Venture Managing Member Corp (Pass-Thru Company For Poker Venture LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('Port Auth Of New York &Amp; New Jersey NY Ser 179, Bonds')
INSERT INTO Business VALUES ('Powerhouse Associates, LLC (Potential Future Real Estate Development)')
INSERT INTO Business VALUES ('Powershares Nasdaq 100 Etf (Qqq)')
INSERT INTO Business VALUES ('Powershares S&Amp;P 500 Downside Hedged Portfolio Etf (Phdg)')
INSERT INTO Business VALUES ('Powershares S&Amp;P 500 Low Volatility Portfolio Etf (Splv)')
INSERT INTO Business VALUES ('President-Elect&#39;S Transition Team')
INSERT INTO Business VALUES ('Princeton Horizon Apartments (Residential Real Estate In South Brunswick, NJ)')
INSERT INTO Business VALUES ('Principal Sm-Md Cp Div P (Pmdpx)')
INSERT INTO Business VALUES ('Principal Sm-Mid Cp Div P (Pmdpx)')
INSERT INTO Business VALUES ('Puck Building, Lp (Commercial Real Estate In New York, NY)')
INSERT INTO Business VALUES ('Puck Residential Associates, LLC (Residential Real Estate In New York, NY And Leonia, NJ)')
INSERT INTO Business VALUES ('Quadro Partners (D/B/A Cadre) (Real Estate Investment Platform In New York, NY)')
INSERT INTO Business VALUES ('Quadro Partners, Inc. (D/B/A Cadre) (Real Estate Investment Platform In New York, NY')
INSERT INTO Business VALUES ('Real Estate Board Of New York (Rebny) (Real Estate Organization)')
INSERT INTO Business VALUES ('Realcadre LLC')
INSERT INTO Business VALUES ('Regal Bank (Shares Of Corp. Stock; Livingston, NJ)')
INSERT INTO Business VALUES ('River Edge Apartments (Residential Real Estate In Ewing, NJ)')
INSERT INTO Business VALUES ('Riverhead Reeves Building Corp. (Residential Real Estate In Riverhead, NY)')
INSERT INTO Business VALUES ('Riverhead Sound Associates LLC (Residential Real Estate In Riverhead, NY)')
INSERT INTO Business VALUES ('Riverhead Sound Building Corp. (Residential Real Estate In Riverhead, NY)')
INSERT INTO Business VALUES ('Rivernorth/Doubleline Strategic Income Fund I (Rnsix)')
INSERT INTO Business VALUES ('Rob Speyer')
INSERT INTO Business VALUES ('Rockwell Automation Inc')
INSERT INTO Business VALUES ('Route 10 Associates, LLC (Industrial Real Estate In Whippany, NJ)')
INSERT INTO Business VALUES ('Rp/K Kent Avenue, LLC')
INSERT INTO Business VALUES ('Rues Lane Building Corp. (Real Estate In East Brunswick, NJ)')
INSERT INTO Business VALUES ('Sales Tax Asset Receivable Corp NY Rfdg Fiscal 2015 Ser A, Bonds')
INSERT INTO Business VALUES ('Sanei International')
INSERT INTO Business VALUES ('Schlumberger Ltd Netherlands Antilles')
INSERT INTO Business VALUES ('Schoolhouse Jv (Commercial Real Estate In Milburn, NJ)')
INSERT INTO Business VALUES ('Screen Actors Guild')
INSERT INTO Business VALUES ('Seryl Charles Kushner Family Foundation Inc.')
INSERT INTO Business VALUES ('Seven Springs LLC (Real Estate In Mt. Kisco, NY)')
INSERT INTO Business VALUES ('Sg Blocks Inc.')
INSERT INTO Business VALUES ('Signature Bank')
INSERT INTO Business VALUES ('Signature Bank New York NY')
INSERT INTO Business VALUES ('Sixty Capital Fund (Hedge Fund)')
INSERT INTO Business VALUES ('Sixty One Associates, LLC (Commercial Real Estate In New York, NY)')
INSERT INTO Business VALUES ('Sixty-Six West Associates, LLC (Commercial Real Estate In Livingston, NJ)')
INSERT INTO Business VALUES ('Skyline Jv Gp, LLC (Residential Real Estate In Hasbrouck Heights, NJ)')
INSERT INTO Business VALUES ('Skyline Kushner, LLC (Residential Real Estate In Hasbrouck Heights &Amp; Lodi, NJ)')
INSERT INTO Business VALUES ('Skytop Gardens (Residential Real Estate In Sayreville, NJ)')
INSERT INTO Business VALUES ('Slc Turnberry Limited (Golf Courses &Amp; Resort)')
INSERT INTO Business VALUES ('Sq Associates, LLC (Financial Investments In Square Mile Partners, Lp; New York, NY)')
INSERT INTO Business VALUES ('Sqk Associates, LLC (Financial Investments In Square Mile Partners, Lp; New York, NY)')
INSERT INTO Business VALUES ('Ssga Bond Index Fund')
INSERT INTO Business VALUES ('St Leonia, LLC')
INSERT INTO Business VALUES ('State Tower Of Syracuse Associates, LLC (Residential Real Estate In Leonia, NJ)')
INSERT INTO Business VALUES ('Stb Building Corp. (Residential Real Estate In Leonia, NJ)')
INSERT INTO Business VALUES ('Stone 16 Associates, LLC')
INSERT INTO Business VALUES ('Stone 16 Associates, LLC (Residential Real Estate In New York, NY)')
INSERT INTO Business VALUES ('Stone Portfolio LLC')
INSERT INTO Business VALUES ('Sunnydale Estates Property Owner LLC')
INSERT INTO Business VALUES ('T International Realty LLC')
INSERT INTO Business VALUES ('Taylor Edison Jv (Industrial Real Estate In Edison, NJ)')
INSERT INTO Business VALUES ('Tc Marks Buenos Aires LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Templeton Global Bond Adv (Tgbax)')
INSERT INTO Business VALUES ('Templeton Global Income Fund (Gim)')
INSERT INTO Business VALUES ('Thc Baku Hotel Manager Services LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Thc Baku Hotel Manager Services Member Corp (Pass-Thru Company For Thc Baku Hotel Manager Services LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('Thc Baku Services LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Thc Baku Services Member Corp (Pass- Thru Company For Thc Baku Services LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('Thc Central Reservations LLC (Hotel Company)')
INSERT INTO Business VALUES ('Thc Central Reservations Member Corp (Pass-Thru Company For Thc Central Reservations LLC (Hotel Company))')
INSERT INTO Business VALUES ('Thc China Development LLC (Developer)')
INSERT INTO Business VALUES ('Thc China Technical Services LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Thc China Technical Services Manager Corp (Pass-Thru Company For Thc China Technical Services LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('Thc Dc Restaurant Hospitality LLC')
INSERT INTO Business VALUES ('Thc Development Brazil LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Thc Development Brazil Managing Member Corp (Pass-Thru Company For Thc Development Brazil LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('Thc Hotel Development LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Thc Miami Restaurant Hospitality LLC (Restaurant Operations)')
INSERT INTO Business VALUES ('Thc Miami Restaurant Hospitality Member Corp (Pass-Thru Company For Thc Miami Restaurant Hospitality LLC (Restaurant Operations))')
INSERT INTO Business VALUES ('Thc Qatar Hotel Manager LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Thc Qatar Hotel Manager Member Corp (Pass-Thru Company For Thc Qatar Hotel Manager LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('Thc Rio Manager LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Thc Rio Managing Member Corp (Pass- Thru Company For Thc Rio Manager LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('Thc Sales &Amp; Marketing LLC (Management Company)')
INSERT INTO Business VALUES ('Thc Sales &Amp; Marketing Member Corp (Pass-Thru Company For Thc Sales &Amp; Marketing LLC (Management Company))')
INSERT INTO Business VALUES ('Thc Services Shenzhen LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Thc Services Shenzhen Member Corp (Pass-Thru Company For Thc Services Shenzen LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('Thc Shenzhen Hotel Manager LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Thc Shenzhen Hotel Manager Member Corp (Pass-Thru Company For Thc Hotel Manager LLC (Dormant/Inactive))')
INSERT INTO Business VALUES ('Thc VAncouver Management Corp (Management Company)')
INSERT INTO Business VALUES ('Thc VAncouver Payroll Ulc (Payroll Company)')
INSERT INTO Business VALUES ('Thc Venture Ii LLC (Dormant/Inactive)')
INSERT INTO Business VALUES ('Thc Venture Ii Managing Member Corp. (Pass-Thru Company For Thc Venture Ii LLC (Dormant/Inactive))')
