USE Trump
GO
UPDATE Conflict SET Slug = '1290-avenue-of-the-americas-a-tenancy-in-common' WHERE ID = 577
UPDATE Conflict SET Slug = 'erie-county-ny' WHERE ID = 805
UPDATE Conflict SET Slug = 'starrett-city-associates-lp' WHERE ID = 1188
UPDATE Conflict SET Slug = 'village-kf-4-9-10-associates-llc' WHERE ID = 537
UPDATE Conflict SET Slug = 'village-kf-4-9-10-associates-lp' WHERE ID = 1563
UPDATE Conflict SET Slug = 'wake-county-nc' WHERE ID = 1574
UPDATE Conflict SET Slug = 'westchester-county-ny' WHERE ID = 1592
UPDATE Conflict SET Slug = '' WHERE ID = 3298
UPDATE Conflict SET Slug = '1-journal-square-partners' WHERE ID = 3364
UPDATE Conflict SET Slug = '115-east-87' WHERE ID = 535
UPDATE Conflict SET Slug = '1290-avenue-of-the-americas-a-tenancy-in-common' WHERE ID = 2
UPDATE Conflict SET Slug = '175-pearl-street' WHERE ID = 462
UPDATE Conflict SET Slug = '184-kent-associates' WHERE ID = 548
UPDATE Conflict SET Slug = '2-rector-kushner' WHERE ID = 485
UPDATE Conflict SET Slug = '20-de-bariloche' WHERE ID = 498
UPDATE Conflict SET Slug = '200-east-62nd' WHERE ID = 3366
UPDATE Conflict SET Slug = '212-5th' WHERE ID = 3367
UPDATE Conflict SET Slug = '21st-century-fox' WHERE ID = 499
UPDATE Conflict SET Slug = '26-journal-square' WHERE ID = 3295
UPDATE Conflict SET Slug = '29-second-avenue-realty' WHERE ID = 506
UPDATE Conflict SET Slug = '30-florham-associates' WHERE ID = 507
UPDATE Conflict SET Slug = '3126-corporation' WHERE ID = 3
UPDATE Conflict SET Slug = '4-shadow-tree-lane' WHERE ID = 4
UPDATE Conflict SET Slug = '40-wall-street' WHERE ID = 5
UPDATE Conflict SET Slug = '401-mezz-venture' WHERE ID = 3368
UPDATE Conflict SET Slug = '411-west-putnam-avenue' WHERE ID = 3301
UPDATE Conflict SET Slug = '42floors' WHERE ID = 3300
UPDATE Conflict SET Slug = '44th-street-realty' WHERE ID = 3303
UPDATE Conflict SET Slug = '4t-holdings-one' WHERE ID = 6
UPDATE Conflict SET Slug = '4t-holdings-two' WHERE ID = 7
UPDATE Conflict SET Slug = '502-6g' WHERE ID = 3369
UPDATE Conflict SET Slug = '55-challenger-road-associates' WHERE ID = 518
UPDATE Conflict SET Slug = '55-wall-development' WHERE ID = 3365
UPDATE Conflict SET Slug = '570-west-mt-pleasant' WHERE ID = 3370
UPDATE Conflict SET Slug = '65-bay' WHERE ID = 522
UPDATE Conflict SET Slug = '666-fifth-ave' WHERE ID = 443
UPDATE Conflict SET Slug = '666-kc-management' WHERE ID = 564
UPDATE Conflict SET Slug = '715-park-avenue-associates' WHERE ID = 567
UPDATE Conflict SET Slug = '721-33h' WHERE ID = 3371
UPDATE Conflict SET Slug = '767-manager-llc' WHERE ID = 8
UPDATE Conflict SET Slug = '80-ml' WHERE ID = 525
UPDATE Conflict SET Slug = '809-north-canon' WHERE ID = 9
UPDATE Conflict SET Slug = '81-pine-note-holder' WHERE ID = 10
UPDATE Conflict SET Slug = '845-un' WHERE ID = 11
UPDATE Conflict SET Slug = 'aq' WHERE ID = 579
UPDATE Conflict SET Slug = 'aq-longshort-strategies-fund' WHERE ID = 3302
UPDATE Conflict SET Slug = 'ace-entertainment-formerly-trump-casinos-or-trump-taj-mahal' WHERE ID = 12
UPDATE Conflict SET Slug = 'alabama-public-schools' WHERE ID = 582
UPDATE Conflict SET Slug = 'alabama-st-public-sch-clg-auth-cap-impt' WHERE ID = 3186
UPDATE Conflict SET Slug = 'algonquin-associates' WHERE ID = 3177
UPDATE Conflict SET Slug = 'all-county-building-supply-maintenance' WHERE ID = 13
UPDATE Conflict SET Slug = 'all-county-building-supply-amp-maintenance' WHERE ID = 382
UPDATE Conflict SET Slug = 'allen-weisselberg' WHERE ID = 9695
UPDATE Conflict SET Slug = 'amboy-bank' WHERE ID = 9617
UPDATE Conflict SET Slug = 'american-federation-of-television-and-radio-artists' WHERE ID = 9635
UPDATE Conflict SET Slug = 'american-idea' WHERE ID = 482
UPDATE Conflict SET Slug = 'annie-veltri' WHERE ID = 14
UPDATE Conflict SET Slug = 'any-relation-to-kf-bls-member-llc' WHERE ID = 3239
UPDATE Conflict SET Slug = 'apollo-management' WHERE ID = 450
UPDATE Conflict SET Slug = 'apple' WHERE ID = 407
UPDATE Conflict SET Slug = 'approved' WHERE ID = 3238
UPDATE Conflict SET Slug = 'artwork' WHERE ID = 3161
UPDATE Conflict SET Slug = 'att' WHERE ID = 454
UPDATE Conflict SET Slug = 'aviation-payroll-company' WHERE ID = 15
UPDATE Conflict SET Slug = 'b-monmouth-mall' WHERE ID = 586
UPDATE Conflict SET Slug = 'b-plaza-realty' WHERE ID = 16
UPDATE Conflict SET Slug = 'bahrain' WHERE ID = 426
UPDATE Conflict SET Slug = 'bank-of-america' WHERE ID = 589
UPDATE Conflict SET Slug = 'bank-of-china' WHERE ID = 425
UPDATE Conflict SET Slug = 'bank-of-new-york-mellon-trust-company' WHERE ID = 9631
UPDATE Conflict SET Slug = 'bank-of-nova-scotia' WHERE ID = 421
UPDATE Conflict SET Slug = 'bank-united' WHERE ID = 9611
UPDATE Conflict SET Slug = 'battery-park-city' WHERE ID = 590
UPDATE Conflict SET Slug = 'battery-park-city-ny-auth-senior-ser-a' WHERE ID = 3190
UPDATE Conflict SET Slug = 'bedford-hills' WHERE ID = 17
UPDATE Conflict SET Slug = 'berkshire-hathaway' WHERE ID = 406
UPDATE Conflict SET Slug = 'bfps-ventures' WHERE ID = 593
UPDATE Conflict SET Slug = 'blackrock-financial-management' WHERE ID = 3287
UPDATE Conflict SET Slug = 'blackstone-group' WHERE ID = 3305
UPDATE Conflict SET Slug = 'blackstone-strategic-alliance-fund-ii' WHERE ID = 594
UPDATE Conflict SET Slug = 'bls-investors' WHERE ID = 3372
UPDATE Conflict SET Slug = 'bls-manager' WHERE ID = 3373
UPDATE Conflict SET Slug = 'boeing' WHERE ID = 600
UPDATE Conflict SET Slug = 'boston-ma-bonds' WHERE ID = 601
UPDATE Conflict SET Slug = 'boston-ma' WHERE ID = 3304
UPDATE Conflict SET Slug = 'briar-hall-operations' WHERE ID = 18
UPDATE Conflict SET Slug = 'broadband-proliferation-partners' WHERE ID = 607
UPDATE Conflict SET Slug = 'brookfield-asset-management' WHERE ID = 448
UPDATE Conflict SET Slug = 'bruckner-p-corp' WHERE ID = 3265
UPDATE Conflict SET Slug = 'bruckner-plaza-center' WHERE ID = 560
UPDATE Conflict SET Slug = 'brynwood-gardens' WHERE ID = 3245
UPDATE Conflict SET Slug = 'buffalo-bills' WHERE ID = 9691
UPDATE Conflict SET Slug = 'bungalow-hotel' WHERE ID = 9655
UPDATE Conflict SET Slug = 'c-development-ventures' WHERE ID = 19
UPDATE Conflict SET Slug = 'c-iii-capital-partners' WHERE ID = 3229
UPDATE Conflict SET Slug = 'c-iii-recovery-fund-i' WHERE ID = 616
UPDATE Conflict SET Slug = 'cadre' WHERE ID = 445
UPDATE Conflict SET Slug = 'cadre-astoria' WHERE ID = 3206
UPDATE Conflict SET Slug = 'calamos-wealth-management' WHERE ID = 3363
UPDATE Conflict SET Slug = 'california-st-bonds' WHERE ID = 623
UPDATE Conflict SET Slug = 'california-st-dept-of-wtr' WHERE ID = 622
UPDATE Conflict SET Slug = 'california-st-dept-of-wtr-resources-pwr-sply-revenue-ser-m' WHERE ID = 3234
UPDATE Conflict SET Slug = 'cambridge-whos-who' WHERE ID = 9643
UPDATE Conflict SET Slug = 'cap-cana' WHERE ID = 467
UPDATE Conflict SET Slug = 'capital-group' WHERE ID = 3280
UPDATE Conflict SET Slug = 'capital-one' WHERE ID = 9609
UPDATE Conflict SET Slug = 'caribusiness' WHERE ID = 3353
UPDATE Conflict SET Slug = 'caribusiness-mre' WHERE ID = 20
UPDATE Conflict SET Slug = 'caribusiness-re' WHERE ID = 21
UPDATE Conflict SET Slug = 'carl-c-icahn' WHERE ID = 428
UPDATE Conflict SET Slug = 'celgene' WHERE ID = 410
UPDATE Conflict SET Slug = 'centerview-capital' WHERE ID = 951
UPDATE Conflict SET Slug = 'charleston-naval-hospital' WHERE ID = 3329
UPDATE Conflict SET Slug = 'charlotte-nc' WHERE ID = 630
UPDATE Conflict SET Slug = 'charlotte-nc' WHERE ID = 3258
UPDATE Conflict SET Slug = 'chatham-hill-associates' WHERE ID = 631
UPDATE Conflict SET Slug = 'chelsea-hall' WHERE ID = 22
UPDATE Conflict SET Slug = 'cherry-pines-apartments' WHERE ID = 3230
UPDATE Conflict SET Slug = 'chevron' WHERE ID = 416
UPDATE Conflict SET Slug = 'chevy-chase-trust' WHERE ID = 9618
UPDATE Conflict SET Slug = 'chicago-unit-acquisition' WHERE ID = 23
UPDATE Conflict SET Slug = 'chicago-unit-acquisition-llc' WHERE ID = 9619
UPDATE Conflict SET Slug = 'china-state-construction-engineering-corp' WHERE ID = 477
UPDATE Conflict SET Slug = 'china-trademark' WHERE ID = 24
UPDATE Conflict SET Slug = 'cindy-yang' WHERE ID = 9688
UPDATE Conflict SET Slug = 'cisco-sys' WHERE ID = 638
UPDATE Conflict SET Slug = 'cisco-systems' WHERE ID = 3290
UPDATE Conflict SET Slug = 'citi-group' WHERE ID = 3247
UPDATE Conflict SET Slug = 'citibank' WHERE ID = 451
UPDATE Conflict SET Slug = 'ck-bergen-associates' WHERE ID = 492
UPDATE Conflict SET Slug = 'ck-livingston-esplanade' WHERE ID = 641
UPDATE Conflict SET Slug = 'ck-realty-holdings' WHERE ID = 3261
UPDATE Conflict SET Slug = 'claremount-iv-associates' WHERE ID = 644
UPDATE Conflict SET Slug = 'clyde-hall' WHERE ID = 25
UPDATE Conflict SET Slug = 'cna-financial-corporation' WHERE ID = 3267
UPDATE Conflict SET Slug = 'cna-finl' WHERE ID = 647
UPDATE Conflict SET Slug = 'cnn' WHERE ID = 9698
UPDATE Conflict SET Slug = 'colonial-heights-llc' WHERE ID = 3212
UPDATE Conflict SET Slug = 'columbia-windows' WHERE ID = 648
UPDATE Conflict SET Slug = 'commerce-department' WHERE ID = 440
UPDATE Conflict SET Slug = 'coronet-hall' WHERE ID = 26
UPDATE Conflict SET Slug = 'country-apartments' WHERE ID = 27
UPDATE Conflict SET Slug = 'country-investors' WHERE ID = 28
UPDATE Conflict SET Slug = 'country-of-vietnam' WHERE ID = 458
UPDATE Conflict SET Slug = 'country-properties' WHERE ID = 29
UPDATE Conflict SET Slug = 'cpw-pt-partners' WHERE ID = 30
UPDATE Conflict SET Slug = 'cranbury-building-associates' WHERE ID = 662
UPDATE Conflict SET Slug = 'crippled-america' WHERE ID = 31
UPDATE Conflict SET Slug = 'd-aerospace' WHERE ID = 9658
UPDATE Conflict SET Slug = 'd-b-pace-acquisition' WHERE ID = 32
UPDATE Conflict SET Slug = 'daewoo-america' WHERE ID = 33
UPDATE Conflict SET Slug = 'damac-properties' WHERE ID = 476
UPDATE Conflict SET Slug = 'dana-farber-cancer-institute' WHERE ID = 430
UPDATE Conflict SET Slug = 'dartmouth-village' WHERE ID = 3202
UPDATE Conflict SET Slug = 'david-pecker' WHERE ID = 9696
UPDATE Conflict SET Slug = 'deer-tree-building-associates' WHERE ID = 668
UPDATE Conflict SET Slug = 'delaware-funds' WHERE ID = 3226
UPDATE Conflict SET Slug = 'department-of-defense' WHERE ID = 483
UPDATE Conflict SET Slug = 'department-of-energy' WHERE ID = 9700
UPDATE Conflict SET Slug = 'department-of-homeland-security' WHERE ID = 484
UPDATE Conflict SET Slug = 'deutsche-asset-wealth-management' WHERE ID = 9524
UPDATE Conflict SET Slug = 'deutsche-bank' WHERE ID = 424
UPDATE Conflict SET Slug = 'development-corporation-for-israel' WHERE ID = 669
UPDATE Conflict SET Slug = 'dimensional-fund-advisors' WHERE ID = 3203
UPDATE Conflict SET Slug = 'dj-aerospace-bermuda' WHERE ID = 34
UPDATE Conflict SET Slug = 'djnj-frito' WHERE ID = 673
UPDATE Conflict SET Slug = 'djt-aerospace' WHERE ID = 35
UPDATE Conflict SET Slug = 'djt-holdings' WHERE ID = 36
UPDATE Conflict SET Slug = 'djt-land-holdings' WHERE ID = 37
UPDATE Conflict SET Slug = 'djt-operations-cx' WHERE ID = 38
UPDATE Conflict SET Slug = 'djt-operations-i' WHERE ID = 39
UPDATE Conflict SET Slug = 'djt-operations-ii' WHERE ID = 40
UPDATE Conflict SET Slug = 'dogan-holding' WHERE ID = 398
UPDATE Conflict SET Slug = 'dominion-resources' WHERE ID = 682
UPDATE Conflict SET Slug = 'donald-j-trump-enterprises' WHERE ID = 41
UPDATE Conflict SET Slug = 'donald-j-trump-enterprises-ii' WHERE ID = 42
UPDATE Conflict SET Slug = 'donald-j-trump-enterprises-iii' WHERE ID = 43
UPDATE Conflict SET Slug = 'donald-j-trump-company' WHERE ID = 44
UPDATE Conflict SET Slug = 'donald-j-trump-foundation' WHERE ID = 45
UPDATE Conflict SET Slug = 'donald-j-trump-grantor-trust' WHERE ID = 46
UPDATE Conflict SET Slug = 'donald-j-trump-revocable-trust' WHERE ID = 47
UPDATE Conflict SET Slug = 'dsn-licensing-formerly-trump-marks-network' WHERE ID = 48
UPDATE Conflict SET Slug = 'dt-app-warrant-holding' WHERE ID = 49
UPDATE Conflict SET Slug = 'dt-bali-golf-manager' WHERE ID = 50
UPDATE Conflict SET Slug = 'dt-bali-hotel-manager' WHERE ID = 51
UPDATE Conflict SET Slug = 'dt-bali-technical-services-manager' WHERE ID = 52
UPDATE Conflict SET Slug = 'dt-connect' WHERE ID = 53
UPDATE Conflict SET Slug = 'dt-connect-europe' WHERE ID = 54
UPDATE Conflict SET Slug = 'dt-connect-ii' WHERE ID = 55
UPDATE Conflict SET Slug = 'dt-dubai-golf-manager' WHERE ID = 56
UPDATE Conflict SET Slug = 'dt-dubai-ii-golf-manager' WHERE ID = 57
UPDATE Conflict SET Slug = 'dt-endeavor' WHERE ID = 3376
UPDATE Conflict SET Slug = 'dt-home-marks-international' WHERE ID = 58
UPDATE Conflict SET Slug = 'dt-india-venture' WHERE ID = 59
UPDATE Conflict SET Slug = 'dt-jeddah-technical-services-advisor' WHERE ID = 60
UPDATE Conflict SET Slug = 'dt-jeddah-technical-services-manager' WHERE ID = 61
UPDATE Conflict SET Slug = 'dt-lido-golf-manager' WHERE ID = 62
UPDATE Conflict SET Slug = 'dt-lido-hotel-manager' WHERE ID = 63
UPDATE Conflict SET Slug = 'dt-lido-technical-services-manager' WHERE ID = 64
UPDATE Conflict SET Slug = 'dt-marks-baku' WHERE ID = 65
UPDATE Conflict SET Slug = 'dt-marks-bali' WHERE ID = 66
UPDATE Conflict SET Slug = 'dt-marks-dubai' WHERE ID = 67
UPDATE Conflict SET Slug = 'dt-marks-dubai-ii' WHERE ID = 68
UPDATE Conflict SET Slug = 'dt-marks-gurgaon' WHERE ID = 69
UPDATE Conflict SET Slug = 'dt-marks-jersey-city' WHERE ID = 70
UPDATE Conflict SET Slug = 'dt-marks-jupiter' WHERE ID = 71
UPDATE Conflict SET Slug = 'dt-marks-lido' WHERE ID = 72
UPDATE Conflict SET Slug = 'dt-marks-products-international' WHERE ID = 73
UPDATE Conflict SET Slug = 'dt-marks-pune' WHERE ID = 74
UPDATE Conflict SET Slug = 'dt-marks-pune-ii' WHERE ID = 75
UPDATE Conflict SET Slug = 'dt-marks-qatar' WHERE ID = 76
UPDATE Conflict SET Slug = 'dt-marks-rio' WHERE ID = 77
UPDATE Conflict SET Slug = 'dt-marks-vancouver' WHERE ID = 78
UPDATE Conflict SET Slug = 'dt-marks-worli' WHERE ID = 79
UPDATE Conflict SET Slug = 'dt-tower-gurgaon' WHERE ID = 80
UPDATE Conflict SET Slug = 'dt-tower-i' WHERE ID = 81
UPDATE Conflict SET Slug = 'dt-tower-ii' WHERE ID = 82
UPDATE Conflict SET Slug = 'dt-tower-kolkata' WHERE ID = 83
UPDATE Conflict SET Slug = 'dt-venture' WHERE ID = 3377
UPDATE Conflict SET Slug = 'dttm-operations' WHERE ID = 84
UPDATE Conflict SET Slug = 'dtw-venture' WHERE ID = 85
UPDATE Conflict SET Slug = 'durham-cnty' WHERE ID = 776
UPDATE Conflict SET Slug = 'durham-cnty-n-c-rfdg' WHERE ID = 3215
UPDATE Conflict SET Slug = 'durham-county-nc' WHERE ID = 3240
UPDATE Conflict SET Slug = 'dutchess-cnty-ny' WHERE ID = 779
UPDATE Conflict SET Slug = 'dutchess-county-ny' WHERE ID = 3259
UPDATE Conflict SET Slug = 'east-61-st-company' WHERE ID = 86
UPDATE Conflict SET Slug = 'easton-north-associates' WHERE ID = 3223
UPDATE Conflict SET Slug = 'eaton-vance' WHERE ID = 3175
UPDATE Conflict SET Slug = 'eaton-vance-global' WHERE ID = 781
UPDATE Conflict SET Slug = 'ecolab' WHERE ID = 786
UPDATE Conflict SET Slug = 'ecolab-inc' WHERE ID = 3201
UPDATE Conflict SET Slug = 'eid-venture-i' WHERE ID = 87
UPDATE Conflict SET Slug = 'eid-venture-ii' WHERE ID = 88
UPDATE Conflict SET Slug = 'elmwood-chicago' WHERE ID = 3272
UPDATE Conflict SET Slug = 'elmwood-v-associates' WHERE ID = 791
UPDATE Conflict SET Slug = 'energy-fuels' WHERE ID = 9702
UPDATE Conflict SET Slug = 'energy-transfer-partners' WHERE ID = 393
UPDATE Conflict SET Slug = 'entertainment-partners' WHERE ID = 9522
UPDATE Conflict SET Slug = 'environmental-protection-agency-epa' WHERE ID = 9701
UPDATE Conflict SET Slug = 'erie-county-ny' WHERE ID = 2141
UPDATE Conflict SET Slug = 'essential-consultants' WHERE ID = 452
UPDATE Conflict SET Slug = 'ev-jv-partnership' WHERE ID = 3200
UPDATE Conflict SET Slug = 'excel-venture-i' WHERE ID = 89
UPDATE Conflict SET Slug = 'exxon-mobil' WHERE ID = 417
UPDATE Conflict SET Slug = 'fabfitfun' WHERE ID = 813
UPDATE Conflict SET Slug = 'faire-fund' WHERE ID = 943
UPDATE Conflict SET Slug = 'fbi' WHERE ID = 3219
UPDATE Conflict SET Slug = 'federal-election-commission' WHERE ID = 465
UPDATE Conflict SET Slug = 'felmore-associates' WHERE ID = 3220
UPDATE Conflict SET Slug = 'fidelity-investments' WHERE ID = 3378
UPDATE Conflict SET Slug = 'fifth-associates' WHERE ID = 3214
UPDATE Conflict SET Slug = 'fifty-seven-management' WHERE ID = 90
UPDATE Conflict SET Slug = 'fifty-seventh-street-associates' WHERE ID = 91
UPDATE Conflict SET Slug = 'first-eagle-investment-management' WHERE ID = 3246
UPDATE Conflict SET Slug = 'first-member' WHERE ID = 92
UPDATE Conflict SET Slug = 'first-republic-bank' WHERE ID = 9613
UPDATE Conflict SET Slug = 'five-acre-jv' WHERE ID = 3193
UPDATE Conflict SET Slug = 'flatbush-340' WHERE ID = 558
UPDATE Conflict SET Slug = 'flatbush-340-lender' WHERE ID = 3278
UPDATE Conflict SET Slug = 'flights-formerly-trump-flights' WHERE ID = 93
UPDATE Conflict SET Slug = 'florham-park-developers' WHERE ID = 3211
UPDATE Conflict SET Slug = 'florham-park-realty-associates' WHERE ID = 821
UPDATE Conflict SET Slug = 'florida-properties-management' WHERE ID = 94
UPDATE Conflict SET Slug = 'fontainbleu-apartments' WHERE ID = 95
UPDATE Conflict SET Slug = 'ford-motor-company' WHERE ID = 3157
UPDATE Conflict SET Slug = 'ford-motors' WHERE ID = 404
UPDATE Conflict SET Slug = 'ford-mtr' WHERE ID = 826
UPDATE Conflict SET Slug = 'franklin-templeton-investments' WHERE ID = 3281
UPDATE Conflict SET Slug = 'fred-c-trump-trust' WHERE ID = 3379
UPDATE Conflict SET Slug = 'friends-of-idf-israel-defense-forces' WHERE ID = 3170
UPDATE Conflict SET Slug = 'galbreath-columbus-circle-development-associates' WHERE ID = 96
UPDATE Conflict SET Slug = 'gallant-funding' WHERE ID = 828
UPDATE Conflict SET Slug = 'gary-cohn' WHERE ID = 9697
UPDATE Conflict SET Slug = 'gcm-trust' WHERE ID = 3380
UPDATE Conflict SET Slug = 'gellert-80-west-end' WHERE ID = 527
UPDATE Conflict SET Slug = 'general-services-administration' WHERE ID = 97
UPDATE Conflict SET Slug = 'georgia-st-bonds' WHERE ID = 837
UPDATE Conflict SET Slug = 'gept-delmonico' WHERE ID = 98
UPDATE Conflict SET Slug = 'getty-images' WHERE ID = 480
UPDATE Conflict SET Slug = 'glaxosmithkline' WHERE ID = 412
UPDATE Conflict SET Slug = 'global-gateway-alliance' WHERE ID = 3225
UPDATE Conflict SET Slug = 'goldman-sachs' WHERE ID = 403
UPDATE Conflict SET Slug = 'golf-productions' WHERE ID = 99
UPDATE Conflict SET Slug = 'google' WHERE ID = 405
UPDATE Conflict SET Slug = 'gowan-associates' WHERE ID = 546
UPDATE Conflict SET Slug = 'greenburgh-ny' WHERE ID = 845
UPDATE Conflict SET Slug = 'greenburgh-ny' WHERE ID = 3292
UPDATE Conflict SET Slug = 'hartford-funds' WHERE ID = 3269
UPDATE Conflict SET Slug = 'hary-tanoesoedibjo' WHERE ID = 100
UPDATE Conflict SET Slug = 'helicopter-air-services' WHERE ID = 101
UPDATE Conflict SET Slug = 'hennessy-funds' WHERE ID = 3251
UPDATE Conflict SET Slug = 'hennessy-gas-utility' WHERE ID = 855
UPDATE Conflict SET Slug = 'hennessy-gas-utility-index-fund-investor-class-shares' WHERE ID = 3284
UPDATE Conflict SET Slug = 'heritage-equities' WHERE ID = 3391
UPDATE Conflict SET Slug = 'highlander-hall' WHERE ID = 102
UPDATE Conflict SET Slug = 'holds-united-technologies' WHERE ID = 103
UPDATE Conflict SET Slug = 'home-depot' WHERE ID = 864
UPDATE Conflict SET Slug = 'honest-buildings' WHERE ID = 3279
UPDATE Conflict SET Slug = 'hospital-for-special-surgery' WHERE ID = 433
UPDATE Conflict SET Slug = 'how-to-get-rich' WHERE ID = 104
UPDATE Conflict SET Slug = 'hudson-waterfront-associates' WHERE ID = 105
UPDATE Conflict SET Slug = 'hudson-waterfront-associates-i' WHERE ID = 106
UPDATE Conflict SET Slug = 'hudson-waterfront-associates-ii' WHERE ID = 107
UPDATE Conflict SET Slug = 'hudson-waterfront-associates-iii' WHERE ID = 108
UPDATE Conflict SET Slug = 'hudson-waterfront-associates-iv' WHERE ID = 109
UPDATE Conflict SET Slug = 'hudson-waterfront-associates-v' WHERE ID = 110
UPDATE Conflict SET Slug = 'hwa-1290-ill' WHERE ID = 111
UPDATE Conflict SET Slug = 'hwa-1290-iv' WHERE ID = 112
UPDATE Conflict SET Slug = 'hwa-1290-v' WHERE ID = 113
UPDATE Conflict SET Slug = 'hwa-555-owners' WHERE ID = 114
UPDATE Conflict SET Slug = 'hyde-park' WHERE ID = 115
UPDATE Conflict SET Slug = 'idb-bank' WHERE ID = 3159
UPDATE Conflict SET Slug = 'identity-theft-productions' WHERE ID = 3381
UPDATE Conflict SET Slug = 'indian-hills-holdings-formerly-indian-hills-development' WHERE ID = 3352
UPDATE Conflict SET Slug = 'indian-hills-holdings-formerly-indian-hills-development' WHERE ID = 116
UPDATE Conflict SET Slug = 'internal-revenue-service' WHERE ID = 117
UPDATE Conflict SET Slug = 'invesco' WHERE ID = 3286
UPDATE Conflict SET Slug = 'investors-savings-bank' WHERE ID = 3216
UPDATE Conflict SET Slug = 'iroquois-properties' WHERE ID = 850
UPDATE Conflict SET Slug = 'iroquois-properties-realty' WHERE ID = 3195
UPDATE Conflict SET Slug = 'ishares-20-year-treas-bond-etf' WHERE ID = 881
UPDATE Conflict SET Slug = 'it-apparel' WHERE ID = 3382
UPDATE Conflict SET Slug = 'it-collection' WHERE ID = 3383
UPDATE Conflict SET Slug = 'it-international' WHERE ID = 3384
UPDATE Conflict SET Slug = 'it-investors' WHERE ID = 3310
UPDATE Conflict SET Slug = 'it-operations' WHERE ID = 3308
UPDATE Conflict SET Slug = 'it-outerwear' WHERE ID = 3385
UPDATE Conflict SET Slug = 'it-promotions' WHERE ID = 3386
UPDATE Conflict SET Slug = 'it-properties' WHERE ID = 3387
UPDATE Conflict SET Slug = 'itjk-investments' WHERE ID = 3389
UPDATE Conflict SET Slug = 'ivanka-m-trump-charitable-fund' WHERE ID = 470
UPDATE Conflict SET Slug = 'ivanka-trump-brand' WHERE ID = 444
UPDATE Conflict SET Slug = 'ivanka-trump-business-trust' WHERE ID = 478
UPDATE Conflict SET Slug = 'ivanka-trump-fine-jewelry' WHERE ID = 9659
UPDATE Conflict SET Slug = 'ivanka-trump-marks' WHERE ID = 3311
UPDATE Conflict SET Slug = 'ivanka-trump-received-15001-50000-in-rent-or-royalties-income-from-k-26-journal-square-llc-commercial-real-estate-in-jersey-city-nj-the-year-before-her-appointment-as-her-father39s-presidential-adviser' WHERE ID = 3270
UPDATE Conflict SET Slug = 'jp-morgan' WHERE ID = 887
UPDATE Conflict SET Slug = 'janus-henderson-investors' WHERE ID = 3160
UPDATE Conflict SET Slug = 'jck-cadre' WHERE ID = 882
UPDATE Conflict SET Slug = 'jho-low' WHERE ID = 9689
UPDATE Conflict SET Slug = 'jk-thrive-iv' WHERE ID = 884
UPDATE Conflict SET Slug = 'jk-thrive-v' WHERE ID = 885
UPDATE Conflict SET Slug = 'jk2-westminster' WHERE ID = 3243
UPDATE Conflict SET Slug = 'jkm-capital' WHERE ID = 886
UPDATE Conflict SET Slug = 'johnson-johnson' WHERE ID = 414
UPDATE Conflict SET Slug = 'jose-e-b-antonio' WHERE ID = 399
UPDATE Conflict SET Slug = 'jp-morgan' WHERE ID = 3196
UPDATE Conflict SET Slug = 'jp-morgan-chase' WHERE ID = 400
UPDATE Conflict SET Slug = 'jp-morgan-chase-co' WHERE ID = 3263
UPDATE Conflict SET Slug = 'jp-morgan-chase-bank' WHERE ID = 3288
UPDATE Conflict SET Slug = 'jp-morgan-core-bond-fund-select' WHERE ID = 3178
UPDATE Conflict SET Slug = 'jpmorgan-high-yield' WHERE ID = 3199
UPDATE Conflict SET Slug = 'jupiter-golf-club' WHERE ID = 118
UPDATE Conflict SET Slug = 'k-26-journal-square' WHERE ID = 502
UPDATE Conflict SET Slug = 'k-30-journal-square' WHERE ID = 508
UPDATE Conflict SET Slug = 'k-astoria' WHERE ID = 617
UPDATE Conflict SET Slug = 'k-astoria-i' WHERE ID = 3390
UPDATE Conflict SET Slug = 'k-gaia-village-2-associates' WHERE ID = 901
UPDATE Conflict SET Slug = 'k-gaia-village-1-associates' WHERE ID = 517
UPDATE Conflict SET Slug = 'k-maryland-associates' WHERE ID = 651
UPDATE Conflict SET Slug = 'k-one-journal-square' WHERE ID = 905
UPDATE Conflict SET Slug = 'k-stonehage-village-1-associates' WHERE ID = 807
UPDATE Conflict SET Slug = 'k2-26js-member' WHERE ID = 3294
UPDATE Conflict SET Slug = 'k2w2-26js-holdings' WHERE ID = 3264
UPDATE Conflict SET Slug = 'kaszek-ventures' WHERE ID = 914
UPDATE Conflict SET Slug = 'kaszek-ventures-ii' WHERE ID = 3282
UPDATE Conflict SET Slug = 'kay-arr-realty-associates' WHERE ID = 3217
UPDATE Conflict SET Slug = 'kb-astoria' WHERE ID = 3248
UPDATE Conflict SET Slug = 'kc-dumbo' WHERE ID = 3339
UPDATE Conflict SET Slug = 'kc-dumbo-hotel' WHERE ID = 521
UPDATE Conflict SET Slug = 'kc-dumbo-office' WHERE ID = 919
UPDATE Conflict SET Slug = 'kc-profit-participation' WHERE ID = 3192
UPDATE Conflict SET Slug = 'kcof-215-moore' WHERE ID = 935
UPDATE Conflict SET Slug = 'kf-middle-river' WHERE ID = 581
UPDATE Conflict SET Slug = 'kf-westwood-partner' WHERE ID = 660
UPDATE Conflict SET Slug = 'kf-c-iii-recovery-fund-ii' WHERE ID = 940
UPDATE Conflict SET Slug = 'kf-faire-fund-ii' WHERE ID = 942
UPDATE Conflict SET Slug = 'kf-park-street-capital-pe-fund-ix' WHERE ID = 944
UPDATE Conflict SET Slug = 'kf-rcg-longview-debt-fund-iv' WHERE ID = 946
UPDATE Conflict SET Slug = 'kf-bls-member' WHERE ID = 495
UPDATE Conflict SET Slug = 'kf-centerview' WHERE ID = 950
UPDATE Conflict SET Slug = 'kf-wip-co-investors' WHERE ID = 952
UPDATE Conflict SET Slug = 'kff-29-second-avenue' WHERE ID = 953
UPDATE Conflict SET Slug = 'kinder-morgan' WHERE ID = 419
UPDATE Conflict SET Slug = 'kkc-associates' WHERE ID = 595
UPDATE Conflict SET Slug = 'korean-aerospace-industries' WHERE ID = 455
UPDATE Conflict SET Slug = 'kushner-companies' WHERE ID = 439
UPDATE Conflict SET Slug = 'kushner-credit-opportunity-fund' WHERE ID = 3262
UPDATE Conflict SET Slug = 'kushner-family-foundation' WHERE ID = 3221
UPDATE Conflict SET Slug = 'kushner-journal-square' WHERE ID = 3392
UPDATE Conflict SET Slug = 'kushner-media-ventures' WHERE ID = 958
UPDATE Conflict SET Slug = 'kushner-midwest-partners' WHERE ID = 591
UPDATE Conflict SET Slug = 'kushner-midwest-partners-1' WHERE ID = 3194
UPDATE Conflict SET Slug = 'kushner-philadelphia' WHERE ID = 3185
UPDATE Conflict SET Slug = 'kushner-philadelphia-member' WHERE ID = 534
UPDATE Conflict SET Slug = 'kushner-village-2' WHERE ID = 3293
UPDATE Conflict SET Slug = 'kushner-village-2-member' WHERE ID = 962
UPDATE Conflict SET Slug = 'kushner-village-325' WHERE ID = 3237
UPDATE Conflict SET Slug = 'kushner-village-4-spe' WHERE ID = 3244
UPDATE Conflict SET Slug = 'lacey-township-building-corp' WHERE ID = 3173
UPDATE Conflict SET Slug = 'ladder-capital' WHERE ID = 119
UPDATE Conflict SET Slug = 'lamington-family-holdings' WHERE ID = 120
UPDATE Conflict SET Slug = 'lamington-farm-club' WHERE ID = 121
UPDATE Conflict SET Slug = 'landings-apartments' WHERE ID = 969
UPDATE Conflict SET Slug = 'landings-at-caspian-pointe' WHERE ID = 973
UPDATE Conflict SET Slug = 'landings-at-harborside' WHERE ID = 1627
UPDATE Conflict SET Slug = 'landings-chicago' WHERE ID = 3168
UPDATE Conflict SET Slug = 'lawrence-towers-apartments' WHERE ID = 122
UPDATE Conflict SET Slug = 'le-chateau-des-palmiers' WHERE ID = 447
UPDATE Conflict SET Slug = 'leeds-equity-partners' WHERE ID = 1626
UPDATE Conflict SET Slug = 'lfb-acquisition' WHERE ID = 123
UPDATE Conflict SET Slug = 'lido-city-development' WHERE ID = 394
UPDATE Conflict SET Slug = 'lincoln-financial-group' WHERE ID = 3393
UPDATE Conflict SET Slug = 'lindenlawn-apartment-associates' WHERE ID = 990
UPDATE Conflict SET Slug = 'livingston-hills' WHERE ID = 3394
UPDATE Conflict SET Slug = 'lmp' WHERE ID = 3395
UPDATE Conflict SET Slug = 'lodi-phillipsburg' WHERE ID = 3396
UPDATE Conflict SET Slug = 'lord-abbett-co' WHERE ID = 3397
UPDATE Conflict SET Slug = 'lw-investors' WHERE ID = 991
UPDATE Conflict SET Slug = 'madison-ave-diamonds' WHERE ID = 9660
UPDATE Conflict SET Slug = 'magnolia-building-associates' WHERE ID = 996
UPDATE Conflict SET Slug = 'mar-a-lago-club' WHERE ID = 124
UPDATE Conflict SET Slug = 'marc-kasowitz' WHERE ID = 457
UPDATE Conflict SET Slug = 'martha-bell-associates' WHERE ID = 3399
UPDATE Conflict SET Slug = 'maryanne-trump-trust' WHERE ID = 3400
UPDATE Conflict SET Slug = 'maryland-st-dept' WHERE ID = 1003
UPDATE Conflict SET Slug = 'maryland-st-dept-transn' WHERE ID = 3260
UPDATE Conflict SET Slug = 'massachusetts-st-wtr-polutn-bonds' WHERE ID = 1004
UPDATE Conflict SET Slug = 'mecklenburg-cnty-nc' WHERE ID = 1005
UPDATE Conflict SET Slug = 'mecklenburg-county-nc' WHERE ID = 3222
UPDATE Conflict SET Slug = 'megalith-capital-management' WHERE ID = 3401
UPDATE Conflict SET Slug = 'melania' WHERE ID = 9661
UPDATE Conflict SET Slug = 'melania-llc' WHERE ID = 435
UPDATE Conflict SET Slug = 'melania-marks' WHERE ID = 3403
UPDATE Conflict SET Slug = 'merck' WHERE ID = 409
UPDATE Conflict SET Slug = 'merrill-lynch' WHERE ID = 3404
UPDATE Conflict SET Slug = 'merrill-lynch-credit-corporation' WHERE ID = 9648
UPDATE Conflict SET Slug = 'merrill-lynch-credit-corporation-dba-merrill-lynch-home-loans' WHERE ID = 125
UPDATE Conflict SET Slug = 'merritt-associates' WHERE ID = 1007
UPDATE Conflict SET Slug = 'met-transprtn-auth-ny-revenue-rfdg-transprtn-ser-c' WHERE ID = 3208
UPDATE Conflict SET Slug = 'met-transprtn-auth-ny-revenue-transn-ser-a' WHERE ID = 3172
UPDATE Conflict SET Slug = 'met-transprtn-ser-a' WHERE ID = 1009
UPDATE Conflict SET Slug = 'met-transprtn-ser-c' WHERE ID = 1008
UPDATE Conflict SET Slug = 'metallurgical-corporation-of-china-mcc' WHERE ID = 442
UPDATE Conflict SET Slug = 'metlife' WHERE ID = 1010
UPDATE Conflict SET Slug = 'mgm' WHERE ID = 427
UPDATE Conflict SET Slug = 'mgmmark-burnett-productions' WHERE ID = 3315
UPDATE Conflict SET Slug = 'michael-cohen' WHERE ID = 449
UPDATE Conflict SET Slug = 'michael-flynn' WHERE ID = 9686
UPDATE Conflict SET Slug = 'microsoft' WHERE ID = 1011
UPDATE Conflict SET Slug = 'midland-associates' WHERE ID = 126
UPDATE Conflict SET Slug = 'midocean-credit-partners' WHERE ID = 9615
UPDATE Conflict SET Slug = 'milford-building' WHERE ID = 3405
UPDATE Conflict SET Slug = 'millington-bank' WHERE ID = 3198
UPDATE Conflict SET Slug = 'miss-universe-formerly-trump-pageants' WHERE ID = 127
UPDATE Conflict SET Slug = 'mmll' WHERE ID = 883
UPDATE Conflict SET Slug = 'mnc-group' WHERE ID = 441
UPDATE Conflict SET Slug = 'mobile-payroll-construction' WHERE ID = 128
UPDATE Conflict SET Slug = 'monmouth-mall' WHERE ID = 782
UPDATE Conflict SET Slug = 'monmouth-mall-2' WHERE ID = 1019
UPDATE Conflict SET Slug = 'morgan-stanley' WHERE ID = 402
UPDATE Conflict SET Slug = 'mt-pleasant' WHERE ID = 3406
UPDATE Conflict SET Slug = 'murray-energy' WHERE ID = 9699
UPDATE Conflict SET Slug = 'mz-berger-company' WHERE ID = 3407
UPDATE Conflict SET Slug = 'nassau-cnty-ny' WHERE ID = 1028
UPDATE Conflict SET Slug = 'nassau-county-ny' WHERE ID = 3283
UPDATE Conflict SET Slug = 'national-endowment-for-the-humanities' WHERE ID = 3253
UPDATE Conflict SET Slug = 'national-labor-relations-board' WHERE ID = 129
UPDATE Conflict SET Slug = 'nbc' WHERE ID = 130
UPDATE Conflict SET Slug = 'netcong-heights-associates' WHERE ID = 3408
UPDATE Conflict SET Slug = 'never-give-up' WHERE ID = 131
UPDATE Conflict SET Slug = 'new-jersey-renewable-power' WHERE ID = 1031
UPDATE Conflict SET Slug = 'new-jersey-renewable-power-corp' WHERE ID = 1030
UPDATE Conflict SET Slug = 'new-puck' WHERE ID = 3347
UPDATE Conflict SET Slug = 'new-puck-corp' WHERE ID = 3169
UPDATE Conflict SET Slug = 'new-puck-corp' WHERE ID = 3338
UPDATE Conflict SET Slug = 'new-sunshine-llc' WHERE ID = 132
UPDATE Conflict SET Slug = 'new-york-city-ny-muni-wtr' WHERE ID = 1036
UPDATE Conflict SET Slug = 'new-york-community-bank' WHERE ID = 3218
UPDATE Conflict SET Slug = 'new-york-ny-ser-b' WHERE ID = 1037
UPDATE Conflict SET Slug = 'new-york-ny-ser-e' WHERE ID = 1038
UPDATE Conflict SET Slug = 'new-york-ny-var-subser' WHERE ID = 1039
UPDATE Conflict SET Slug = 'new-york-ny-var-subser-l-4' WHERE ID = 3197
UPDATE Conflict SET Slug = 'new-york-presbyterian-hospital' WHERE ID = 432
UPDATE Conflict SET Slug = 'new-york-st-bonds' WHERE ID = 1050
UPDATE Conflict SET Slug = 'new-york-st-dorm-auth-revenues-st-supported-debt-third-gen-resolution-st-univ-edl-facs-ser-a' WHERE ID = 3224
UPDATE Conflict SET Slug = 'new-york-st-dorm-auth-revs-nonst-supported-debt-cornell-univ-b' WHERE ID = 3266
UPDATE Conflict SET Slug = 'new-york-st-dorm-auth-sales-tax-revenue-rfdg-ser-a' WHERE ID = 3164
UPDATE Conflict SET Slug = 'new-york-st-dorm-auth-ser-a' WHERE ID = 1041
UPDATE Conflict SET Slug = 'new-york-st-dorm-auth-ser-e' WHERE ID = 1042
UPDATE Conflict SET Slug = 'new-york-st-dorm-auth-st-personal-income-tax-revenue-rfdg-ser-e' WHERE ID = 3191
UPDATE Conflict SET Slug = 'new-york-st-dorm-auth-st-personal-income-tax-revenue-unrefunded-ser-a' WHERE ID = 3156
UPDATE Conflict SET Slug = 'new-york-st-dorm-auth-st-personal-ser-a' WHERE ID = 1043
UPDATE Conflict SET Slug = 'new-york-st-dorm-univ-b' WHERE ID = 1040
UPDATE Conflict SET Slug = 'new-york-st-environ' WHERE ID = 1044
UPDATE Conflict SET Slug = 'new-york-st-environ-facs-corp-st-clean-wtr-amp-drinking-revolving-fdsnyc-mun-wtr-a' WHERE ID = 3167
UPDATE Conflict SET Slug = 'new-york-st-local-govt-assistance-corp' WHERE ID = 1045
UPDATE Conflict SET Slug = 'new-york-st-local-govt-assistance-corp-rfdg-sub-lien-ser-a' WHERE ID = 3271
UPDATE Conflict SET Slug = 'new-york-st-ser-a' WHERE ID = 1046
UPDATE Conflict SET Slug = 'new-york-st-ser-e' WHERE ID = 1047
UPDATE Conflict SET Slug = 'new-york-st-thruway' WHERE ID = 1048
UPDATE Conflict SET Slug = 'new-york-st-thruway-auth-2nd-gen-highway-amp-bridge-trust-fund-ser-a' WHERE ID = 3252
UPDATE Conflict SET Slug = 'new-york-st-urban-dev' WHERE ID = 1049
UPDATE Conflict SET Slug = 'new-york-st-urban-dev-corp-rev-st-pers-income-tax-ser-a1' WHERE ID = 3257
UPDATE Conflict SET Slug = 'new-york-state' WHERE ID = 3171
UPDATE Conflict SET Slug = 'new-york-state-urban-dev' WHERE ID = 1051
UPDATE Conflict SET Slug = 'new-york-state-urban-dev-corp-rev-rfdg-svc-contract-ser-b' WHERE ID = 3296
UPDATE Conflict SET Slug = 'new-york-ny' WHERE ID = 3241
UPDATE Conflict SET Slug = 'news-corp' WHERE ID = 3176
UPDATE Conflict SET Slug = 'news-corporation' WHERE ID = 1052
UPDATE Conflict SET Slug = 'nextera-energy' WHERE ID = 1053
UPDATE Conflict SET Slug = 'nippon-telegraph-telephone-corp-ntt' WHERE ID = 461
UPDATE Conflict SET Slug = 'nitto-world' WHERE ID = 133
UPDATE Conflict SET Slug = 'nk-80-maiden-holdings' WHERE ID = 3277
UPDATE Conflict SET Slug = 'nk-80-maiden-mezz' WHERE ID = 3255
UPDATE Conflict SET Slug = 'nk-80-maiden-owner' WHERE ID = 3183
UPDATE Conflict SET Slug = 'normandy-real-estate-partners' WHERE ID = 463
UPDATE Conflict SET Slug = 'novartis' WHERE ID = 453
UPDATE Conflict SET Slug = 'nuveen-tiaa' WHERE ID = 3232
UPDATE Conflict SET Slug = 'nuveen-enhanced-amt-free-municipal-credit-opportunities-fund' WHERE ID = 1061
UPDATE Conflict SET Slug = 'o-townhomes' WHERE ID = 3409
UPDATE Conflict SET Slug = 'oakwood-chicago' WHERE ID = 3179
UPDATE Conflict SET Slug = 'oakwood-chicago-holding-llc' WHERE ID = 3228
UPDATE Conflict SET Slug = 'oakwood-garden-associates' WHERE ID = 1062
UPDATE Conflict SET Slug = 'observer-capital' WHERE ID = 1072
UPDATE Conflict SET Slug = 'observer-media' WHERE ID = 3410
UPDATE Conflict SET Slug = 'oc-partners' WHERE ID = 1073
UPDATE Conflict SET Slug = 'ocean-development' WHERE ID = 134
UPDATE Conflict SET Slug = 'office-of-government-ethics' WHERE ID = 475
UPDATE Conflict SET Slug = 'old-post-office-hotel' WHERE ID = 9672
UPDATE Conflict SET Slug = 'one-central-park-west' WHERE ID = 135
UPDATE Conflict SET Slug = 'onondaga' WHERE ID = 1087
UPDATE Conflict SET Slug = 'onondaga-county-ny' WHERE ID = 3174
UPDATE Conflict SET Slug = 'operation-smile' WHERE ID = 431
UPDATE Conflict SET Slug = 'opo-hotel-manager' WHERE ID = 136
UPDATE Conflict SET Slug = 'oppenheimerfunds' WHERE ID = 1090
UPDATE Conflict SET Slug = 'oregon-st' WHERE ID = 1092
UPDATE Conflict SET Slug = 'ownership-rights' WHERE ID = 3227
UPDATE Conflict SET Slug = 'owo-developer' WHERE ID = 137
UPDATE Conflict SET Slug = 'oxford-arms-associates' WHERE ID = 3411
UPDATE Conflict SET Slug = 'pv-development' WHERE ID = 1094
UPDATE Conflict SET Slug = 'panama-ocean-club-management' WHERE ID = 138
UPDATE Conflict SET Slug = 'paramount-rpv-holdings' WHERE ID = 139
UPDATE Conflict SET Slug = 'parc-consulting' WHERE ID = 140
UPDATE Conflict SET Slug = 'park-briar-associates' WHERE ID = 141
UPDATE Conflict SET Slug = 'park-lake-village' WHERE ID = 3412
UPDATE Conflict SET Slug = 'park-lane-mobile-home-park' WHERE ID = 3413
UPDATE Conflict SET Slug = 'park-street-capital' WHERE ID = 945
UPDATE Conflict SET Slug = 'partnership-for-new-york-city' WHERE ID = 3414
UPDATE Conflict SET Slug = 'paul-manafort' WHERE ID = 9685
UPDATE Conflict SET Slug = 'penguin-random-house' WHERE ID = 471
UPDATE Conflict SET Slug = 'pepsico' WHERE ID = 1101
UPDATE Conflict SET Slug = 'pfizer' WHERE ID = 411
UPDATE Conflict SET Slug = 'philippine-government' WHERE ID = 459
UPDATE Conflict SET Slug = 'phillips-66' WHERE ID = 418
UPDATE Conflict SET Slug = 'pier-village' WHERE ID = 464
UPDATE Conflict SET Slug = 'pimco' WHERE ID = 3209
UPDATE Conflict SET Slug = 'pimco-enhanced' WHERE ID = 1108
UPDATE Conflict SET Slug = 'pimco-enhanced-short-mat-active-etf' WHERE ID = 3204
UPDATE Conflict SET Slug = 'pimco-rae-fundamental-advantage-plus-fund' WHERE ID = 1109
UPDATE Conflict SET Slug = 'pimco-rae-fundamental-advantage-plus-fund-class-p' WHERE ID = 3210
UPDATE Conflict SET Slug = 'pine-hill-development' WHERE ID = 142
UPDATE Conflict SET Slug = 'pinecrest-lake-building-associates' WHERE ID = 1112
UPDATE Conflict SET Slug = 'pinefield-manor' WHERE ID = 3415
UPDATE Conflict SET Slug = 'plaza-consulting' WHERE ID = 143
UPDATE Conflict SET Slug = 'poker-venture' WHERE ID = 144
UPDATE Conflict SET Slug = 'police-athletic-league' WHERE ID = 145
UPDATE Conflict SET Slug = 'port-auth-of-new-york' WHERE ID = 1119
UPDATE Conflict SET Slug = 'port-authority-of-new-york-new-jersey' WHERE ID = 3163
UPDATE Conflict SET Slug = 'powerhouse-associates' WHERE ID = 3416
UPDATE Conflict SET Slug = 'president-elects-transition-team' WHERE ID = 3418
UPDATE Conflict SET Slug = 'president-elects-transition-team' WHERE ID = 8772
UPDATE Conflict SET Slug = 'princeton-horizon-apartments' WHERE ID = 3417
UPDATE Conflict SET Slug = 'principal-funds' WHERE ID = 3273
UPDATE Conflict SET Slug = 'proctor-gamble' WHERE ID = 413
UPDATE Conflict SET Slug = 'prospect-place' WHERE ID = 9663
UPDATE Conflict SET Slug = 'puck-building' WHERE ID = 1033
UPDATE Conflict SET Slug = 'puck-residential-associates' WHERE ID = 516
UPDATE Conflict SET Slug = 'qatar-government' WHERE ID = 456
UPDATE Conflict SET Slug = 'quail-ridge' WHERE ID = 469
UPDATE Conflict SET Slug = 'qvc' WHERE ID = 146
UPDATE Conflict SET Slug = 'rcg-longview' WHERE ID = 3348
UPDATE Conflict SET Slug = 'rcg-longview-debt-fund-iv' WHERE ID = 947
UPDATE Conflict SET Slug = 'real-estate-board-of-new-york' WHERE ID = 3419
UPDATE Conflict SET Slug = 'reg-tru-equities' WHERE ID = 147
UPDATE Conflict SET Slug = 'regal-bank' WHERE ID = 1130
UPDATE Conflict SET Slug = 'related-companies' WHERE ID = 436
UPDATE Conflict SET Slug = 'restaurant-40' WHERE ID = 148
UPDATE Conflict SET Slug = 'river-edge-apartments' WHERE ID = 3420
UPDATE Conflict SET Slug = 'riverhead-reeves' WHERE ID = 3421
UPDATE Conflict SET Slug = 'riverhead-sound' WHERE ID = 3422
UPDATE Conflict SET Slug = 'rivernorth' WHERE ID = 3423
UPDATE Conflict SET Slug = 'rockwell-automation' WHERE ID = 1137
UPDATE Conflict SET Slug = 'route-10-associates' WHERE ID = 509
UPDATE Conflict SET Slug = 'royal-bank-america' WHERE ID = 149
UPDATE Conflict SET Slug = 'royal-bank-of-canada' WHERE ID = 423
UPDATE Conflict SET Slug = 'rpv-development' WHERE ID = 150
UPDATE Conflict SET Slug = 'rues-lane-building-corp' WHERE ID = 3424
UPDATE Conflict SET Slug = 'russia' WHERE ID = 9705
UPDATE Conflict SET Slug = 'sales-tax-asset-receivable' WHERE ID = 1145
UPDATE Conflict SET Slug = 'sales-tax-asset-receivable-corp-ny-rfdg-fiscal-2015-ser-a' WHERE ID = 3181
UPDATE Conflict SET Slug = 'samuel-patten' WHERE ID = 9690
UPDATE Conflict SET Slug = 'saudi-arabia' WHERE ID = 9676
UPDATE Conflict SET Slug = 'saudi-arabia-and-emirati-real-estate-and-hotel-deals' WHERE ID = 396
UPDATE Conflict SET Slug = 'schlumberger-ltd' WHERE ID = 1146
UPDATE Conflict SET Slug = 'schoolhouse-jv' WHERE ID = 3425
UPDATE Conflict SET Slug = 'scion' WHERE ID = 481
UPDATE Conflict SET Slug = 'scotland-acquisitions' WHERE ID = 151
UPDATE Conflict SET Slug = 'screen-actors-guild' WHERE ID = 3426
UPDATE Conflict SET Slug = 'seven-springs' WHERE ID = 152
UPDATE Conflict SET Slug = 'shell' WHERE ID = 415
UPDATE Conflict SET Slug = 'sheri-dillon' WHERE ID = 9693
UPDATE Conflict SET Slug = 'shore-haven-apt1' WHERE ID = 153
UPDATE Conflict SET Slug = 'shore-haven-management' WHERE ID = 154
UPDATE Conflict SET Slug = 'shore-haven-shopping-center' WHERE ID = 155
UPDATE Conflict SET Slug = 'signature-bank' WHERE ID = 395
UPDATE Conflict SET Slug = 'signature-bank-new-york-ny' WHERE ID = 3213
UPDATE Conflict SET Slug = 'sixty-capital-fund' WHERE ID = 1155
UPDATE Conflict SET Slug = 'sixty-one-associates' WHERE ID = 1156
UPDATE Conflict SET Slug = 'sixty-six-west-associates' WHERE ID = 1157
UPDATE Conflict SET Slug = 'skyline-kushner' WHERE ID = 602
UPDATE Conflict SET Slug = 'skytop-gardens' WHERE ID = 3427
UPDATE Conflict SET Slug = 'softbank-vision-fund' WHERE ID = 446
UPDATE Conflict SET Slug = 'spring-creek-plaza' WHERE ID = 156
UPDATE Conflict SET Slug = 'sq-associates' WHERE ID = 1165
UPDATE Conflict SET Slug = 'sqk-associates' WHERE ID = 1167
UPDATE Conflict SET Slug = 'square-mile-partners' WHERE ID = 1166
UPDATE Conflict SET Slug = 'starrett-city-associates-lp' WHERE ID = 157
UPDATE Conflict SET Slug = 'state-of-alabama' WHERE ID = 3187
UPDATE Conflict SET Slug = 'state-of-california' WHERE ID = 3274
UPDATE Conflict SET Slug = 'state-of-georgia' WHERE ID = 3184
UPDATE Conflict SET Slug = 'state-of-maryland' WHERE ID = 3166
UPDATE Conflict SET Slug = 'state-of-massachusetts' WHERE ID = 3207
UPDATE Conflict SET Slug = 'state-of-oregon' WHERE ID = 3165
UPDATE Conflict SET Slug = 'state-of-utah' WHERE ID = 3205
UPDATE Conflict SET Slug = 'state-of-virginia' WHERE ID = 3275
UPDATE Conflict SET Slug = 'state-street-global-advisors' WHERE ID = 3428
UPDATE Conflict SET Slug = 'state-tower-of-syracuse-associates' WHERE ID = 1186
UPDATE Conflict SET Slug = 'stefan-passantino' WHERE ID = 9694
UPDATE Conflict SET Slug = 'stephanie-clifford-aka-stormy-daniels' WHERE ID = 385
UPDATE Conflict SET Slug = 'stephanie-clifford-akastormy-daniels' WHERE ID = 158
UPDATE Conflict SET Slug = 'stone-16-associates' WHERE ID = 921
UPDATE Conflict SET Slug = 'storage-106' WHERE ID = 159
UPDATE Conflict SET Slug = 'sussex-hall' WHERE ID = 160
UPDATE Conflict SET Slug = 't-express' WHERE ID = 161
UPDATE Conflict SET Slug = 't-international-realty-aka-trump-international-realty' WHERE ID = 386
UPDATE Conflict SET Slug = 't-international-realty-akatrump-international-realty' WHERE ID = 162
UPDATE Conflict SET Slug = 't-retail' WHERE ID = 9634
UPDATE Conflict SET Slug = 't-mobile' WHERE ID = 9692
UPDATE Conflict SET Slug = 'tag-air' WHERE ID = 163
UPDATE Conflict SET Slug = 'taylor-edison-jv' WHERE ID = 3429
UPDATE Conflict SET Slug = 'tc-marks-buenos-aires' WHERE ID = 164
UPDATE Conflict SET Slug = 'templeton-gim' WHERE ID = 1201
UPDATE Conflict SET Slug = 'templeton-global-income-fund' WHERE ID = 3188
UPDATE Conflict SET Slug = 'thc-baku-hotel-manager-services' WHERE ID = 165
UPDATE Conflict SET Slug = 'thc-baku-services' WHERE ID = 166
UPDATE Conflict SET Slug = 'thc-barra-hotelaria' WHERE ID = 167
UPDATE Conflict SET Slug = 'thc-central-reservations' WHERE ID = 168
UPDATE Conflict SET Slug = 'thc-china-development' WHERE ID = 169
UPDATE Conflict SET Slug = 'thc-china-technical-services' WHERE ID = 170
UPDATE Conflict SET Slug = 'thc-dc-restaurant-hospitality' WHERE ID = 171
UPDATE Conflict SET Slug = 'thc-development-brazil' WHERE ID = 172
UPDATE Conflict SET Slug = 'thc-dubai-ii-hotel-manager' WHERE ID = 173
UPDATE Conflict SET Slug = 'thc-hotel-development' WHERE ID = 174
UPDATE Conflict SET Slug = 'thc-imea-development' WHERE ID = 175
UPDATE Conflict SET Slug = 'thc-jeddah-hotel-advisor' WHERE ID = 176
UPDATE Conflict SET Slug = 'thc-jeddah-hotel-manager' WHERE ID = 177
UPDATE Conflict SET Slug = 'thc-miami-restaurant-hospitality' WHERE ID = 178
UPDATE Conflict SET Slug = 'thc-qatar-hotel-manager' WHERE ID = 179
UPDATE Conflict SET Slug = 'thc-rio' WHERE ID = 180
UPDATE Conflict SET Slug = 'thc-sales-marketing' WHERE ID = 181
UPDATE Conflict SET Slug = 'thc-sales-amp-marketing' WHERE ID = 387
UPDATE Conflict SET Slug = 'thc-services-shenzhen' WHERE ID = 182
UPDATE Conflict SET Slug = 'thc-shenzhen-hotel-manager' WHERE ID = 183
UPDATE Conflict SET Slug = 'thc-vancouver' WHERE ID = 184
UPDATE Conflict SET Slug = 'thc-venture-i' WHERE ID = 185
UPDATE Conflict SET Slug = 'thc-venture-ii' WHERE ID = 186
UPDATE Conflict SET Slug = 'thc-venture-iii-now-tttt-venture' WHERE ID = 187
UPDATE Conflict SET Slug = 'the-america-we-deserve' WHERE ID = 188
UPDATE Conflict SET Slug = 'the-art-of-the-comeback' WHERE ID = 189
UPDATE Conflict SET Slug = 'the-art-of-the-deal' WHERE ID = 190
UPDATE Conflict SET Slug = 'the-att-building' WHERE ID = 9684
UPDATE Conflict SET Slug = 'the-best-real-estate-advice-i-ever-received' WHERE ID = 191
UPDATE Conflict SET Slug = 'the-daily-mail' WHERE ID = 192
UPDATE Conflict SET Slug = 'the-eric-trump-foundation' WHERE ID = 3330
UPDATE Conflict SET Slug = 'the-new-york-observer' WHERE ID = 3250
UPDATE Conflict SET Slug = 'the-obsidian-fund' WHERE ID = 1253
UPDATE Conflict SET Slug = 'the-patriot-legal-defense-fund-trust-llc' WHERE ID = 474
UPDATE Conflict SET Slug = 'the-trump-organization' WHERE ID = 9673
UPDATE Conflict SET Slug = 'the-way-to-the-top' WHERE ID = 193
UPDATE Conflict SET Slug = 'think-big-and-kick-ass' WHERE ID = 194
UPDATE Conflict SET Slug = 'think-like-a-billionaire' WHERE ID = 195
UPDATE Conflict SET Slug = 'think-like-a-champion' WHERE ID = 196
UPDATE Conflict SET Slug = 'this-asset-has-been-divested' WHERE ID = 3180
UPDATE Conflict SET Slug = 'thrive-capital-partners' WHERE ID = 959
UPDATE Conflict SET Slug = 'thrive-capital-partners-ii' WHERE ID = 1269
UPDATE Conflict SET Slug = 'thrive-capital-partners-iii' WHERE ID = 1270
UPDATE Conflict SET Slug = 'thrive-partners-ii-gp' WHERE ID = 1272
UPDATE Conflict SET Slug = 'thrive-partners-iii-gp' WHERE ID = 1273
UPDATE Conflict SET Slug = 'tiger-woods' WHERE ID = 9707
UPDATE Conflict SET Slug = 'tihc-reservations' WHERE ID = 197
UPDATE Conflict SET Slug = 'tihh-member' WHERE ID = 3430
UPDATE Conflict SET Slug = 'tihm-member' WHERE ID = 198
UPDATE Conflict SET Slug = 'tiht-chicago-member-acquisition' WHERE ID = 199
UPDATE Conflict SET Slug = 'tiht-commercial' WHERE ID = 200
UPDATE Conflict SET Slug = 'tiht-holding-company' WHERE ID = 201
UPDATE Conflict SET Slug = 'tiht-member' WHERE ID = 202
UPDATE Conflict SET Slug = 'time-to-get-tough' WHERE ID = 203
UPDATE Conflict SET Slug = 'times-square-associates' WHERE ID = 797
UPDATE Conflict SET Slug = 'tipperary-realty' WHERE ID = 204
UPDATE Conflict SET Slug = 'tmg' WHERE ID = 205
UPDATE Conflict SET Slug = 'tngc-charlotte' WHERE ID = 206
UPDATE Conflict SET Slug = 'tngc-dutchess-county-formerly-trump-marks-classic-cars' WHERE ID = 207
UPDATE Conflict SET Slug = 'tngc-jupiter' WHERE ID = 208
UPDATE Conflict SET Slug = 'tngc-pine-hill-trump-national-golf-club-philadelphia-formerly-crest-court' WHERE ID = 209
UPDATE Conflict SET Slug = 'toronto-development' WHERE ID = 210
UPDATE Conflict SET Slug = 'toronto-dominion-bank' WHERE ID = 422
UPDATE Conflict SET Slug = 'tp-cfd' WHERE ID = 211
UPDATE Conflict SET Slug = 'transcanada' WHERE ID = 420
UPDATE Conflict SET Slug = 'travel-enterprises-management-formerly-toys-at-trump' WHERE ID = 212
UPDATE Conflict SET Slug = 'treasury-department' WHERE ID = 438
UPDATE Conflict SET Slug = 'triborough' WHERE ID = 1301
UPDATE Conflict SET Slug = 'triborough-ny-bridge-tunnel-authority' WHERE ID = 3276
UPDATE Conflict SET Slug = 'trump-101-the-way-to-success' WHERE ID = 213
UPDATE Conflict SET Slug = 'trump-106' WHERE ID = 214
UPDATE Conflict SET Slug = 'trump-767-management' WHERE ID = 215
UPDATE Conflict SET Slug = 'trump-845' WHERE ID = 216
UPDATE Conflict SET Slug = 'trump-845-un' WHERE ID = 217
UPDATE Conflict SET Slug = 'trump-ac-casino-marks' WHERE ID = 218
UPDATE Conflict SET Slug = 'trump-acquisition' WHERE ID = 219
UPDATE Conflict SET Slug = 'trump-books' WHERE ID = 220
UPDATE Conflict SET Slug = 'trump-brazil' WHERE ID = 221
UPDATE Conflict SET Slug = 'trump-briarcliff-manor-development-formerly-briar-hall-development' WHERE ID = 222
UPDATE Conflict SET Slug = 'trump-canadian-services' WHERE ID = 223
UPDATE Conflict SET Slug = 'trump-canouan-estate' WHERE ID = 224
UPDATE Conflict SET Slug = 'trump-caribbean' WHERE ID = 225
UPDATE Conflict SET Slug = 'trump-carousel' WHERE ID = 226
UPDATE Conflict SET Slug = 'trump-central-park-west' WHERE ID = 227
UPDATE Conflict SET Slug = 'trump-chicago' WHERE ID = 3431
UPDATE Conflict SET Slug = 'trump-chicago-commercial' WHERE ID = 228
UPDATE Conflict SET Slug = 'trump-chicago-development' WHERE ID = 229
UPDATE Conflict SET Slug = 'trump-chicago-hotel-manager' WHERE ID = 230
UPDATE Conflict SET Slug = 'trump-chicago-residential' WHERE ID = 231
UPDATE Conflict SET Slug = 'trump-chicago-retail' WHERE ID = 232
UPDATE Conflict SET Slug = 'trump-classic-cars' WHERE ID = 233
UPDATE Conflict SET Slug = 'trump-commercial-chicago' WHERE ID = 234
UPDATE Conflict SET Slug = 'trump-corporation' WHERE ID = 235
UPDATE Conflict SET Slug = 'trump-cps' WHERE ID = 236
UPDATE Conflict SET Slug = 'trump-delmonico' WHERE ID = 3432
UPDATE Conflict SET Slug = 'trump-development-services' WHERE ID = 237
UPDATE Conflict SET Slug = 'trump-drinks-israel' WHERE ID = 238
UPDATE Conflict SET Slug = 'trump-drinks-israel-holdings' WHERE ID = 239
UPDATE Conflict SET Slug = 'trump-dubai' WHERE ID = 9708
UPDATE Conflict SET Slug = 'trump-education' WHERE ID = 240
UPDATE Conflict SET Slug = 'trump-empire-state' WHERE ID = 241
UPDATE Conflict SET Slug = 'trump-endeavor-12' WHERE ID = 242
UPDATE Conflict SET Slug = 'trump-entrepreneur-initiative-formerly-trump-university-ca' WHERE ID = 243
UPDATE Conflict SET Slug = 'trump-equitable-fifth-avenue-company' WHERE ID = 244
UPDATE Conflict SET Slug = 'trump-eu-marks' WHERE ID = 245
UPDATE Conflict SET Slug = 'trump-ferry-point' WHERE ID = 246
UPDATE Conflict SET Slug = 'trump-florida' WHERE ID = 247
UPDATE Conflict SET Slug = 'trump-follies' WHERE ID = 248
UPDATE Conflict SET Slug = 'trump-golf-acquisitions' WHERE ID = 249
UPDATE Conflict SET Slug = 'trump-golf-coco-beach' WHERE ID = 250
UPDATE Conflict SET Slug = 'trump-golf-management' WHERE ID = 251
UPDATE Conflict SET Slug = 'trump-hollywood' WHERE ID = 9670
UPDATE Conflict SET Slug = 'trump-home-marks' WHERE ID = 252
UPDATE Conflict SET Slug = 'trump-hotel' WHERE ID = 253
UPDATE Conflict SET Slug = 'trump-hotel-rio-de-janeiro' WHERE ID = 254
UPDATE Conflict SET Slug = 'trump-ice' WHERE ID = 3433
UPDATE Conflict SET Slug = 'trump-identity' WHERE ID = 3434
UPDATE Conflict SET Slug = 'trump-international-development' WHERE ID = 255
UPDATE Conflict SET Slug = 'trump-international-golf-club' WHERE ID = 256
UPDATE Conflict SET Slug = 'trump-international-golf-club-florida' WHERE ID = 257
UPDATE Conflict SET Slug = 'trump-international-golf-club-scotland' WHERE ID = 258
UPDATE Conflict SET Slug = 'trump-international-golf-links-doonbeg' WHERE ID = 259
UPDATE Conflict SET Slug = 'trump-international-golf-links-scotland' WHERE ID = 260
UPDATE Conflict SET Slug = 'trump-international-hotel-and-tower-panama' WHERE ID = 261
UPDATE Conflict SET Slug = 'trump-international-hotel-and-tower-condominium' WHERE ID = 3350
UPDATE Conflict SET Slug = 'trump-international-hotel-dc' WHERE ID = 397
UPDATE Conflict SET Slug = 'trump-international-hotel-hawaii' WHERE ID = 262
UPDATE Conflict SET Slug = 'trump-international-hotels-management-dba-trump-hotel-collection' WHERE ID = 263
UPDATE Conflict SET Slug = 'trump-international-management' WHERE ID = 264
UPDATE Conflict SET Slug = 'trump-ireland-doonbeg' WHERE ID = 9724
UPDATE Conflict SET Slug = 'trump-jeddah' WHERE ID = 9722
UPDATE Conflict SET Slug = 'trump-jets-formerly-sentient-jets' WHERE ID = 265
UPDATE Conflict SET Slug = 'trump-kelowna' WHERE ID = 3435
UPDATE Conflict SET Slug = 'trump-korea' WHERE ID = 266
UPDATE Conflict SET Slug = 'trump-las-vegas' WHERE ID = 267
UPDATE Conflict SET Slug = 'trump-las-vegas-development' WHERE ID = 268
UPDATE Conflict SET Slug = 'trump-las-vegas-sales-marketing' WHERE ID = 269
UPDATE Conflict SET Slug = 'trump-las-vegas-sales-amp-marketing' WHERE ID = 388
UPDATE Conflict SET Slug = 'trump-lauderdale' WHERE ID = 3436
UPDATE Conflict SET Slug = 'trump-lntematlonal-hotel-and-tower-condominium' WHERE ID = 270
UPDATE Conflict SET Slug = 'trump-los-olas' WHERE ID = 271
UPDATE Conflict SET Slug = 'trump-management' WHERE ID = 272
UPDATE Conflict SET Slug = 'trump-marketing' WHERE ID = 273
UPDATE Conflict SET Slug = 'trump-marks' WHERE ID = 274
UPDATE Conflict SET Slug = 'trump-marks-asia' WHERE ID = 275
UPDATE Conflict SET Slug = 'trump-marks-atlanta' WHERE ID = 276
UPDATE Conflict SET Slug = 'trump-marks-baja' WHERE ID = 277
UPDATE Conflict SET Slug = 'trump-marks-batumi' WHERE ID = 278
UPDATE Conflict SET Slug = 'trump-marks-beverages' WHERE ID = 279
UPDATE Conflict SET Slug = 'trump-marks-canouan' WHERE ID = 280
UPDATE Conflict SET Slug = 'trump-marks-chicago' WHERE ID = 281
UPDATE Conflict SET Slug = 'trump-marks-dubai' WHERE ID = 282
UPDATE Conflict SET Slug = 'trump-marks-egypt' WHERE ID = 283
UPDATE Conflict SET Slug = 'trump-marks-fine-foods' WHERE ID = 284
UPDATE Conflict SET Slug = 'trump-marks-ft-lauderdale' WHERE ID = 285
UPDATE Conflict SET Slug = 'trump-marks-golf-swing' WHERE ID = 3437
UPDATE Conflict SET Slug = 'trump-marks-hollywood' WHERE ID = 286
UPDATE Conflict SET Slug = 'trump-marks-istanbul-ii' WHERE ID = 287
UPDATE Conflict SET Slug = 'trump-marks-jersey-city' WHERE ID = 288
UPDATE Conflict SET Slug = 'trump-marks-las-vegas' WHERE ID = 289
UPDATE Conflict SET Slug = 'trump-marks-magazine' WHERE ID = 290
UPDATE Conflict SET Slug = 'trump-marks-mattress' WHERE ID = 291
UPDATE Conflict SET Slug = 'trump-marks-menswear' WHERE ID = 292
UPDATE Conflict SET Slug = 'trump-marks-mortgage' WHERE ID = 293
UPDATE Conflict SET Slug = 'trump-marks-mumbai' WHERE ID = 294
UPDATE Conflict SET Slug = 'trump-marks-new-orleans' WHERE ID = 3438
UPDATE Conflict SET Slug = 'trump-marks-new-rochelle' WHERE ID = 295
UPDATE Conflict SET Slug = 'trump-marks-palm-beach' WHERE ID = 296
UPDATE Conflict SET Slug = 'trump-marks-panama' WHERE ID = 297
UPDATE Conflict SET Slug = 'trump-marks-philadelphia' WHERE ID = 298
UPDATE Conflict SET Slug = 'trump-marks-philippines' WHERE ID = 299
UPDATE Conflict SET Slug = 'trump-marks-products' WHERE ID = 300
UPDATE Conflict SET Slug = 'trump-marks-puerto-rico-i' WHERE ID = 301
UPDATE Conflict SET Slug = 'trump-marks-puerto-rico-ii' WHERE ID = 302
UPDATE Conflict SET Slug = 'trump-marks-punta-del-este' WHERE ID = 303
UPDATE Conflict SET Slug = 'trump-marks-real-estate' WHERE ID = 304
UPDATE Conflict SET Slug = 'trump-marks-soho' WHERE ID = 305
UPDATE Conflict SET Slug = 'trump-marks-south-africa' WHERE ID = 3439
UPDATE Conflict SET Slug = 'trump-marks-stamford' WHERE ID = 306
UPDATE Conflict SET Slug = 'trump-marks-sunny-isles-i' WHERE ID = 307
UPDATE Conflict SET Slug = 'trump-marks-sunny-isles-ii' WHERE ID = 308
UPDATE Conflict SET Slug = 'trump-marks-tampa' WHERE ID = 309
UPDATE Conflict SET Slug = 'trump-marks-toronto' WHERE ID = 310
UPDATE Conflict SET Slug = 'trump-marks-waikiki' WHERE ID = 311
UPDATE Conflict SET Slug = 'trump-marks-westchester' WHERE ID = 312
UPDATE Conflict SET Slug = 'trump-marks-white-plains' WHERE ID = 313
UPDATE Conflict SET Slug = 'trump-miami-resort' WHERE ID = 314
UPDATE Conflict SET Slug = 'trump-model-management' WHERE ID = 315
UPDATE Conflict SET Slug = 'trump-mortgage' WHERE ID = 316
UPDATE Conflict SET Slug = 'trump-national-doral' WHERE ID = 9669
UPDATE Conflict SET Slug = 'trump-national-golf-club-charlotte' WHERE ID = 317
UPDATE Conflict SET Slug = 'trump-national-golf-club-colts-neck' WHERE ID = 318
UPDATE Conflict SET Slug = 'trump-national-golf-club-hudson-valley' WHERE ID = 319
UPDATE Conflict SET Slug = 'trump-national-golf-club-los-angeles' WHERE ID = 320
UPDATE Conflict SET Slug = 'trump-national-golf-club-washington-dc' WHERE ID = 321
UPDATE Conflict SET Slug = 'trump-national-golf-club-westchester' WHERE ID = 322
UPDATE Conflict SET Slug = 'trump-national-golf-club-member' WHERE ID = 323
UPDATE Conflict SET Slug = 'trump-new-world-property' WHERE ID = 9671
UPDATE Conflict SET Slug = 'trump-new-world-property-management' WHERE ID = 3440
UPDATE Conflict SET Slug = 'trump-ocean' WHERE ID = 324
UPDATE Conflict SET Slug = 'trump-old-post-office' WHERE ID = 325
UPDATE Conflict SET Slug = 'trump-on-the-ocean-llc' WHERE ID = 326
UPDATE Conflict SET Slug = 'trump-organization-inc' WHERE ID = 327
UPDATE Conflict SET Slug = 'trump-organization-llc-dba-the-trump-organization' WHERE ID = 328
UPDATE Conflict SET Slug = 'trump-pageants' WHERE ID = 329
UPDATE Conflict SET Slug = 'trump-palace-condominium' WHERE ID = 3441
UPDATE Conflict SET Slug = 'trump-palaceparc' WHERE ID = 330
UPDATE Conflict SET Slug = 'trump-panama' WHERE ID = 9703
UPDATE Conflict SET Slug = 'trump-panama-condominium' WHERE ID = 331
UPDATE Conflict SET Slug = 'trump-panama-hotel-management' WHERE ID = 332
UPDATE Conflict SET Slug = 'trump-parc-east-condominium' WHERE ID = 333
UPDATE Conflict SET Slug = 'trump-park-avenue' WHERE ID = 334
UPDATE Conflict SET Slug = 'trump-payroll' WHERE ID = 335
UPDATE Conflict SET Slug = 'trump-payroll-chicago' WHERE ID = 336
UPDATE Conflict SET Slug = 'trump-phoenix-development' WHERE ID = 337
UPDATE Conflict SET Slug = 'trump-plaza' WHERE ID = 338
UPDATE Conflict SET Slug = 'trump-productions-formerly-rancho-lien' WHERE ID = 339
UPDATE Conflict SET Slug = 'trump-project-management' WHERE ID = 340
UPDATE Conflict SET Slug = 'trump-properties' WHERE ID = 341
UPDATE Conflict SET Slug = 'trump-realty-services-formerly-trump-mortgage-services-or-tower-mortgage-services' WHERE ID = 342
UPDATE Conflict SET Slug = 'trump-restaurants' WHERE ID = 343
UPDATE Conflict SET Slug = 'trump-riverside-management' WHERE ID = 344
UPDATE Conflict SET Slug = 'trump-ruffin' WHERE ID = 345
UPDATE Conflict SET Slug = 'trump-sales-leasing-chicago' WHERE ID = 346
UPDATE Conflict SET Slug = 'trump-sales-amp-leasing-chicago' WHERE ID = 389
UPDATE Conflict SET Slug = 'trump-scotland' WHERE ID = 347
UPDATE Conflict SET Slug = 'trump-scotland-aberdeen-and-turnberry' WHERE ID = 9711
UPDATE Conflict SET Slug = 'trump-scotsborough-square' WHERE ID = 348
UPDATE Conflict SET Slug = 'trump-soho' WHERE ID = 349
UPDATE Conflict SET Slug = 'trump-sunny-isles' WHERE ID = 9704
UPDATE Conflict SET Slug = 'trump-toronto-development' WHERE ID = 350
UPDATE Conflict SET Slug = 'trump-toronto-hotel' WHERE ID = 351
UPDATE Conflict SET Slug = 'trump-toronto-member-formerly-trump-toronto-management' WHERE ID = 352
UPDATE Conflict SET Slug = 'trump-tower-commercial' WHERE ID = 353
UPDATE Conflict SET Slug = 'trump-tower-condominium' WHERE ID = 3351
UPDATE Conflict SET Slug = 'trump-tower-condominium-residential-section' WHERE ID = 354
UPDATE Conflict SET Slug = 'trump-tower-i' WHERE ID = 466
UPDATE Conflict SET Slug = 'trump-tower-managing-member' WHERE ID = 355
UPDATE Conflict SET Slug = 'trump-tower-triplex' WHERE ID = 356
UPDATE Conflict SET Slug = 'trump-towers-istanbul' WHERE ID = 357
UPDATE Conflict SET Slug = 'trump-turnberry' WHERE ID = 358
UPDATE Conflict SET Slug = 'trump-victory' WHERE ID = 9687
UPDATE Conflict SET Slug = 'trump-village-construction' WHERE ID = 359
UPDATE Conflict SET Slug = 'trump-vineyard-estates-formerly-eric-trump-land-holdings' WHERE ID = 360
UPDATE Conflict SET Slug = 'trump-virginia-acquisitions-formerly-virginia-acquisitions' WHERE ID = 361
UPDATE Conflict SET Slug = 'trump-virginia-lot-5' WHERE ID = 362
UPDATE Conflict SET Slug = 'trump-wine-marks' WHERE ID = 363
UPDATE Conflict SET Slug = 'trump-world-golf-club-dubai' WHERE ID = 468
UPDATE Conflict SET Slug = 'trump-world-productions' WHERE ID = 364
UPDATE Conflict SET Slug = 'trump-world-publications' WHERE ID = 365
UPDATE Conflict SET Slug = 'trump39s-castle-management' WHERE ID = 390
UPDATE Conflict SET Slug = 'trumps-castle-management' WHERE ID = 5341
UPDATE Conflict SET Slug = 'trumps-castle-management' WHERE ID = 367
UPDATE Conflict SET Slug = 'trump-surviving-at-the-top' WHERE ID = 366
UPDATE Conflict SET Slug = 'truth-about-israel' WHERE ID = 437
UPDATE Conflict SET Slug = 'ttt-consulting' WHERE ID = 3312
UPDATE Conflict SET Slug = 'tttt-venture-formerly-thc-venture-iii' WHERE ID = 3313
UPDATE Conflict SET Slug = 'tw-venture-i' WHERE ID = 368
UPDATE Conflict SET Slug = 'tw-venture-ii' WHERE ID = 369
UPDATE Conflict SET Slug = 'us-department-of-justice' WHERE ID = 392
UPDATE Conflict SET Slug = 'us-department-of-agriculture' WHERE ID = 3299
UPDATE Conflict SET Slug = 'us-department-of-defense' WHERE ID = 3182
UPDATE Conflict SET Slug = 'us-department-of-veterans-affairs' WHERE ID = 9664
UPDATE Conflict SET Slug = 'us-money-market' WHERE ID = 3233
UPDATE Conflict SET Slug = 'us-treasury-department' WHERE ID = 3256
UPDATE Conflict SET Slug = 'ubs' WHERE ID = 3289
UPDATE Conflict SET Slug = 'ultimate-air' WHERE ID = 370
UPDATE Conflict SET Slug = 'unit-2502-enterprises' WHERE ID = 371
UPDATE Conflict SET Slug = 'united-way' WHERE ID = 434
UPDATE Conflict SET Slug = 'univ-of-texas' WHERE ID = 1544
UPDATE Conflict SET Slug = 'universal-city-studios' WHERE ID = 3314
UPDATE Conflict SET Slug = 'university-of-texas' WHERE ID = 3231
UPDATE Conflict SET Slug = 'unknown' WHERE ID = 1
UPDATE Conflict SET Slug = 'utah-st-rfdg-ser-c' WHERE ID = 3254
UPDATE Conflict SET Slug = 'utah-st-ser-a' WHERE ID = 1546
UPDATE Conflict SET Slug = 'utah-st-ser-c' WHERE ID = 1545
UPDATE Conflict SET Slug = 'valley-national-bank' WHERE ID = 3235
UPDATE Conflict SET Slug = 'vanguard' WHERE ID = 3189
UPDATE Conflict SET Slug = 'vegas-seven' WHERE ID = 472
UPDATE Conflict SET Slug = 'veggie-grill' WHERE ID = 473
UPDATE Conflict SET Slug = 'victor-pinchuk' WHERE ID = 460
UPDATE Conflict SET Slug = 'village-kf-2-km' WHERE ID = 1560
UPDATE Conflict SET Slug = 'village-kf-4-9-10-associates' WHERE ID = 3349
UPDATE Conflict SET Slug = 'village-kf-4-9-10-associates-llc' WHERE ID = 1820
UPDATE Conflict SET Slug = 'village-kf-4-9-10-associates-lp' WHERE ID = 2899
UPDATE Conflict SET Slug = 'virginia-beach-va-bonds' WHERE ID = 1568
UPDATE Conflict SET Slug = 'virginia-beach-va' WHERE ID = 3242
UPDATE Conflict SET Slug = 'virginia-st-bonds' WHERE ID = 1569
UPDATE Conflict SET Slug = 'visa' WHERE ID = 3285
UPDATE Conflict SET Slug = 'vreeland-avenue-associates' WHERE ID = 1268
UPDATE Conflict SET Slug = 'wake-cnty-nc-bonds' WHERE ID = 3249
UPDATE Conflict SET Slug = 'wake-cnty-nc-rfdg' WHERE ID = 3268
UPDATE Conflict SET Slug = 'wake-county-nc' WHERE ID = 2910
UPDATE Conflict SET Slug = 'wake-countync' WHERE ID = 3297
UPDATE Conflict SET Slug = 'wallkill' WHERE ID = 3158
UPDATE Conflict SET Slug = 'wallkill-apartments-associates' WHERE ID = 1576
UPDATE Conflict SET Slug = 'walmart' WHERE ID = 408
UPDATE Conflict SET Slug = 'warren-at-bay' WHERE ID = 1584
UPDATE Conflict SET Slug = 'warren-at-bay-associates' WHERE ID = 3236
UPDATE Conflict SET Slug = 'wb-studio-enterprises' WHERE ID = 9632
UPDATE Conflict SET Slug = 'wells-fargo' WHERE ID = 401
UPDATE Conflict SET Slug = 'west-end-building-associates' WHERE ID = 1620
UPDATE Conflict SET Slug = 'west-palm-operations' WHERE ID = 372
UPDATE Conflict SET Slug = 'westchester-county-ny' WHERE ID = 2928
UPDATE Conflict SET Slug = 'westmin-mad-associates' WHERE ID = 1619
UPDATE Conflict SET Slug = 'westminister-management' WHERE ID = 479
UPDATE Conflict SET Slug = 'westminster-hotel-management' WHERE ID = 9633
UPDATE Conflict SET Slug = 'westminster-linden' WHERE ID = 1621
UPDATE Conflict SET Slug = 'westminster-title' WHERE ID = 1593
UPDATE Conflict SET Slug = 'westminster-title-associates' WHERE ID = 3162
UPDATE Conflict SET Slug = 'wexford-hall' WHERE ID = 373
UPDATE Conflict SET Slug = 'white-course' WHERE ID = 374
UPDATE Conflict SET Slug = 'white-plains-ny' WHERE ID = 1606
UPDATE Conflict SET Slug = 'white-plains-ny' WHERE ID = 3291
UPDATE Conflict SET Slug = 'why-we-want-you-to-be-rich' WHERE ID = 375
UPDATE Conflict SET Slug = 'william-j-clinton-foundation' WHERE ID = 429
UPDATE Conflict SET Slug = 'william-trump-medical-fund-llc' WHERE ID = 376
UPDATE Conflict SET Slug = 'wilshire-hall' WHERE ID = 377
UPDATE Conflict SET Slug = 'wmtmf' WHERE ID = 378
UPDATE Conflict SET Slug = 'wollman-rink-operations' WHERE ID = 379
UPDATE Conflict SET Slug = 'women-who-work' WHERE ID = 3388
UPDATE Conflict SET Slug = 'wt-25-columbia' WHERE ID = 500
UPDATE Conflict SET Slug = 'yorktown-real-estate-formerly-yorktown-development-associates' WHERE ID = 380
UPDATE Conflict SET Slug = 'yum-brands' WHERE ID = 1618
