USE Trump
GO
UPDATE Conflict SET Slug = '' WHERE ID = 391
UPDATE Conflict SET Slug = '' WHERE ID = 381
UPDATE Conflict SET Slug = '1290-avenue-of-the-americas-a-tenancy-in-common' WHERE ID = 2
UPDATE Conflict SET Slug = '175-pearl-street' WHERE ID = 462
UPDATE Conflict SET Slug = '3126-corporation' WHERE ID = 3
UPDATE Conflict SET Slug = '4-shadow-tree-lane' WHERE ID = 4
UPDATE Conflict SET Slug = '40-wall-street' WHERE ID = 5
UPDATE Conflict SET Slug = '4t-holdings-one' WHERE ID = 6
UPDATE Conflict SET Slug = '4t-holdings-two' WHERE ID = 7
UPDATE Conflict SET Slug = '666-fifth-ave' WHERE ID = 443
UPDATE Conflict SET Slug = '767-manager-llc' WHERE ID = 8
UPDATE Conflict SET Slug = '809-north-canon' WHERE ID = 9
UPDATE Conflict SET Slug = '81-pine-note-holder' WHERE ID = 10
UPDATE Conflict SET Slug = '845-un' WHERE ID = 11
UPDATE Conflict SET Slug = 'ace-entertainment-formerly-trump-casinos-or-trump-taj-mahal' WHERE ID = 12
UPDATE Conflict SET Slug = 'all-county-building-supply-maintenance' WHERE ID = 13
UPDATE Conflict SET Slug = 'all-county-building-supply-amp-maintenance' WHERE ID = 382
UPDATE Conflict SET Slug = 'american-idea' WHERE ID = 482
UPDATE Conflict SET Slug = 'annie-veltri' WHERE ID = 14
UPDATE Conflict SET Slug = 'apollo-management' WHERE ID = 450
UPDATE Conflict SET Slug = 'apple' WHERE ID = 407
UPDATE Conflict SET Slug = 'att' WHERE ID = 454
UPDATE Conflict SET Slug = 'aviation-payroll-company' WHERE ID = 15
UPDATE Conflict SET Slug = 'b-plaza-realty' WHERE ID = 16
UPDATE Conflict SET Slug = 'bahrain' WHERE ID = 426
UPDATE Conflict SET Slug = 'bank-of-china' WHERE ID = 425
UPDATE Conflict SET Slug = 'bank-of-nova-scotia' WHERE ID = 421
UPDATE Conflict SET Slug = 'bedford-hills' WHERE ID = 17
UPDATE Conflict SET Slug = 'berkshire-hathaway' WHERE ID = 406
UPDATE Conflict SET Slug = 'briar-hall-operations' WHERE ID = 18
UPDATE Conflict SET Slug = 'brookfield-asset-management' WHERE ID = 448
UPDATE Conflict SET Slug = 'c-development-ventures' WHERE ID = 19
UPDATE Conflict SET Slug = 'cadre' WHERE ID = 445
UPDATE Conflict SET Slug = 'cap-cana' WHERE ID = 467
UPDATE Conflict SET Slug = 'caribusiness-mre' WHERE ID = 20
UPDATE Conflict SET Slug = 'caribusiness-re' WHERE ID = 21
UPDATE Conflict SET Slug = 'carl-c-icahn' WHERE ID = 428
UPDATE Conflict SET Slug = 'celgene' WHERE ID = 410
UPDATE Conflict SET Slug = 'chelsea-hall' WHERE ID = 22
UPDATE Conflict SET Slug = 'chevron' WHERE ID = 416
UPDATE Conflict SET Slug = 'chicago-unit-acquisition' WHERE ID = 23
UPDATE Conflict SET Slug = 'china-state-construction-engineering-corp' WHERE ID = 477
UPDATE Conflict SET Slug = 'china-trademark' WHERE ID = 24
UPDATE Conflict SET Slug = 'citibank' WHERE ID = 451
UPDATE Conflict SET Slug = 'clyde-hall' WHERE ID = 25
UPDATE Conflict SET Slug = 'commerce-department' WHERE ID = 440
UPDATE Conflict SET Slug = 'coronet-hall' WHERE ID = 26
UPDATE Conflict SET Slug = 'country-apartments' WHERE ID = 27
UPDATE Conflict SET Slug = 'country-investors' WHERE ID = 28
UPDATE Conflict SET Slug = 'country-of-vietnam' WHERE ID = 458
UPDATE Conflict SET Slug = 'country-properties' WHERE ID = 29
UPDATE Conflict SET Slug = 'cpw-pt-partners' WHERE ID = 30
UPDATE Conflict SET Slug = 'crippled-america' WHERE ID = 31
UPDATE Conflict SET Slug = 'd-b-pace-acquisition' WHERE ID = 32
UPDATE Conflict SET Slug = 'daewoo-america' WHERE ID = 33
UPDATE Conflict SET Slug = 'damac-properties' WHERE ID = 476
UPDATE Conflict SET Slug = 'dana-farber-cancer-institute' WHERE ID = 430
UPDATE Conflict SET Slug = 'department-of-defense' WHERE ID = 483
UPDATE Conflict SET Slug = 'department-of-homeland-security' WHERE ID = 484
UPDATE Conflict SET Slug = 'deutsche-bank' WHERE ID = 424
UPDATE Conflict SET Slug = 'dj-aerospace-bermuda' WHERE ID = 34
UPDATE Conflict SET Slug = 'djt-aerospace' WHERE ID = 35
UPDATE Conflict SET Slug = 'djt-holdings' WHERE ID = 36
UPDATE Conflict SET Slug = 'djt-land-holdings' WHERE ID = 37
UPDATE Conflict SET Slug = 'djt-operations-cx' WHERE ID = 38
UPDATE Conflict SET Slug = 'djt-operations-i' WHERE ID = 39
UPDATE Conflict SET Slug = 'djt-operations-ii' WHERE ID = 40
UPDATE Conflict SET Slug = 'dogan-holding' WHERE ID = 398
UPDATE Conflict SET Slug = 'donald-j-trump-enterprises' WHERE ID = 41
UPDATE Conflict SET Slug = 'donald-j-trump-enterprises-ii' WHERE ID = 42
UPDATE Conflict SET Slug = 'donald-j-trump-enterprises-iii' WHERE ID = 43
UPDATE Conflict SET Slug = 'donald-j-trump-company' WHERE ID = 44
UPDATE Conflict SET Slug = 'donald-j-trump-foundation' WHERE ID = 45
UPDATE Conflict SET Slug = 'donald-j-trump-grantor-trust' WHERE ID = 46
UPDATE Conflict SET Slug = 'donald-j-trump-revocable-trust' WHERE ID = 47
UPDATE Conflict SET Slug = 'dsn-licensing-formerly-trump-marks-network' WHERE ID = 48
UPDATE Conflict SET Slug = 'dt-app-warrant-holding' WHERE ID = 49
UPDATE Conflict SET Slug = 'dt-bali-golf-manager' WHERE ID = 50
UPDATE Conflict SET Slug = 'dt-bali-hotel-manager' WHERE ID = 51
UPDATE Conflict SET Slug = 'dt-bali-technical-services-manager' WHERE ID = 52
UPDATE Conflict SET Slug = 'dt-connect' WHERE ID = 53
UPDATE Conflict SET Slug = 'dt-connect-europe' WHERE ID = 54
UPDATE Conflict SET Slug = 'dt-connect-ii' WHERE ID = 55
UPDATE Conflict SET Slug = 'dt-dubai-golf-manager' WHERE ID = 56
UPDATE Conflict SET Slug = 'dt-dubai-ii-golf-manager' WHERE ID = 57
UPDATE Conflict SET Slug = 'dt-home-marks-international' WHERE ID = 58
UPDATE Conflict SET Slug = 'dt-india-venture' WHERE ID = 59
UPDATE Conflict SET Slug = 'dt-jeddah-technical-services-advisor' WHERE ID = 60
UPDATE Conflict SET Slug = 'dt-jeddah-technical-services-manager' WHERE ID = 61
UPDATE Conflict SET Slug = 'dt-lido-golf-manager' WHERE ID = 62
UPDATE Conflict SET Slug = 'dt-lido-hotel-manager' WHERE ID = 63
UPDATE Conflict SET Slug = 'dt-lido-technical-services-manager' WHERE ID = 64
UPDATE Conflict SET Slug = 'dt-marks-baku' WHERE ID = 65
UPDATE Conflict SET Slug = 'dt-marks-bali' WHERE ID = 66
UPDATE Conflict SET Slug = 'dt-marks-dubai' WHERE ID = 67
UPDATE Conflict SET Slug = 'dt-marks-dubai-ii' WHERE ID = 68
UPDATE Conflict SET Slug = 'dt-marks-gurgaon' WHERE ID = 69
UPDATE Conflict SET Slug = 'dt-marks-jersey-city' WHERE ID = 70
UPDATE Conflict SET Slug = 'dt-marks-jupiter' WHERE ID = 71
UPDATE Conflict SET Slug = 'dt-marks-lido' WHERE ID = 72
UPDATE Conflict SET Slug = 'dt-marks-products-international' WHERE ID = 73
UPDATE Conflict SET Slug = 'dt-marks-pune' WHERE ID = 74
UPDATE Conflict SET Slug = 'dt-marks-pune-ii' WHERE ID = 75
UPDATE Conflict SET Slug = 'dt-marks-qatar' WHERE ID = 76
UPDATE Conflict SET Slug = 'dt-marks-rio' WHERE ID = 77
UPDATE Conflict SET Slug = 'dt-marks-vancouver' WHERE ID = 78
UPDATE Conflict SET Slug = 'dt-marks-worli' WHERE ID = 79
UPDATE Conflict SET Slug = 'dt-tower-gurgaon' WHERE ID = 80
UPDATE Conflict SET Slug = 'dt-tower-i' WHERE ID = 81
UPDATE Conflict SET Slug = 'dt-tower-ii' WHERE ID = 82
UPDATE Conflict SET Slug = 'dt-tower-kolkata' WHERE ID = 83
UPDATE Conflict SET Slug = 'dttm-operations' WHERE ID = 84
UPDATE Conflict SET Slug = 'dtw-venture' WHERE ID = 85
UPDATE Conflict SET Slug = 'east-61-st-company' WHERE ID = 86
UPDATE Conflict SET Slug = 'eid-venture-i' WHERE ID = 87
UPDATE Conflict SET Slug = 'eid-venture-ii' WHERE ID = 88
UPDATE Conflict SET Slug = 'energy-transfer-partners' WHERE ID = 393
UPDATE Conflict SET Slug = 'essential-consultants' WHERE ID = 452
UPDATE Conflict SET Slug = 'excel-venture-i' WHERE ID = 89
UPDATE Conflict SET Slug = 'exxon-mobil' WHERE ID = 417
UPDATE Conflict SET Slug = 'federal-election-commission' WHERE ID = 465
UPDATE Conflict SET Slug = 'fifty-seven-management' WHERE ID = 90
UPDATE Conflict SET Slug = 'fifty-seventh-street-associates' WHERE ID = 91
UPDATE Conflict SET Slug = 'first-member' WHERE ID = 92
UPDATE Conflict SET Slug = 'flights-formerly-trump-flights' WHERE ID = 93
UPDATE Conflict SET Slug = 'florida-properties-management' WHERE ID = 94
UPDATE Conflict SET Slug = 'fontainbleu-apartments' WHERE ID = 95
UPDATE Conflict SET Slug = 'ford-motors' WHERE ID = 404
UPDATE Conflict SET Slug = 'galbreath-columbus-circle-development-associates' WHERE ID = 96
UPDATE Conflict SET Slug = 'general-services-administration' WHERE ID = 97
UPDATE Conflict SET Slug = 'gept-delmonico' WHERE ID = 98
UPDATE Conflict SET Slug = 'getty-images' WHERE ID = 480
UPDATE Conflict SET Slug = 'glaxosmithkline' WHERE ID = 412
UPDATE Conflict SET Slug = 'goldman-sachs' WHERE ID = 403
UPDATE Conflict SET Slug = 'golf-productions' WHERE ID = 99
UPDATE Conflict SET Slug = 'google' WHERE ID = 405
UPDATE Conflict SET Slug = 'hary-tanoesoedibjo' WHERE ID = 100
UPDATE Conflict SET Slug = 'helicopter-air-services' WHERE ID = 101
UPDATE Conflict SET Slug = 'highlander-hall' WHERE ID = 102
UPDATE Conflict SET Slug = 'holds-united-technologies' WHERE ID = 103
UPDATE Conflict SET Slug = 'hospital-for-special-surgery' WHERE ID = 433
UPDATE Conflict SET Slug = 'how-to-get-rich' WHERE ID = 104
UPDATE Conflict SET Slug = 'hudson-waterfront-associates' WHERE ID = 105
UPDATE Conflict SET Slug = 'hudson-waterfront-associates-i' WHERE ID = 106
UPDATE Conflict SET Slug = 'hudson-waterfront-associates-ii' WHERE ID = 107
UPDATE Conflict SET Slug = 'hudson-waterfront-associates-iii' WHERE ID = 108
UPDATE Conflict SET Slug = 'hudson-waterfront-associates-iv' WHERE ID = 109
UPDATE Conflict SET Slug = 'hudson-waterfront-associates-v' WHERE ID = 110
UPDATE Conflict SET Slug = 'hwa-1290-ill' WHERE ID = 111
UPDATE Conflict SET Slug = 'hwa-1290-iv' WHERE ID = 112
UPDATE Conflict SET Slug = 'hwa-1290-v' WHERE ID = 113
UPDATE Conflict SET Slug = 'hwa-555-owners' WHERE ID = 114
UPDATE Conflict SET Slug = 'hyde-park' WHERE ID = 115
UPDATE Conflict SET Slug = 'indian-hills-holdings-formerly-indian-hills-development' WHERE ID = 116
UPDATE Conflict SET Slug = 'internal-revenue-service' WHERE ID = 117
UPDATE Conflict SET Slug = 'ivanka-m-trump-charitable-fund' WHERE ID = 470
UPDATE Conflict SET Slug = 'ivanka-trump-brand' WHERE ID = 444
UPDATE Conflict SET Slug = 'ivanka-trump-business-trust' WHERE ID = 478
UPDATE Conflict SET Slug = 'johnson-johnson' WHERE ID = 414
UPDATE Conflict SET Slug = 'jose-e-b-antonio' WHERE ID = 399
UPDATE Conflict SET Slug = 'jp-morgan-chase' WHERE ID = 400
UPDATE Conflict SET Slug = 'jupiter-golf-club' WHERE ID = 118
UPDATE Conflict SET Slug = 'kinder-morgan' WHERE ID = 419
UPDATE Conflict SET Slug = 'korean-aerospace-industries' WHERE ID = 455
UPDATE Conflict SET Slug = 'kushner-companies' WHERE ID = 439
UPDATE Conflict SET Slug = 'ladder-capital' WHERE ID = 119
UPDATE Conflict SET Slug = 'lamington-family-holdings' WHERE ID = 120
UPDATE Conflict SET Slug = 'lamington-farm-club' WHERE ID = 121
UPDATE Conflict SET Slug = 'lawrence-towers-apartments' WHERE ID = 122
UPDATE Conflict SET Slug = 'le-chateau-des-palmiers' WHERE ID = 447
UPDATE Conflict SET Slug = 'lfb-acquisition' WHERE ID = 123
UPDATE Conflict SET Slug = 'lido-city-development' WHERE ID = 394
UPDATE Conflict SET Slug = 'mar-a-lago-club' WHERE ID = 124
UPDATE Conflict SET Slug = 'marc-kasowitz' WHERE ID = 457
UPDATE Conflict SET Slug = 'melania-llc' WHERE ID = 435
UPDATE Conflict SET Slug = 'merck' WHERE ID = 409
UPDATE Conflict SET Slug = 'merrill-lynch-credit-corporation-dba-merrill-lynch-home-loans' WHERE ID = 125
UPDATE Conflict SET Slug = 'metallurgical-corporation-of-china-mcc' WHERE ID = 442
UPDATE Conflict SET Slug = 'mgm' WHERE ID = 427
UPDATE Conflict SET Slug = 'michael-cohen' WHERE ID = 449
UPDATE Conflict SET Slug = 'midland-associates' WHERE ID = 126
UPDATE Conflict SET Slug = 'miss-universe-formerly-trump-pageants' WHERE ID = 127
UPDATE Conflict SET Slug = 'mnc-group' WHERE ID = 441
UPDATE Conflict SET Slug = 'mobile-payroll-construction' WHERE ID = 128
UPDATE Conflict SET Slug = 'morgan-stanley' WHERE ID = 402
UPDATE Conflict SET Slug = 'national-labor-relations-board' WHERE ID = 129
UPDATE Conflict SET Slug = 'nbc' WHERE ID = 130
UPDATE Conflict SET Slug = 'never-give-up' WHERE ID = 131
UPDATE Conflict SET Slug = 'new-sunshine-llc' WHERE ID = 132
UPDATE Conflict SET Slug = 'new-york-presbyterian-hospital' WHERE ID = 432
UPDATE Conflict SET Slug = 'nippon-telegraph-telephone-corp-ntt' WHERE ID = 461
UPDATE Conflict SET Slug = 'nitto-world' WHERE ID = 133
UPDATE Conflict SET Slug = 'normandy-real-estate-partners' WHERE ID = 463
UPDATE Conflict SET Slug = 'novartis' WHERE ID = 453
UPDATE Conflict SET Slug = 'ocean-development' WHERE ID = 134
UPDATE Conflict SET Slug = 'office-of-government-ethics' WHERE ID = 475
UPDATE Conflict SET Slug = 'one-central-park-west' WHERE ID = 135
UPDATE Conflict SET Slug = 'operation-smile' WHERE ID = 431
UPDATE Conflict SET Slug = 'opo-hotel-manager' WHERE ID = 136
UPDATE Conflict SET Slug = 'owo-developer' WHERE ID = 137
UPDATE Conflict SET Slug = 'panama-ocean-club-management' WHERE ID = 138
UPDATE Conflict SET Slug = 'paramount-rpv-holdings' WHERE ID = 139
UPDATE Conflict SET Slug = 'parc-consulting' WHERE ID = 140
UPDATE Conflict SET Slug = 'park-briar-associates' WHERE ID = 141
UPDATE Conflict SET Slug = 'penguin-random-house' WHERE ID = 471
UPDATE Conflict SET Slug = 'pfizer' WHERE ID = 411
UPDATE Conflict SET Slug = 'philippine-government' WHERE ID = 459
UPDATE Conflict SET Slug = 'phillips-66' WHERE ID = 418
UPDATE Conflict SET Slug = 'pier-village' WHERE ID = 464
UPDATE Conflict SET Slug = 'pine-hill-development' WHERE ID = 142
UPDATE Conflict SET Slug = 'plaza-consulting' WHERE ID = 143
UPDATE Conflict SET Slug = 'poker-venture' WHERE ID = 144
UPDATE Conflict SET Slug = 'police-athletic-league' WHERE ID = 145
UPDATE Conflict SET Slug = 'proctor-gamble' WHERE ID = 413
UPDATE Conflict SET Slug = 'qatar-government' WHERE ID = 456
UPDATE Conflict SET Slug = 'quail-ridge' WHERE ID = 469
UPDATE Conflict SET Slug = 'qvc' WHERE ID = 146
UPDATE Conflict SET Slug = 'reg-tru-equities' WHERE ID = 147
UPDATE Conflict SET Slug = 'related-companies' WHERE ID = 436
UPDATE Conflict SET Slug = 'restaurant-40' WHERE ID = 148
UPDATE Conflict SET Slug = 'royal-bank-america' WHERE ID = 149
UPDATE Conflict SET Slug = 'royal-bank-of-canada' WHERE ID = 423
UPDATE Conflict SET Slug = 'rpv-development' WHERE ID = 150
UPDATE Conflict SET Slug = 'saudi-arabia-and-emirati-real-estate-and-hotel-deals' WHERE ID = 396
UPDATE Conflict SET Slug = 'scion' WHERE ID = 481
UPDATE Conflict SET Slug = 'scotland-acquisitions' WHERE ID = 151
UPDATE Conflict SET Slug = 'seven-springs' WHERE ID = 152
UPDATE Conflict SET Slug = 'shell' WHERE ID = 415
UPDATE Conflict SET Slug = 'shore-haven-apt1' WHERE ID = 153
UPDATE Conflict SET Slug = 'shore-haven-management' WHERE ID = 154
UPDATE Conflict SET Slug = 'shore-haven-shopping-center' WHERE ID = 155
UPDATE Conflict SET Slug = 'signature-bank' WHERE ID = 395
UPDATE Conflict SET Slug = 'softbank-vision-fund' WHERE ID = 446
UPDATE Conflict SET Slug = 'spring-creek-plaza' WHERE ID = 156
UPDATE Conflict SET Slug = 'starrett-city-associates-lp' WHERE ID = 157
UPDATE Conflict SET Slug = 'stephanie-clifford-aka-stormy-daniels' WHERE ID = 385
UPDATE Conflict SET Slug = 'stephanie-clifford-akastormy-daniels' WHERE ID = 158
UPDATE Conflict SET Slug = 'storage-106' WHERE ID = 159
UPDATE Conflict SET Slug = 'sussex-hall' WHERE ID = 160
UPDATE Conflict SET Slug = 't-express' WHERE ID = 161
UPDATE Conflict SET Slug = 't-international-realty-aka-trump-international-realty' WHERE ID = 386
UPDATE Conflict SET Slug = 't-international-realty-akatrump-international-realty' WHERE ID = 162
UPDATE Conflict SET Slug = 'tag-air' WHERE ID = 163
UPDATE Conflict SET Slug = 'tc-marks-buenos-aires' WHERE ID = 164
UPDATE Conflict SET Slug = 'thc-baku-hotel-manager-services' WHERE ID = 165
UPDATE Conflict SET Slug = 'thc-baku-services' WHERE ID = 166
UPDATE Conflict SET Slug = 'thc-barra-hotelaria' WHERE ID = 167
UPDATE Conflict SET Slug = 'thc-central-reservations' WHERE ID = 168
UPDATE Conflict SET Slug = 'thc-china-development' WHERE ID = 169
UPDATE Conflict SET Slug = 'thc-china-technical-services' WHERE ID = 170
UPDATE Conflict SET Slug = 'thc-dc-restaurant-hospitality' WHERE ID = 171
UPDATE Conflict SET Slug = 'thc-development-brazil' WHERE ID = 172
UPDATE Conflict SET Slug = 'thc-dubai-ii-hotel-manager' WHERE ID = 173
UPDATE Conflict SET Slug = 'thc-hotel-development' WHERE ID = 174
UPDATE Conflict SET Slug = 'thc-imea-development' WHERE ID = 175
UPDATE Conflict SET Slug = 'thc-jeddah-hotel-advisor' WHERE ID = 176
UPDATE Conflict SET Slug = 'thc-jeddah-hotel-manager' WHERE ID = 177
UPDATE Conflict SET Slug = 'thc-miami-restaurant-hospitality' WHERE ID = 178
UPDATE Conflict SET Slug = 'thc-qatar-hotel-manager' WHERE ID = 179
UPDATE Conflict SET Slug = 'thc-rio' WHERE ID = 180
UPDATE Conflict SET Slug = 'thc-sales-marketing' WHERE ID = 181
UPDATE Conflict SET Slug = 'thc-sales-amp-marketing' WHERE ID = 387
UPDATE Conflict SET Slug = 'thc-services-shenzhen' WHERE ID = 182
UPDATE Conflict SET Slug = 'thc-shenzhen-hotel-manager' WHERE ID = 183
UPDATE Conflict SET Slug = 'thc-vancouver' WHERE ID = 184
UPDATE Conflict SET Slug = 'thc-venture-i' WHERE ID = 185
UPDATE Conflict SET Slug = 'thc-venture-ii' WHERE ID = 186
UPDATE Conflict SET Slug = 'thc-venture-iii-now-tttt-venture' WHERE ID = 187
UPDATE Conflict SET Slug = 'the-america-we-deserve' WHERE ID = 188
UPDATE Conflict SET Slug = 'the-art-of-the-comeback' WHERE ID = 189
UPDATE Conflict SET Slug = 'the-art-of-the-deal' WHERE ID = 190
UPDATE Conflict SET Slug = 'the-best-real-estate-advice-i-ever-received' WHERE ID = 191
UPDATE Conflict SET Slug = 'the-daily-mail' WHERE ID = 192
UPDATE Conflict SET Slug = 'the-patriot-legal-defense-fund-trust-llc' WHERE ID = 474
UPDATE Conflict SET Slug = 'the-way-to-the-top' WHERE ID = 193
UPDATE Conflict SET Slug = 'think-big-and-kick-ass' WHERE ID = 194
UPDATE Conflict SET Slug = 'think-like-a-billionaire' WHERE ID = 195
UPDATE Conflict SET Slug = 'think-like-a-champion' WHERE ID = 196
UPDATE Conflict SET Slug = 'tihc-reservations' WHERE ID = 197
UPDATE Conflict SET Slug = 'tihm-member' WHERE ID = 198
UPDATE Conflict SET Slug = 'tiht-chicago-member-acquisition' WHERE ID = 199
UPDATE Conflict SET Slug = 'tiht-commercial' WHERE ID = 200
UPDATE Conflict SET Slug = 'tiht-holding-company' WHERE ID = 201
UPDATE Conflict SET Slug = 'tiht-member' WHERE ID = 202
UPDATE Conflict SET Slug = 'time-to-get-tough' WHERE ID = 203
UPDATE Conflict SET Slug = 'tipperary-realty' WHERE ID = 204
UPDATE Conflict SET Slug = 'tmg' WHERE ID = 205
UPDATE Conflict SET Slug = 'tngc-charlotte' WHERE ID = 206
UPDATE Conflict SET Slug = 'tngc-dutchess-county-formerly-trump-marks-classic-cars' WHERE ID = 207
UPDATE Conflict SET Slug = 'tngc-jupiter' WHERE ID = 208
UPDATE Conflict SET Slug = 'tngc-pine-hill-trump-national-golf-club-philadelphia-formerly-crest-court' WHERE ID = 209
UPDATE Conflict SET Slug = 'toronto-development' WHERE ID = 210
UPDATE Conflict SET Slug = 'toronto-dominion-bank' WHERE ID = 422
UPDATE Conflict SET Slug = 'tp-cfd' WHERE ID = 211
UPDATE Conflict SET Slug = 'transcanada' WHERE ID = 420
UPDATE Conflict SET Slug = 'travel-enterprises-management-formerly-toys-at-trump' WHERE ID = 212
UPDATE Conflict SET Slug = 'treasury-department' WHERE ID = 438
UPDATE Conflict SET Slug = 'trump-101-the-way-to-success' WHERE ID = 213
UPDATE Conflict SET Slug = 'trump-106' WHERE ID = 214
UPDATE Conflict SET Slug = 'trump-767-management' WHERE ID = 215
UPDATE Conflict SET Slug = 'trump-845' WHERE ID = 216
UPDATE Conflict SET Slug = 'trump-845-un' WHERE ID = 217
UPDATE Conflict SET Slug = 'trump-ac-casino-marks' WHERE ID = 218
UPDATE Conflict SET Slug = 'trump-acquisition' WHERE ID = 219
UPDATE Conflict SET Slug = 'trump-books' WHERE ID = 220
UPDATE Conflict SET Slug = 'trump-brazil' WHERE ID = 221
UPDATE Conflict SET Slug = 'trump-briarcliff-manor-development-formerly-briar-hall-development' WHERE ID = 222
UPDATE Conflict SET Slug = 'trump-canadian-services' WHERE ID = 223
UPDATE Conflict SET Slug = 'trump-canouan-estate' WHERE ID = 224
UPDATE Conflict SET Slug = 'trump-caribbean' WHERE ID = 225
UPDATE Conflict SET Slug = 'trump-carousel' WHERE ID = 226
UPDATE Conflict SET Slug = 'trump-central-park-west' WHERE ID = 227
UPDATE Conflict SET Slug = 'trump-chicago-commercial' WHERE ID = 228
UPDATE Conflict SET Slug = 'trump-chicago-development' WHERE ID = 229
UPDATE Conflict SET Slug = 'trump-chicago-hotel-manager' WHERE ID = 230
UPDATE Conflict SET Slug = 'trump-chicago-residential' WHERE ID = 231
UPDATE Conflict SET Slug = 'trump-chicago-retail' WHERE ID = 232
UPDATE Conflict SET Slug = 'trump-classic-cars' WHERE ID = 233
UPDATE Conflict SET Slug = 'trump-commercial-chicago' WHERE ID = 234
UPDATE Conflict SET Slug = 'trump-corporation' WHERE ID = 235
UPDATE Conflict SET Slug = 'trump-cps' WHERE ID = 236
UPDATE Conflict SET Slug = 'trump-development-services' WHERE ID = 237
UPDATE Conflict SET Slug = 'trump-drinks-israel' WHERE ID = 238
UPDATE Conflict SET Slug = 'trump-drinks-israel-holdings' WHERE ID = 239
UPDATE Conflict SET Slug = 'trump-education' WHERE ID = 240
UPDATE Conflict SET Slug = 'trump-empire-state' WHERE ID = 241
UPDATE Conflict SET Slug = 'trump-endeavor-12' WHERE ID = 242
UPDATE Conflict SET Slug = 'trump-entrepreneur-initiative-formerly-trump-university-ca' WHERE ID = 243
UPDATE Conflict SET Slug = 'trump-equitable-fifth-avenue-company' WHERE ID = 244
UPDATE Conflict SET Slug = 'trump-eu-marks' WHERE ID = 245
UPDATE Conflict SET Slug = 'trump-ferry-point' WHERE ID = 246
UPDATE Conflict SET Slug = 'trump-florida' WHERE ID = 247
UPDATE Conflict SET Slug = 'trump-follies' WHERE ID = 248
UPDATE Conflict SET Slug = 'trump-golf-acquisitions' WHERE ID = 249
UPDATE Conflict SET Slug = 'trump-golf-coco-beach' WHERE ID = 250
UPDATE Conflict SET Slug = 'trump-golf-management' WHERE ID = 251
UPDATE Conflict SET Slug = 'trump-home-marks' WHERE ID = 252
UPDATE Conflict SET Slug = 'trump-hotel' WHERE ID = 253
UPDATE Conflict SET Slug = 'trump-hotel-rio-de-janeiro' WHERE ID = 254
UPDATE Conflict SET Slug = 'trump-international-development' WHERE ID = 255
UPDATE Conflict SET Slug = 'trump-international-golf-club' WHERE ID = 256
UPDATE Conflict SET Slug = 'trump-international-golf-club-florida' WHERE ID = 257
UPDATE Conflict SET Slug = 'trump-international-golf-club-scotland' WHERE ID = 258
UPDATE Conflict SET Slug = 'trump-international-golf-links-doonbeg' WHERE ID = 259
UPDATE Conflict SET Slug = 'trump-international-golf-links-scotland' WHERE ID = 260
UPDATE Conflict SET Slug = 'trump-international-hotel-and-tower-panama' WHERE ID = 261
UPDATE Conflict SET Slug = 'trump-international-hotel-dc' WHERE ID = 397
UPDATE Conflict SET Slug = 'trump-international-hotel-hawaii' WHERE ID = 262
UPDATE Conflict SET Slug = 'trump-international-hotels-management-dba-trump-hotel-collection' WHERE ID = 263
UPDATE Conflict SET Slug = 'trump-international-management' WHERE ID = 264
UPDATE Conflict SET Slug = 'trump-jets-formerly-sentient-jets' WHERE ID = 265
UPDATE Conflict SET Slug = 'trump-korea' WHERE ID = 266
UPDATE Conflict SET Slug = 'trump-las-vegas' WHERE ID = 267
UPDATE Conflict SET Slug = 'trump-las-vegas-development' WHERE ID = 268
UPDATE Conflict SET Slug = 'trump-las-vegas-sales-marketing' WHERE ID = 269
UPDATE Conflict SET Slug = 'trump-las-vegas-sales-amp-marketing' WHERE ID = 388
UPDATE Conflict SET Slug = 'trump-lntematlonal-hotel-and-tower-condominium' WHERE ID = 270
UPDATE Conflict SET Slug = 'trump-los-olas' WHERE ID = 271
UPDATE Conflict SET Slug = 'trump-management' WHERE ID = 272
UPDATE Conflict SET Slug = 'trump-marketing' WHERE ID = 273
UPDATE Conflict SET Slug = 'trump-marks' WHERE ID = 274
UPDATE Conflict SET Slug = 'trump-marks-asia' WHERE ID = 275
UPDATE Conflict SET Slug = 'trump-marks-atlanta' WHERE ID = 276
UPDATE Conflict SET Slug = 'trump-marks-baja' WHERE ID = 277
UPDATE Conflict SET Slug = 'trump-marks-batumi' WHERE ID = 278
UPDATE Conflict SET Slug = 'trump-marks-beverages' WHERE ID = 279
UPDATE Conflict SET Slug = 'trump-marks-canouan' WHERE ID = 280
UPDATE Conflict SET Slug = 'trump-marks-chicago' WHERE ID = 281
UPDATE Conflict SET Slug = 'trump-marks-dubai' WHERE ID = 282
UPDATE Conflict SET Slug = 'trump-marks-egypt' WHERE ID = 283
UPDATE Conflict SET Slug = 'trump-marks-fine-foods' WHERE ID = 284
UPDATE Conflict SET Slug = 'trump-marks-ft-lauderdale' WHERE ID = 285
UPDATE Conflict SET Slug = 'trump-marks-hollywood' WHERE ID = 286
UPDATE Conflict SET Slug = 'trump-marks-istanbul-ii' WHERE ID = 287
UPDATE Conflict SET Slug = 'trump-marks-jersey-city' WHERE ID = 288
UPDATE Conflict SET Slug = 'trump-marks-las-vegas' WHERE ID = 289
UPDATE Conflict SET Slug = 'trump-marks-magazine' WHERE ID = 290
UPDATE Conflict SET Slug = 'trump-marks-mattress' WHERE ID = 291
UPDATE Conflict SET Slug = 'trump-marks-menswear' WHERE ID = 292
UPDATE Conflict SET Slug = 'trump-marks-mortgage' WHERE ID = 293
UPDATE Conflict SET Slug = 'trump-marks-mumbai' WHERE ID = 294
UPDATE Conflict SET Slug = 'trump-marks-new-rochelle' WHERE ID = 295
UPDATE Conflict SET Slug = 'trump-marks-palm-beach' WHERE ID = 296
UPDATE Conflict SET Slug = 'trump-marks-panama' WHERE ID = 297
UPDATE Conflict SET Slug = 'trump-marks-philadelphia' WHERE ID = 298
UPDATE Conflict SET Slug = 'trump-marks-philippines' WHERE ID = 299
UPDATE Conflict SET Slug = 'trump-marks-products' WHERE ID = 300
UPDATE Conflict SET Slug = 'trump-marks-puerto-rico-i' WHERE ID = 301
UPDATE Conflict SET Slug = 'trump-marks-puerto-rico-ii' WHERE ID = 302
UPDATE Conflict SET Slug = 'trump-marks-punta-del-este' WHERE ID = 303
UPDATE Conflict SET Slug = 'trump-marks-real-estate' WHERE ID = 304
UPDATE Conflict SET Slug = 'trump-marks-soho' WHERE ID = 305
UPDATE Conflict SET Slug = 'trump-marks-stamford' WHERE ID = 306
UPDATE Conflict SET Slug = 'trump-marks-sunny-isles-i' WHERE ID = 307
UPDATE Conflict SET Slug = 'trump-marks-sunny-isles-ii' WHERE ID = 308
UPDATE Conflict SET Slug = 'trump-marks-tampa' WHERE ID = 309
UPDATE Conflict SET Slug = 'trump-marks-toronto' WHERE ID = 310
UPDATE Conflict SET Slug = 'trump-marks-waikiki' WHERE ID = 311
UPDATE Conflict SET Slug = 'trump-marks-westchester' WHERE ID = 312
UPDATE Conflict SET Slug = 'trump-marks-white-plains' WHERE ID = 313
UPDATE Conflict SET Slug = 'trump-miami-resort' WHERE ID = 314
UPDATE Conflict SET Slug = 'trump-model-management' WHERE ID = 315
UPDATE Conflict SET Slug = 'trump-mortgage' WHERE ID = 316
UPDATE Conflict SET Slug = 'trump-national-golf-club-charlotte' WHERE ID = 317
UPDATE Conflict SET Slug = 'trump-national-golf-club-colts-neck' WHERE ID = 318
UPDATE Conflict SET Slug = 'trump-national-golf-club-hudson-valley' WHERE ID = 319
UPDATE Conflict SET Slug = 'trump-national-golf-club-los-angeles' WHERE ID = 320
UPDATE Conflict SET Slug = 'trump-national-golf-club-washington-dc' WHERE ID = 321
UPDATE Conflict SET Slug = 'trump-national-golf-club-westchester' WHERE ID = 322
UPDATE Conflict SET Slug = 'trump-national-golf-club-member' WHERE ID = 323
UPDATE Conflict SET Slug = 'trump-ocean' WHERE ID = 324
UPDATE Conflict SET Slug = 'trump-old-post-office' WHERE ID = 325
UPDATE Conflict SET Slug = 'trump-on-the-ocean-llc' WHERE ID = 326
UPDATE Conflict SET Slug = 'trump-organization-inc' WHERE ID = 327
UPDATE Conflict SET Slug = 'trump-organization-llc-dba-the-trump-organization' WHERE ID = 328
UPDATE Conflict SET Slug = 'trump-pageants' WHERE ID = 329
UPDATE Conflict SET Slug = 'trump-palaceparc' WHERE ID = 330
UPDATE Conflict SET Slug = 'trump-panama-condominium' WHERE ID = 331
UPDATE Conflict SET Slug = 'trump-panama-hotel-management' WHERE ID = 332
UPDATE Conflict SET Slug = 'trump-parc-east-condominium' WHERE ID = 333
UPDATE Conflict SET Slug = 'trump-park-avenue' WHERE ID = 334
UPDATE Conflict SET Slug = 'trump-payroll' WHERE ID = 335
UPDATE Conflict SET Slug = 'trump-payroll-chicago' WHERE ID = 336
UPDATE Conflict SET Slug = 'trump-phoenix-development' WHERE ID = 337
UPDATE Conflict SET Slug = 'trump-plaza' WHERE ID = 338
UPDATE Conflict SET Slug = 'trump-productions-formerly-rancho-lien' WHERE ID = 339
UPDATE Conflict SET Slug = 'trump-project-management' WHERE ID = 340
UPDATE Conflict SET Slug = 'trump-properties' WHERE ID = 341
UPDATE Conflict SET Slug = 'trump-realty-services-formerly-trump-mortgage-services-or-tower-mortgage-services' WHERE ID = 342
UPDATE Conflict SET Slug = 'trump-restaurants' WHERE ID = 343
UPDATE Conflict SET Slug = 'trump-riverside-management' WHERE ID = 344
UPDATE Conflict SET Slug = 'trump-ruffin' WHERE ID = 345
UPDATE Conflict SET Slug = 'trump-sales-leasing-chicago' WHERE ID = 346
UPDATE Conflict SET Slug = 'trump-sales-amp-leasing-chicago' WHERE ID = 389
UPDATE Conflict SET Slug = 'trump-scotland' WHERE ID = 347
UPDATE Conflict SET Slug = 'trump-scotsborough-square' WHERE ID = 348
UPDATE Conflict SET Slug = 'trump-soho' WHERE ID = 349
UPDATE Conflict SET Slug = 'trump-toronto-development' WHERE ID = 350
UPDATE Conflict SET Slug = 'trump-toronto-hotel' WHERE ID = 351
UPDATE Conflict SET Slug = 'trump-toronto-member-formerly-trump-toronto-management' WHERE ID = 352
UPDATE Conflict SET Slug = 'trump-tower-commercial' WHERE ID = 353
UPDATE Conflict SET Slug = 'trump-tower-condominium-residential-section' WHERE ID = 354
UPDATE Conflict SET Slug = 'trump-tower-i' WHERE ID = 466
UPDATE Conflict SET Slug = 'trump-tower-managing-member' WHERE ID = 355
UPDATE Conflict SET Slug = 'trump-tower-triplex' WHERE ID = 356
UPDATE Conflict SET Slug = 'trump-towers-istanbul' WHERE ID = 357
UPDATE Conflict SET Slug = 'trump-turnberry' WHERE ID = 358
UPDATE Conflict SET Slug = 'trump-village-construction' WHERE ID = 359
UPDATE Conflict SET Slug = 'trump-vineyard-estates-formerly-eric-trump-land-holdings' WHERE ID = 360
UPDATE Conflict SET Slug = 'trump-virginia-acquisitions-formerly-virginia-acquisitions' WHERE ID = 361
UPDATE Conflict SET Slug = 'trump-virginia-lot-5' WHERE ID = 362
UPDATE Conflict SET Slug = 'trump-wine-marks' WHERE ID = 363
UPDATE Conflict SET Slug = 'trump-world-golf-club-dubai' WHERE ID = 468
UPDATE Conflict SET Slug = 'trump-world-productions' WHERE ID = 364
UPDATE Conflict SET Slug = 'trump-world-publications' WHERE ID = 365
UPDATE Conflict SET Slug = 'trump39s-castle-management' WHERE ID = 390
UPDATE Conflict SET Slug = 'trumps-castle-management' WHERE ID = 367
UPDATE Conflict SET Slug = 'trump-surviving-at-the-top' WHERE ID = 366
UPDATE Conflict SET Slug = 'truth-about-israel' WHERE ID = 437
UPDATE Conflict SET Slug = 'tw-venture-i' WHERE ID = 368
UPDATE Conflict SET Slug = 'tw-venture-ii' WHERE ID = 369
UPDATE Conflict SET Slug = 'us-department-of-justice' WHERE ID = 392
UPDATE Conflict SET Slug = 'ultimate-air' WHERE ID = 370
UPDATE Conflict SET Slug = 'unit-2502-enterprises' WHERE ID = 371
UPDATE Conflict SET Slug = 'united-way' WHERE ID = 434
UPDATE Conflict SET Slug = 'unknown' WHERE ID = 1
UPDATE Conflict SET Slug = 'vegas-seven' WHERE ID = 472
UPDATE Conflict SET Slug = 'veggie-grill' WHERE ID = 473
UPDATE Conflict SET Slug = 'victor-pinchuk' WHERE ID = 460
UPDATE Conflict SET Slug = 'walmart' WHERE ID = 408
UPDATE Conflict SET Slug = 'wells-fargo' WHERE ID = 401
UPDATE Conflict SET Slug = 'west-palm-operations' WHERE ID = 372
UPDATE Conflict SET Slug = 'westminister-management' WHERE ID = 479
UPDATE Conflict SET Slug = 'wexford-hall' WHERE ID = 373
UPDATE Conflict SET Slug = 'white-course' WHERE ID = 374
UPDATE Conflict SET Slug = 'why-we-want-you-to-be-rich' WHERE ID = 375
UPDATE Conflict SET Slug = 'william-j-clinton-foundation' WHERE ID = 429
UPDATE Conflict SET Slug = 'william-trump-medical-fund-llc' WHERE ID = 376
UPDATE Conflict SET Slug = 'wilshire-hall' WHERE ID = 377
UPDATE Conflict SET Slug = 'wmtmf' WHERE ID = 378
UPDATE Conflict SET Slug = 'wollman-rink-operations' WHERE ID = 379
UPDATE Conflict SET Slug = 'yorktown-real-estate-formerly-yorktown-development-associates' WHERE ID = 380
