USE Trump
GO
INSERT INTO Source VALUES ('New York Post' , GetDate(), 1)
INSERT INTO Source VALUES ('Vanity Fair' , GetDate(), 1)
INSERT INTO Source VALUES ('CNN' , GetDate(), 1)
INSERT INTO Source VALUES ('Washington Post' , GetDate(), 1)
INSERT INTO Source VALUES ('Associated Press' , GetDate(), 1)
INSERT INTO Source VALUES ('Business Insider' , GetDate(), 1)
INSERT INTO Source VALUES ('Office of Government Ethics' , GetDate(), 1)
INSERT INTO Source VALUES ('Indy Star' , GetDate(), 1)
INSERT INTO Source VALUES ('Wall Street Journal' , GetDate(), 1)
INSERT INTO Source VALUES ('Newsweek' , GetDate(), 1)
INSERT INTO Source VALUES ('NYS Department of State' , GetDate(), 1)
INSERT INTO Source VALUES ('McClatchy' , GetDate(), 1)
INSERT INTO Source VALUES ('Forbes' , GetDate(), 1)
INSERT INTO Source VALUES ('ProPublica' , GetDate(), 1)
INSERT INTO Source VALUES ('New York Times' , GetDate(), 1)
INSERT INTO Source VALUES ('MNC Newsroom' , GetDate(), 1)
INSERT INTO Source VALUES ('Politico' , GetDate(), 1)
INSERT INTO Source VALUES ('National Labor Relations Board' , GetDate(), 1)
INSERT INTO Source VALUES ('Center for Public Integrity' , GetDate(), 1)
INSERT INTO Source VALUES ('Variety' , GetDate(), 1)
INSERT INTO Source VALUES ('Mother Jones' , GetDate(), 1)
INSERT INTO Source VALUES ('The Real Deal' , GetDate(), 1)
INSERT INTO Source VALUES ('Huffington Post' , GetDate(), 1)
INSERT INTO Source VALUES ('Bloomberg Politics' , GetDate(), 1)
INSERT INTO Source VALUES ('BuzzFeed' , GetDate(), 1)
INSERT INTO Source VALUES ('NPR' , GetDate(), 1)
INSERT INTO Source VALUES ('@realDonaldTrump' , GetDate(), 1)
INSERT INTO Source VALUES ('La Nacion' , GetDate(), 1)
INSERT INTO Source VALUES ('Shanghaiist' , GetDate(), 1)
INSERT INTO Source VALUES ('Economic Times' , GetDate(), 1)
INSERT INTO Source VALUES ('Fox News' , GetDate(), 1)
INSERT INTO Source VALUES ('General Services Administration' , GetDate(), 1)
INSERT INTO Source VALUES ('Government Executive' , GetDate(), 1)
INSERT INTO Source VALUES ('Trump, Inc. (WNYC)' , GetDate(), 1)
INSERT INTO Source VALUES ('Global News' , GetDate(), 1)
INSERT INTO Source VALUES ('Reuters' , GetDate(), 1)
INSERT INTO Source VALUES ('Florida Division of Corporations' , GetDate(), 1)
INSERT INTO Source VALUES ('Jacksonville Daily Record' , GetDate(), 1)
INSERT INTO Source VALUES ('Tulsa World' , GetDate(), 1)
INSERT INTO Source VALUES ('GigaOm' , GetDate(), 1)
INSERT INTO Source VALUES ('CNN Money' , GetDate(), 1)
INSERT INTO Source VALUES ('Japan Times' , GetDate(), 1)
INSERT INTO Source VALUES ('The Hill ' , GetDate(), 1)
INSERT INTO Source VALUES ('Fortune' , GetDate(), 1)
INSERT INTO Source VALUES ('The Post and Courier' , GetDate(), 1)
INSERT INTO Source VALUES ('The Foundation Center' , GetDate(), 1)
INSERT INTO Source VALUES ('PR Web' , GetDate(), 1)
INSERT INTO Source VALUES ('PR Newsire' , GetDate(), 1)
