USE Trump
GO

INSERT INTO BusinessUnit VALUES ('(various)')
INSERT INTO BusinessUnit VALUES ('1290 Avenue of the Americas, A Tenancy-In-Common')
INSERT INTO BusinessUnit VALUES ('3126 Corporation')
INSERT INTO BusinessUnit VALUES ('4 Shadow Tree Lane Member Corp')
INSERT INTO BusinessUnit VALUES ('DJT Holdings LLC')
INSERT INTO BusinessUnit VALUES ('4 Shadow Tree Lane LLC')
INSERT INTO BusinessUnit VALUES ('DJT Holdings Managing Member LLC')
INSERT INTO BusinessUnit VALUES ('Parc Consulting, Inc.')
INSERT INTO BusinessUnit VALUES ('The Donald J. Trump Revocable Trust')
INSERT INTO BusinessUnit VALUES ('40 Wall Development Associates LLC')
INSERT INTO BusinessUnit VALUES ('40 Wall Street Commercial LLC')
INSERT INTO BusinessUnit VALUES ('40 Wall Street Member Corp')
INSERT INTO BusinessUnit VALUES ('40 Wall Street LLC')
INSERT INTO BusinessUnit VALUES ('Trump Chicago Managing Member LLC')
INSERT INTO BusinessUnit VALUES ('Trump Chicago Member LLC')
INSERT INTO BusinessUnit VALUES ('TIHT Chicago Member Acquisition LLC')
INSERT INTO BusinessUnit VALUES ('401 Mezz Venture LLC')
INSERT INTO BusinessUnit VALUES ('401 North Wabash Venture LLC')
INSERT INTO BusinessUnit VALUES ('4T Holdings One LLC')
INSERT INTO BusinessUnit VALUES ('4T Holdings Two LLC')
INSERT INTO BusinessUnit VALUES ('55 Wall Development Corp')
INSERT INTO BusinessUnit VALUES ('721 33H Holdings LLC')
INSERT INTO BusinessUnit VALUES ('721 33H LLC')
INSERT INTO BusinessUnit VALUES ('767 Manager LLC')
INSERT INTO BusinessUnit VALUES ('809 North Canon Member Corporation')
INSERT INTO BusinessUnit VALUES ('809 North Canon LLC')
INSERT INTO BusinessUnit VALUES ('81 Pine Note Holder Inc')
INSERT INTO BusinessUnit VALUES ('Trump 845 LP LLC')
INSERT INTO BusinessUnit VALUES ('Trump 845 UN GP LLC')
INSERT INTO BusinessUnit VALUES ('845 UN Limited Partnership')
INSERT INTO BusinessUnit VALUES ('Ace Entertainment Holdings Inc. (F/K/A Trump Casinos, Inc., F/K/A Trump Taj Mahal, Inc.)')
INSERT INTO BusinessUnit VALUES ('Trump Family Members')
INSERT INTO BusinessUnit VALUES ('All County Building Supply &amp; Maintenance Corp.')
INSERT INTO BusinessUnit VALUES ('Aviation Payroll Company')
INSERT INTO BusinessUnit VALUES ('Donald J. Trump')
INSERT INTO BusinessUnit VALUES ('B Plaza Realty Corp.')
INSERT INTO BusinessUnit VALUES ('Bahrain')
INSERT INTO BusinessUnit VALUES ('Beach Haven Apartments #3 LLC')
INSERT INTO BusinessUnit VALUES ('Beach Haven Apt#1. Inc.')
INSERT INTO BusinessUnit VALUES ('Beach Haven Shopping Center LLC')
INSERT INTO BusinessUnit VALUES ('Bedford Hills Corp')
INSERT INTO BusinessUnit VALUES ('Briar Hall Operations LLC')
INSERT INTO BusinessUnit VALUES ('Briarcliff Properties, Inc.')
INSERT INTO BusinessUnit VALUES ('C Development Ventures LLC')
INSERT INTO BusinessUnit VALUES ('C Development Ventures Member Corp.')
INSERT INTO BusinessUnit VALUES ('Caribusiness Investments, S.R.L.')
INSERT INTO BusinessUnit VALUES ('Caribusiness MRE LLC')
INSERT INTO BusinessUnit VALUES ('Chelsea Hall LLC')
INSERT INTO BusinessUnit VALUES ('Chicago Unit Acquisition LLC')
INSERT INTO BusinessUnit VALUES ('China Trademark LLC')
INSERT INTO BusinessUnit VALUES ('Clyde Hall, Inc.')
INSERT INTO BusinessUnit VALUES ('Coronet Hall Inc.')
INSERT INTO BusinessUnit VALUES ('Country Apartments, LLC')
INSERT INTO BusinessUnit VALUES ('Country Investors LLC')
INSERT INTO BusinessUnit VALUES ('Country Properties, LLC')
INSERT INTO BusinessUnit VALUES ('Crippled America')
INSERT INTO BusinessUnit VALUES ('D B Pace Acquisition Member Corp.')
INSERT INTO BusinessUnit VALUES ('D B Pace Acquisition, LLC.')
INSERT INTO BusinessUnit VALUES ('Development Member Inc.')
INSERT INTO BusinessUnit VALUES ('DJ Aerospace (Bermuda) Limited')
INSERT INTO BusinessUnit VALUES ('DJT Aerospace LLC')
INSERT INTO BusinessUnit VALUES ('DJT Entrepreneur Managing Member LLC (f/k/a DJT University Managing Member LLC)')
INSERT INTO BusinessUnit VALUES ('DJT Entrepreneur Member LLC (f/k/a DJT University Member LLC)')
INSERT INTO BusinessUnit VALUES ('DJT Land Holdings Member Corp')
INSERT INTO BusinessUnit VALUES ('DJT Operations CX LLC')
INSERT INTO BusinessUnit VALUES ('DJT Operations I LLC')
INSERT INTO BusinessUnit VALUES ('DJT Operations II LLC')
INSERT INTO BusinessUnit VALUES ('Donald J Trump Enterprises II LLC')
INSERT INTO BusinessUnit VALUES ('Donald J Trump Enterprises III LLC')
INSERT INTO BusinessUnit VALUES ('Donald J Trump Enterprises LLC')
INSERT INTO BusinessUnit VALUES ('DSN Licensing LLC')
INSERT INTO BusinessUnit VALUES ('DSN Licensing Member Corp. (F/K/A Trump Marks Network Member Inc.)')
INSERT INTO BusinessUnit VALUES ('DT App Warrant Holding LLC')
INSERT INTO BusinessUnit VALUES ('DT App Warrant Holding Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Bali Golf Manager LLC')
INSERT INTO BusinessUnit VALUES ('DT Bali Golf Manager Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Bali Hotel Manager LLC')
INSERT INTO BusinessUnit VALUES ('DT Bali Hotel Manager Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Bali Technical Services Manager LLC')
INSERT INTO BusinessUnit VALUES ('DT Bali Technical Services Manager Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Connect Europe Limited')
INSERT INTO BusinessUnit VALUES ('DT Connect II LLC')
INSERT INTO BusinessUnit VALUES ('DT Connect II Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Connect LLC')
INSERT INTO BusinessUnit VALUES ('DT Connect Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Dubai Golf Manager LLC')
INSERT INTO BusinessUnit VALUES ('DT Dubai Golf Manager Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Dubai II Golf Manager LLC')
INSERT INTO BusinessUnit VALUES ('DT Dubai II Golf Manager Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Endeavor I LLC')
INSERT INTO BusinessUnit VALUES ('DT Endeavor I Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Home Marks International LLC')
INSERT INTO BusinessUnit VALUES ('DT Home Marks International Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT India Venture LLC')
INSERT INTO BusinessUnit VALUES ('DT India Venture Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Jeddah Technical Services Advisor LLC')
INSERT INTO BusinessUnit VALUES ('DT Jeddah Technical Services Advisor Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Jeddah Technical Services Manager LLC')
INSERT INTO BusinessUnit VALUES ('DT Jeddah Technical Services Manager Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Lido Golf Manager LLC')
INSERT INTO BusinessUnit VALUES ('DT Lido Golf Manager Member Corp/')
INSERT INTO BusinessUnit VALUES ('DT Lido Hotel Manager LLC')
INSERT INTO BusinessUnit VALUES ('DT Lido Hotel Manager Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Lido Technical Services Manager LLC')
INSERT INTO BusinessUnit VALUES ('DT Lido Technical Services Manager Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Marks Baku LLC')
INSERT INTO BusinessUnit VALUES ('DT Marks Baku Managing Member Corp')
INSERT INTO BusinessUnit VALUES ('DT Marks Bali LLC')
INSERT INTO BusinessUnit VALUES ('DT Marks Bali Member Corp')
INSERT INTO BusinessUnit VALUES ('DT Marks Dubai II LLC')
INSERT INTO BusinessUnit VALUES ('DT Marks Dubai II Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Marks Dubai LLC')
INSERT INTO BusinessUnit VALUES ('DT Marks Dubai Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Marks Gurgaon LLC')
INSERT INTO BusinessUnit VALUES ('DT Marks Gurgaon Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Marks Jersey City LLC')
INSERT INTO BusinessUnit VALUES ('DT Marks Jupiter LLC')
INSERT INTO BusinessUnit VALUES ('DT Marks Lido LLC')
INSERT INTO BusinessUnit VALUES ('DT Marks Lido Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Marks Products International LLC')
INSERT INTO BusinessUnit VALUES ('DT Marks Products International Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Marks Pune II LLC')
INSERT INTO BusinessUnit VALUES ('DT Marks Pune II Managing Member Corp')
INSERT INTO BusinessUnit VALUES ('DT Marks Pune LLC')
INSERT INTO BusinessUnit VALUES ('DT Marks Pune Managing Member Corp')
INSERT INTO BusinessUnit VALUES ('DT Marks Qatar LLC')
INSERT INTO BusinessUnit VALUES ('DT Marks Qatar Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Marks Rio LLC')
INSERT INTO BusinessUnit VALUES ('DT Marks Rio Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Marks Vancouver LP')
INSERT INTO BusinessUnit VALUES ('DT Marks Vancouver Manager Corp.')
INSERT INTO BusinessUnit VALUES ('DT Marks Worli LLC')
INSERT INTO BusinessUnit VALUES ('DT Marks Worli Member Corp')
INSERT INTO BusinessUnit VALUES ('DT Tower Gurgaon LLC')
INSERT INTO BusinessUnit VALUES ('DT Tower Gurgaon Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Tower I LLC')
INSERT INTO BusinessUnit VALUES ('DT Tower I Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Tower II LLC')
INSERT INTO BusinessUnit VALUES ('DT Tower II Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Tower Kolkata LLC')
INSERT INTO BusinessUnit VALUES ('DT Tower Kolkata Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Venture I LLC')
INSERT INTO BusinessUnit VALUES ('DT Venture I Member Corp.')
INSERT INTO BusinessUnit VALUES ('DT Venture II LLC (F/K/A Ritz Carlton Hotel at 112 Central Park South)')
INSERT INTO BusinessUnit VALUES ('DT Venture II Member Corp.')
INSERT INTO BusinessUnit VALUES ('DTTM Operations LLC')
INSERT INTO BusinessUnit VALUES ('DTTM Operations Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('DTW Venture LLC')
INSERT INTO BusinessUnit VALUES ('DTW Venture Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('EID Venture I Corporation')
INSERT INTO BusinessUnit VALUES ('EID Venture I LLC')
INSERT INTO BusinessUnit VALUES ('EID Venture II LLC')
INSERT INTO BusinessUnit VALUES ('EID Venture II Member Corp.')
INSERT INTO BusinessUnit VALUES ('Excel Venture I Corp.')
INSERT INTO BusinessUnit VALUES ('Excel Venture I LLC')
INSERT INTO BusinessUnit VALUES ('Fifty Seven Management Corp')
INSERT INTO BusinessUnit VALUES ('Fifty Seventh Street Associates LLC')
INSERT INTO BusinessUnit VALUES ('First Member, Inc.')
INSERT INTO BusinessUnit VALUES ('Flights Inc. (F/K/A Trump Flights Inc.)')
INSERT INTO BusinessUnit VALUES ('Florida Properties Management LLC')
INSERT INTO BusinessUnit VALUES ('Fontainbleu Apartments LLC')
INSERT INTO BusinessUnit VALUES ('Fred C. Trump, GRAT Trust- F/B/O Elizabeth Trump Grau')
INSERT INTO BusinessUnit VALUES ('General Services Administration')
INSERT INTO BusinessUnit VALUES ('Golf Productions LLC')
INSERT INTO BusinessUnit VALUES ('Golf Productions Member Corp.')
INSERT INTO BusinessUnit VALUES ('Golf Recreation Scotland Limited')
INSERT INTO BusinessUnit VALUES ('Helicopter Air Services, Inc.')
INSERT INTO BusinessUnit VALUES ('Highlander Hall, Inc.')
INSERT INTO BusinessUnit VALUES ('Holds United Technologies Corp')
INSERT INTO BusinessUnit VALUES ('How to Get Rich')
INSERT INTO BusinessUnit VALUES ('Hudson Waterfront Associates I, LP')
INSERT INTO BusinessUnit VALUES ('Hudson Waterfront Associates II, LP')
INSERT INTO BusinessUnit VALUES ('Hudson Waterfront Associates III, LP')
INSERT INTO BusinessUnit VALUES ('Hudson Waterfront Associates IV, LP')
INSERT INTO BusinessUnit VALUES ('Hudson Waterfront Associates V, LP')
INSERT INTO BusinessUnit VALUES ('Hudson Waterfront Associates, LP.')
INSERT INTO BusinessUnit VALUES ('HWA 1290 Ill LLC')
INSERT INTO BusinessUnit VALUES ('HWA 1290 IV LLC')
INSERT INTO BusinessUnit VALUES ('HWA 1290 V LLC')
INSERT INTO BusinessUnit VALUES ('HWA 555 Owners, LLC')
INSERT INTO BusinessUnit VALUES ('Identity Theft Productions LLC')
INSERT INTO BusinessUnit VALUES ('Identity Theft Productions Member Corp.')
INSERT INTO BusinessUnit VALUES ('Indian Hills Holdings LLC (F/K/A Indian Hills Development LLC)')
INSERT INTO BusinessUnit VALUES ('Internal Revenue Service')
INSERT INTO BusinessUnit VALUES ('Jupiter Golf Club LLC (Trump National Golf Club - Jupiter)')
INSERT INTO BusinessUnit VALUES ('Jupiter Golf Club Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('Ladder Capital')
INSERT INTO BusinessUnit VALUES ('Lamington Family Holdings LLC')
INSERT INTO BusinessUnit VALUES ('Lamington Farm Club, LLC (Trump National Golf Club - Bedminster)')
INSERT INTO BusinessUnit VALUES ('Lawrence Towers Apartments LLC')
INSERT INTO BusinessUnit VALUES ('LFB Acquisition LLC')
INSERT INTO BusinessUnit VALUES ('LFB Acquisition Member Corp.')
INSERT INTO BusinessUnit VALUES ('Mar-a-Lago')
INSERT INTO BusinessUnit VALUES ('Mar-A-Lago Club, Inc.')
INSERT INTO BusinessUnit VALUES ('Mar-A-Lago Club, L.L.C.')
INSERT INTO BusinessUnit VALUES ('Maryanne Trump GRAT Trust- F/B/O Elizabeth Trump Grau')
INSERT INTO BusinessUnit VALUES ('Melania LLC')
INSERT INTO BusinessUnit VALUES ('Melania Marks Accessories LLC')
INSERT INTO BusinessUnit VALUES ('Melania Marks Accessories Member Corp.')
INSERT INTO BusinessUnit VALUES ('Melania Marks Skincare LLC')
INSERT INTO BusinessUnit VALUES ('Melania Marks Skincare Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('Merrill Lynch Credit Corporation')
INSERT INTO BusinessUnit VALUES ('Midland Associates')
INSERT INTO BusinessUnit VALUES ('Miss Universe L.P., LLLP (F/K/A Trump Pageants, LP.)')
INSERT INTO BusinessUnit VALUES ('Mobile Payroll Construction LLC')
INSERT INTO BusinessUnit VALUES ('Mobile Payroll Construction Manager Corp.')
INSERT INTO BusinessUnit VALUES ('MZ Berger &amp; Company LLC')
INSERT INTO BusinessUnit VALUES ('National Labor Relations Board')
INSERT INTO BusinessUnit VALUES ('NBC')
INSERT INTO BusinessUnit VALUES ('Never Give Up')
INSERT INTO BusinessUnit VALUES ('New Sunshine LLC')
INSERT INTO BusinessUnit VALUES ('Nitto World Co., Limited')
INSERT INTO BusinessUnit VALUES ('Ocean Development Member Inc.')
INSERT INTO BusinessUnit VALUES ('One Central Park West Associates')
INSERT INTO BusinessUnit VALUES ('One Central Park West PT Associates')
INSERT INTO BusinessUnit VALUES ('OPO Hotel Manager LLC')
INSERT INTO BusinessUnit VALUES ('OPO Hotel Manager Member Corp')
INSERT INTO BusinessUnit VALUES ('OWO Developer LLC')
INSERT INTO BusinessUnit VALUES ('Panama Ocean Club Management LLC')
INSERT INTO BusinessUnit VALUES ('Panama Ocean Club Management Member Corp.')
INSERT INTO BusinessUnit VALUES ('Paramount RPV Holdings LLC')
INSERT INTO BusinessUnit VALUES ('Paramount RPV Holdings Manager Corp.')
INSERT INTO BusinessUnit VALUES ('Park Briar Associates')
INSERT INTO BusinessUnit VALUES ('Pine Hill Development LLC')
INSERT INTO BusinessUnit VALUES ('Pine Hill Development Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('Plaza Consulting Corp')
INSERT INTO BusinessUnit VALUES ('Poker Venture LLC')
INSERT INTO BusinessUnit VALUES ('Poker Venture Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('QVC')
INSERT INTO BusinessUnit VALUES ('Reg-Tru Equities, Ltd.')
INSERT INTO BusinessUnit VALUES ('Restaurant 40 LLC')
INSERT INTO BusinessUnit VALUES ('Restaurant 40 Member Corp.')
INSERT INTO BusinessUnit VALUES ('Royal Bank America')
INSERT INTO BusinessUnit VALUES ('RPV Development LLC')
INSERT INTO BusinessUnit VALUES ('Russian real estate investors')
INSERT INTO BusinessUnit VALUES ('Scotland Acquisitions LLC')
INSERT INTO BusinessUnit VALUES ('Screen Actors Guild')
INSERT INTO BusinessUnit VALUES ('Sentient Jets LLC (N/K/A Trump Jets LLC)')
INSERT INTO BusinessUnit VALUES ('Sentient Jets Member Corp.')
INSERT INTO BusinessUnit VALUES ('Seven Springs LLC')
INSERT INTO BusinessUnit VALUES ('Shore Haven Apt#1, Inc.')
INSERT INTO BusinessUnit VALUES ('Shore Haven Management Corp.')
INSERT INTO BusinessUnit VALUES ('Shore Haven Shopping Center LLC')
INSERT INTO BusinessUnit VALUES ('SLC Turnberry Limited (Trump Turnberry)')
INSERT INTO BusinessUnit VALUES ('Spring Creek Plaza')
INSERT INTO BusinessUnit VALUES ('Starrett City Associates, L.P.')
INSERT INTO BusinessUnit VALUES ('Stephanie Clifford (aka Stormy Daniels)')
INSERT INTO BusinessUnit VALUES ('Storage 106 LLC')
INSERT INTO BusinessUnit VALUES ('Sussex Hall, Inc.')
INSERT INTO BusinessUnit VALUES ('T Express LLC')
INSERT INTO BusinessUnit VALUES ('T Express Manager Member Corp.')
INSERT INTO BusinessUnit VALUES ('T International Realty LLC (dba Trump International Realty)')
INSERT INTO BusinessUnit VALUES ('Tag Air, Inc.')
INSERT INTO BusinessUnit VALUES ('Tanoesoedibjo, Hary')
INSERT INTO BusinessUnit VALUES ('TC Marks Buenos Aires LLC')
INSERT INTO BusinessUnit VALUES ('THC Baku Hotel Manager Services LLC')
INSERT INTO BusinessUnit VALUES ('THC Baku Hotel Manager Services Member Corp.')
INSERT INTO BusinessUnit VALUES ('THC Baku Services LLC')
INSERT INTO BusinessUnit VALUES ('THC Baku Services Member Corp.')
INSERT INTO BusinessUnit VALUES ('THC Barra Hotelaria LTDA')
INSERT INTO BusinessUnit VALUES ('THC Central Reservations LLC')
INSERT INTO BusinessUnit VALUES ('THC Central Reservations Member Corp.')
INSERT INTO BusinessUnit VALUES ('THC China Development LLC (F/K/A Trump China Development LLC)')
INSERT INTO BusinessUnit VALUES ('THC China Development Management Corp (F/K/A Trump China Development Management Corp)')
INSERT INTO BusinessUnit VALUES ('THC China Technical Services LLC')
INSERT INTO BusinessUnit VALUES ('THC China Technical Services Manager Corp.')
INSERT INTO BusinessUnit VALUES ('THC DC Restaurant Hospitality LLC')
INSERT INTO BusinessUnit VALUES ('THC Development Brazil LLC')
INSERT INTO BusinessUnit VALUES ('THC Development Brazil Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('THC Dubai II Hotel Manager LLC')
INSERT INTO BusinessUnit VALUES ('THC Dubai II Hotel Manager Member Corp.')
INSERT INTO BusinessUnit VALUES ('THC Hotel Development LLC')
INSERT INTO BusinessUnit VALUES ('THC IMEA Development LLC')
INSERT INTO BusinessUnit VALUES ('THC Jeddah Hotel Advisor LLC')
INSERT INTO BusinessUnit VALUES ('THC Jeddah Hotel Advisor Member Corp.')
INSERT INTO BusinessUnit VALUES ('THC Jeddah Hotel Manager LLC')
INSERT INTO BusinessUnit VALUES ('THC Jeddah Hotel Manager Member Corp.')
INSERT INTO BusinessUnit VALUES ('THC Miami Restaurant Hospitality LLC')
INSERT INTO BusinessUnit VALUES ('THC Miami Restaurant Hospitality Member Corp.')
INSERT INTO BusinessUnit VALUES ('THC Qatar Hotel Manager LLC')
INSERT INTO BusinessUnit VALUES ('THC Qatar Hotel Manager Member Corp.')
INSERT INTO BusinessUnit VALUES ('THC Rio Manager LLC')
INSERT INTO BusinessUnit VALUES ('THC Rio Managing Member Corp')
INSERT INTO BusinessUnit VALUES ('THC Sales &amp; Marketing LLC')
INSERT INTO BusinessUnit VALUES ('THC Sales &amp; Marketing Member Corp.')
INSERT INTO BusinessUnit VALUES ('THC Services Shenzhen LLC')
INSERT INTO BusinessUnit VALUES ('THC Services Shenzhen Member Corp.')
INSERT INTO BusinessUnit VALUES ('THC Shenzhen Hotel Manager LLC')
INSERT INTO BusinessUnit VALUES ('THC Shenzhen Hotel Manager Member Corp.')
INSERT INTO BusinessUnit VALUES ('THC Vancouver Management Corp')
INSERT INTO BusinessUnit VALUES ('THC Vancouver Payroll ULC')
INSERT INTO BusinessUnit VALUES ('THC Venture I LLC')
INSERT INTO BusinessUnit VALUES ('THC Venture I Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('THC Venture II LLC')
INSERT INTO BusinessUnit VALUES ('THC Venture II Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('THC Venture III LLC (N/K/A TTTT Venture LLC)')
INSERT INTO BusinessUnit VALUES ('THC Venture III Managing Member Corp. - N/K/A TTTT Venture Member Corp.')
INSERT INTO BusinessUnit VALUES ('The America We Deserve')
INSERT INTO BusinessUnit VALUES ('The Art of the Comeback')
INSERT INTO BusinessUnit VALUES ('The Art of the Deal')
INSERT INTO BusinessUnit VALUES ('The Best Real Estate Advice I Ever Received')
INSERT INTO BusinessUnit VALUES ('The Caribusiness RE Corp')
INSERT INTO BusinessUnit VALUES ('The Daily Mail')
INSERT INTO BusinessUnit VALUES ('The Donald J. Trump Company LLC')
INSERT INTO BusinessUnit VALUES ('The Donald J. Trump Foundation')
INSERT INTO BusinessUnit VALUES ('The Donald J. Trump Foundation, Inc.')
INSERT INTO BusinessUnit VALUES ('The Donald J. Trump Grantor Trust')
INSERT INTO BusinessUnit VALUES ('The East 61 St. Company, LP.')
INSERT INTO BusinessUnit VALUES ('The Fred C. Trump December 16, 1976 Trust- F/B/O Donald J. Trump.')
INSERT INTO BusinessUnit VALUES ('The Fred C. Trump December 16, 1976 Trust- F/B/O Elizabeth J. Trump')
INSERT INTO BusinessUnit VALUES ('The Fred C. Trump December 16, 1976 Trust- F/B/O Robert S. Trump')
INSERT INTO BusinessUnit VALUES ('The Police Athletic League, Inc.')
INSERT INTO BusinessUnit VALUES ('The Trump Corporation')
INSERT INTO BusinessUnit VALUES ('The Trump Entrepreneur Initiative LLC (f/k/a Trump University CA LLC)')
INSERT INTO BusinessUnit VALUES ('The Trump Entrepreneur Initiative LLC (NY Domestic)')
INSERT INTO BusinessUnit VALUES ('The Trump Equitable Fifth Avenue Company')
INSERT INTO BusinessUnit VALUES ('The Trump Follies LLC')
INSERT INTO BusinessUnit VALUES ('The Trump Follies Member Inc.')
INSERT INTO BusinessUnit VALUES ('The Trump Hotel Corp.')
INSERT INTO BusinessUnit VALUES ('The Trump Marks Real Estate Corp.')
INSERT INTO BusinessUnit VALUES ('The Trump Organization, Inc.')
INSERT INTO BusinessUnit VALUES ('The Way to the Top')
INSERT INTO BusinessUnit VALUES ('Think Big and Kick Ass')
INSERT INTO BusinessUnit VALUES ('Think Like a Billionaire')
INSERT INTO BusinessUnit VALUES ('Think Like a Champion')
INSERT INTO BusinessUnit VALUES ('TIGL Common Area Management Corp.')
INSERT INTO BusinessUnit VALUES ('TIGL Common Area Management Holdings LLC')
INSERT INTO BusinessUnit VALUES ('TIGL Ireland Enterprises Limited (Trump International Golf Links - Doonbeg)')
INSERT INTO BusinessUnit VALUES ('TIGL Ireland Management Limited')
INSERT INTO BusinessUnit VALUES ('TIHC Reservations LLC')
INSERT INTO BusinessUnit VALUES ('TIHH Member Corp')
INSERT INTO BusinessUnit VALUES ('TIHH Member LLC')
INSERT INTO BusinessUnit VALUES ('TIHM Member Corp')
INSERT INTO BusinessUnit VALUES ('TIHT Commercial LLC')
INSERT INTO BusinessUnit VALUES ('TIHT Holding Company LLC')
INSERT INTO BusinessUnit VALUES ('TIHT Member LLC')
INSERT INTO BusinessUnit VALUES ('Time To Get Tough')
INSERT INTO BusinessUnit VALUES ('Tipperary Realty Corp.')
INSERT INTO BusinessUnit VALUES ('TMG Member, LLC')
INSERT INTO BusinessUnit VALUES ('TNGC Charlotte LLC')
INSERT INTO BusinessUnit VALUES ('TNGC Charlotte Manager Corp')
INSERT INTO BusinessUnit VALUES ('TNGC Dutchess County LLC (F/K/A Trump Marks Classis Cars LLC)')
INSERT INTO BusinessUnit VALUES ('TNGC Dutchess County Member Corp. (F/K/A Trump Marks Classic Cars Member Corp.)')
INSERT INTO BusinessUnit VALUES ('TNGC Jupiter Management LLC')
INSERT INTO BusinessUnit VALUES ('TNGC Jupiter Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('TNGC Pine Hill LLC (F/K/A Crest Court LLC) (Trump National Golf Club - Philadelphia)')
INSERT INTO BusinessUnit VALUES ('TNGC Pine Hill Member Corp. (F/K/A Crest Court Member Court)')
INSERT INTO BusinessUnit VALUES ('Toronto Development LLC')
INSERT INTO BusinessUnit VALUES ('TP CFD LLC')
INSERT INTO BusinessUnit VALUES ('TP CFD Manager Corp.')
INSERT INTO BusinessUnit VALUES ('Travel Enterprises Management Inc. (F/K/A Toys at Trump, Inc.)')
INSERT INTO BusinessUnit VALUES ('Trump 101: The Way to Success')
INSERT INTO BusinessUnit VALUES ('Trump 106 CPS LLC')
INSERT INTO BusinessUnit VALUES ('Trump 767 Management LLC')
INSERT INTO BusinessUnit VALUES ('Trump 845 UN MGR Corp.')
INSERT INTO BusinessUnit VALUES ('Trump 845 UN MGR LLC (F/K/A 845 UN LLC)')
INSERT INTO BusinessUnit VALUES ('Trump AC Casino Marks LLC')
INSERT INTO BusinessUnit VALUES ('Trump AC Casino Marks Member Corp')
INSERT INTO BusinessUnit VALUES ('Trump Acquisition Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Acquisition, LLC')
INSERT INTO BusinessUnit VALUES ('Trump Books LLC (The Midas Touch)')
INSERT INTO BusinessUnit VALUES ('Trump Books Manager Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Brazil LLC')
INSERT INTO BusinessUnit VALUES ('Trump Briarcliff Manor Development LLC (F/K/A Briar Hall Development LLC)')
INSERT INTO BusinessUnit VALUES ('Trump Canadian Services Inc.')
INSERT INTO BusinessUnit VALUES ('Trump Canouan Estate LLC')
INSERT INTO BusinessUnit VALUES ('Trump Canouan Estate Member Corp')
INSERT INTO BusinessUnit VALUES ('Trump Caribbean LLC')
INSERT INTO BusinessUnit VALUES ('Trump Carousel LLC')
INSERT INTO BusinessUnit VALUES ('Trump Carousel Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Central Park West Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Chicago Commercial Manager LLC')
INSERT INTO BusinessUnit VALUES ('Trump Chicago Commercial Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Chicago Development LLC')
INSERT INTO BusinessUnit VALUES ('Trump Chicago Hotel Manager LLC')
INSERT INTO BusinessUnit VALUES ('Trump Chicago Hotel Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Chicago Residential Manager LLC')
INSERT INTO BusinessUnit VALUES ('Trump Chicago Residential Member Corp')
INSERT INTO BusinessUnit VALUES ('Trump Chicago Retail LLC')
INSERT INTO BusinessUnit VALUES ('Trump Chicago Retail Manager LLC')
INSERT INTO BusinessUnit VALUES ('Trump Chicago Retail Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Classic Cars LLC')
INSERT INTO BusinessUnit VALUES ('Trump Classic Cars Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Commercial Chicago LLC')
INSERT INTO BusinessUnit VALUES ('Trump CPS Corp.')
INSERT INTO BusinessUnit VALUES ('Trump CPS LLC')
INSERT INTO BusinessUnit VALUES ('Trump Delmonico LLC')
INSERT INTO BusinessUnit VALUES ('Trump Development Services LLC')
INSERT INTO BusinessUnit VALUES ('Trump Development Services Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Drinks Israel Holdings')
INSERT INTO BusinessUnit VALUES ('Trump Drinks Israel Holdings Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Drinks Israel LLC')
INSERT INTO BusinessUnit VALUES ('Trump Drinks Israel Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Education ULC')
INSERT INTO BusinessUnit VALUES ('Trump Empire State, Inc.')
INSERT INTO BusinessUnit VALUES ('Trump Endeavor 12 LLC (Trump National Doral)')
INSERT INTO BusinessUnit VALUES ('Trump Endeavor 12 Manager Corp.')
INSERT INTO BusinessUnit VALUES ('Trump EU Marks LLC')
INSERT INTO BusinessUnit VALUES ('Trump EU Marks Member Corp')
INSERT INTO BusinessUnit VALUES ('Trump Ferry Point LLC (D/B/A Trump Golf Links Ferry Point [Delaware], Trump Golf Links Ferry Point [New York], Trump Golf Links [New York])')
INSERT INTO BusinessUnit VALUES ('Trump Ferry Point Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Florida Management LLC')
INSERT INTO BusinessUnit VALUES ('Trump Florida Manager Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Golf Acquisitions LLC')
INSERT INTO BusinessUnit VALUES ('Trump Golf Coco Beach LLC')
INSERT INTO BusinessUnit VALUES ('Trump Golf Coco Beach Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Golf Management LLC')
INSERT INTO BusinessUnit VALUES ('Trump Home Marks LLC')
INSERT INTO BusinessUnit VALUES ('Trump Home Marks Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Hotel Rio de Janeiro')
INSERT INTO BusinessUnit VALUES ('Trump Ice LLC')
INSERT INTO BusinessUnit VALUES ('Trump Ice, Inc.')
INSERT INTO BusinessUnit VALUES ('Trump Identity')
INSERT INTO BusinessUnit VALUES ('Trump Identity Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump International Development LLC')
INSERT INTO BusinessUnit VALUES ('Trump International Development Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump International Golf Club LC (Trump International Golf Club - Florida)')
INSERT INTO BusinessUnit VALUES ('Trump International Golf Club Scotland Limited')
INSERT INTO BusinessUnit VALUES ('Trump International Golf Club, Inc.')
INSERT INTO BusinessUnit VALUES ('Trump International Golf Links - Scotland')
INSERT INTO BusinessUnit VALUES ('Trump International Hotel and Tower (Panama)')
INSERT INTO BusinessUnit VALUES ('Trump International Hotel Hawaii LLC')
INSERT INTO BusinessUnit VALUES ('Trump International Hotels Management LLC (D/B/A Trump Hotel Collection [Hawaii], Trump Hotel Collection [New York])')
INSERT INTO BusinessUnit VALUES ('Trump International Management Corp')
INSERT INTO BusinessUnit VALUES ('Trump Jets LLC (F/K/A Sentient Jets LLC)')
INSERT INTO BusinessUnit VALUES ('Trump Kelowna LLC')
INSERT INTO BusinessUnit VALUES ('Trump Kelowna Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Korea LLC')
INSERT INTO BusinessUnit VALUES ('Trump Korean Projects LLC')
INSERT INTO BusinessUnit VALUES ('Trump Las Olas LLC')
INSERT INTO BusinessUnit VALUES ('Trump Las Olas Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Las Vegas Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Las Vegas Development LLC')
INSERT INTO BusinessUnit VALUES ('Trump Las Vegas Managing Member LLC')
INSERT INTO BusinessUnit VALUES ('Trump Las Vegas Member LLC')
INSERT INTO BusinessUnit VALUES ('Trump Las Vegas Sales &amp; Marketing Inc.')
INSERT INTO BusinessUnit VALUES ('Trump Lauderdale Development 2 LLC')
INSERT INTO BusinessUnit VALUES ('Trump Lauderdale Development LLC')
INSERT INTO BusinessUnit VALUES ('Trump lntematlonal Hotel and Tower Condominium')
INSERT INTO BusinessUnit VALUES ('Trump Management Inc.')
INSERT INTO BusinessUnit VALUES ('Trump Marketing LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Asia Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Asia LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Atlanta LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Atlanta Member Corp')
INSERT INTO BusinessUnit VALUES ('Trump Marks Baja Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Baja LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Batumi LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Batumi Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Batumi Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Beverages Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Beverages LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Canouan Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Canouan LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Chicago LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Chicago Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Dubai Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Dubai LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Egypt Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Egypt LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Fine Foods LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Fine Foods Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Ft. Lauderdale LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Ft. Lauderdale Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Gofl Swing LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Golf Swing Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks GP Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Holding LP (F/K/A Trump Marks LP)')
INSERT INTO BusinessUnit VALUES ('Trump Marks Hollywood Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Hollywood LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Istanbul II Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Istanbul ll LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Jersey City Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Jersey City LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Las Vegas Corp')
INSERT INTO BusinessUnit VALUES ('Trump Marks Las Vegas LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Magazine Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Magazine LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Mattress LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Mattress Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Menswear LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Menswear Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Mortgage Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Mtg LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Mumbai LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Mumbai Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks New Orleans Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks New Orleans LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks New Rochelle Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks New Rochelle LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Palm Beach Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Palm Beach LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Panama Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Panama LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Philadelphia Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Philadelphia LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Philippines Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Philippines LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Products LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Products Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Puerto Rico I LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Puerto Rico I Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Puerto Rico II LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Puerto Rico II Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Punta del Este LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Punta del Este Manager Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Real Estate LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks SOHO License Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks SOHO LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks South Africa LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks South Africa Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Stamford Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Stamford LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Sunny Isles I LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Sunny Isles I Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Sunny Isles II LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Sunny Isles II Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Tampa Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Tampa LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Toronto Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Toronto LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Toronto LP (F/K/A Trump Toronto Management LP)')
INSERT INTO BusinessUnit VALUES ('Trump Marks Waikiki Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Waikiki LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks Westchester Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks Westchester LLC')
INSERT INTO BusinessUnit VALUES ('Trump Marks White Plains Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Marks White Plains LLC')
INSERT INTO BusinessUnit VALUES ('Trump Miami Resort Management LLC')
INSERT INTO BusinessUnit VALUES ('Trump Miami Resort Management Member Corp')
INSERT INTO BusinessUnit VALUES ('Trump Model Management LLC')
INSERT INTO BusinessUnit VALUES ('Trump Mortgage LLC')
INSERT INTO BusinessUnit VALUES ('Trump National Golf Club - Charlotte')
INSERT INTO BusinessUnit VALUES ('Trump National Golf Club - Hudson Valley')
INSERT INTO BusinessUnit VALUES ('Trump National Golf Club Colts Neck LLC')
INSERT INTO BusinessUnit VALUES ('Trump National Golf Club Colts Neck Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump National Golf Club LLC (Trump National Golf Club - Westchester)')
INSERT INTO BusinessUnit VALUES ('Trump National Golf Club Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump National Golf Club Washington DC LLC')
INSERT INTO BusinessUnit VALUES ('Trump National Golf Club Washington DC Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Ocean Manager Inc.')
INSERT INTO BusinessUnit VALUES ('Trump Ocean Managing Member LLC')
INSERT INTO BusinessUnit VALUES ('Trump Old Post Office LLC')
INSERT INTO BusinessUnit VALUES ('Trump Old Post Office Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump On the Ocean LLC')
INSERT INTO BusinessUnit VALUES ('Trump Organization LLC (D/B/A The Trump Organization)')
INSERT INTO BusinessUnit VALUES ('Trump Pageants, Inc.')
INSERT INTO BusinessUnit VALUES ('Trump Palace Condominium')
INSERT INTO BusinessUnit VALUES ('Trump Palace/Parc LLC')
INSERT INTO BusinessUnit VALUES ('Trump Panama Condominium Management LLC')
INSERT INTO BusinessUnit VALUES ('Trump Panama Condominium Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Panama Hotel Management LLC')
INSERT INTO BusinessUnit VALUES ('Trump Panama Hotel Management Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Parc East Condominium')
INSERT INTO BusinessUnit VALUES ('Trump Park Avenue Acquisition LLC')
INSERT INTO BusinessUnit VALUES ('Trump Park Avenue LLC')
INSERT INTO BusinessUnit VALUES ('Trump Payroll Chicago LLC')
INSERT INTO BusinessUnit VALUES ('Trump Payroll Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Phoenix Development LLC')
INSERT INTO BusinessUnit VALUES ('Trump Plaza LLC')
INSERT INTO BusinessUnit VALUES ('Trump Plaza Member Inc. (F/K/A Trump Plaza Corp.)')
INSERT INTO BusinessUnit VALUES ('Trump Production Managing Member Inc.')
INSERT INTO BusinessUnit VALUES ('Trump Productions LLC (F/K/A Rancho Lien LLC)')
INSERT INTO BusinessUnit VALUES ('Trump Project Management Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Properties LLC')
INSERT INTO BusinessUnit VALUES ('Trump Realty Services, LLC (F/K/A Trump Mortgage Services LLC (03) &amp; Tower Mortgage Services LLC)')
INSERT INTO BusinessUnit VALUES ('Trump Restaurants LLC')
INSERT INTO BusinessUnit VALUES ('Trump Riverside Management LLC')
INSERT INTO BusinessUnit VALUES ('Trump Ruffin Commercial LLC')
INSERT INTO BusinessUnit VALUES ('Trump Ruffin LLC')
INSERT INTO BusinessUnit VALUES ('Trump Ruffin Tower I LLC')
INSERT INTO BusinessUnit VALUES ('Trump Sales &amp; Leasing Chicago LLC')
INSERT INTO BusinessUnit VALUES ('Trump Sales &amp; Leasing Chicago Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Scotland Member Inc.')
INSERT INTO BusinessUnit VALUES ('Trump Scotsborough Square LLC')
INSERT INTO BusinessUnit VALUES ('Trump Scotsborough Square Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump SoHo Hotel Condominium New York')
INSERT INTO BusinessUnit VALUES ('Trump Soho Member LLC')
INSERT INTO BusinessUnit VALUES ('Trump Toronto Development Inc.')
INSERT INTO BusinessUnit VALUES ('Trump Toronto Hotel Management Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Toronto Member Corp. (F/K/A Trump Toronto Management Member Corp.)')
INSERT INTO BusinessUnit VALUES ('Trump Tower Commercial LLC')
INSERT INTO BusinessUnit VALUES ('Trump Tower Condominium Residential Section')
INSERT INTO BusinessUnit VALUES ('Trump Tower Managing Member Inc.')
INSERT INTO BusinessUnit VALUES ('Trump Tower Triplex')
INSERT INTO BusinessUnit VALUES ('Trump Towers Istanbul')
INSERT INTO BusinessUnit VALUES ('Trump Village Construction Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Vineyard Estates LLC')
INSERT INTO BusinessUnit VALUES ('Trump Vineyard Estates Lot 3 Owner LLC (F/K/A Eric Trump Land Holdings LLC)')
INSERT INTO BusinessUnit VALUES ('Trump Vineyard Estates Manager Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Virginia Acquisitions LLC (F/K/A Virginia Acquisitions LLC)')
INSERT INTO BusinessUnit VALUES ('Trump Virginia Acquisitions Manager Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Virginia Lot 5 LLC')
INSERT INTO BusinessUnit VALUES ('Trump Virginia Lot 5 Manager Corp.')
INSERT INTO BusinessUnit VALUES ('Trump Wine Marks LLC')
INSERT INTO BusinessUnit VALUES ('Trump Wine Marks Member Corp.')
INSERT INTO BusinessUnit VALUES ('Trump World Productions LLC')
INSERT INTO BusinessUnit VALUES ('Trump World Productions Manager Corp.')
INSERT INTO BusinessUnit VALUES ('Trump World Publications')
INSERT INTO BusinessUnit VALUES ('Trump: Surviving at the Top')
INSERT INTO BusinessUnit VALUES ('Trump&#39;s Castle Management Corp.')
INSERT INTO BusinessUnit VALUES ('Trump/New World Property Management LLC')
INSERT INTO BusinessUnit VALUES ('Trust U/W/O Fred C. Trump - Elizabeth Trump Grau')
INSERT INTO BusinessUnit VALUES ('Trust U/W/O Fred C. Trump - F/B/O the grandchildren of Fred C. Trump')
INSERT INTO BusinessUnit VALUES ('Trust U/W/O Fred C. Trump- Tiffany Ariana Trump')
INSERT INTO BusinessUnit VALUES ('Turnberry Scotland LLC')
INSERT INTO BusinessUnit VALUES ('Turnberry Scotland Managing Member Corp')
INSERT INTO BusinessUnit VALUES ('TW Venture I LLC')
INSERT INTO BusinessUnit VALUES ('TW Venture I Managing Member Corp')
INSERT INTO BusinessUnit VALUES ('TW Venture II LLC')
INSERT INTO BusinessUnit VALUES ('TW Venture II Managing Member Corp')
INSERT INTO BusinessUnit VALUES ('Ultimate Air Corp.')
INSERT INTO BusinessUnit VALUES ('Unit 2502 Enterprises Corp.')
INSERT INTO BusinessUnit VALUES ('Unit 2502 Enterprises LLC')
INSERT INTO BusinessUnit VALUES ('VH Property Corp. (Trump National Golf Club - Los Angeles)')
INSERT INTO BusinessUnit VALUES ('VHPS LLC')
INSERT INTO BusinessUnit VALUES ('West Palm Operations LLC')
INSERT INTO BusinessUnit VALUES ('Wexford Hall Inc.')
INSERT INTO BusinessUnit VALUES ('White Course LLC')
INSERT INTO BusinessUnit VALUES ('White Course Managing Member Corp.')
INSERT INTO BusinessUnit VALUES ('Why We Want You To Be Rich')
INSERT INTO BusinessUnit VALUES ('William Trump Medical Fund LLC')
INSERT INTO BusinessUnit VALUES ('Wilshire Hall LLC')
INSERT INTO BusinessUnit VALUES ('WMTMF LLC')
INSERT INTO BusinessUnit VALUES ('Wollman Rink Operations LLC')
INSERT INTO BusinessUnit VALUES ('Yorktown Real Estate LLC (F/K/A Yorktown Development Associates LLC)')
