USE Trump
GO

INSERT INTO Business VALUES ('Hwa 1290 Ill LLC')
INSERT INTO Business VALUES ('Hwa 1290 Iv LLC')
INSERT INTO Business VALUES ('Hwa 1290 V LLC')
INSERT INTO Business VALUES ('1290 Avenue Of The Americas, A Tenancy-In-Common')
INSERT INTO Business VALUES ('3126 Corporation')
INSERT INTO Business VALUES ('4 Shadow Tree Lane Member Corp')
INSERT INTO Business VALUES ('Djt Holdings LLC')
INSERT INTO Business VALUES ('4 Shadow Tree Lane LLC')
INSERT INTO Business VALUES ('Djt Holdings Managing Member LLC')
INSERT INTO Business VALUES ('Parc Consulting, Inc.')
INSERT INTO Business VALUES ('The Donald J. Trump Revocable Trust')
INSERT INTO Business VALUES ('40 Wall Development Associates LLC')
INSERT INTO Business VALUES ('40 Wall Street Commercial LLC')
INSERT INTO Business VALUES ('40 Wall Street Member Corp')
INSERT INTO Business VALUES ('40 Wall Street LLC')
INSERT INTO Business VALUES ('Tttt Venture LLC')
INSERT INTO Business VALUES ('4T Holdings One LLC')
INSERT INTO Business VALUES ('4T Holdings Two LLC')
INSERT INTO Business VALUES ('767 Manager LLC')
INSERT INTO Business VALUES ('809 North Canon Member Corporation')
INSERT INTO Business VALUES ('809 North Canon LLC')
INSERT INTO Business VALUES ('81 Pine Note Holder Inc')
INSERT INTO Business VALUES ('Trump 845 Lp LLC')
INSERT INTO Business VALUES ('Trump 845 Un Gp LLC')
INSERT INTO Business VALUES ('845 Un Limited Partnership')
INSERT INTO Business VALUES ('Ace Entertainment Holdings Inc. (F/K/A Trump Casinos, Inc., F/K/A Trump Taj Mahal, Inc.)')
INSERT INTO Business VALUES ('Trump Family Members')
INSERT INTO Business VALUES ('All County Building Supply &Amp; Maintenance Corp.')
INSERT INTO Business VALUES ('Annie Veltri')
INSERT INTO Business VALUES ('Aviation Payroll Company')
INSERT INTO Business VALUES ('Donald J. Trump')
INSERT INTO Business VALUES ('B Plaza Realty Corp.')
INSERT INTO Business VALUES ('Bedford Hills Corp')
INSERT INTO Business VALUES ('Development Member Inc.')
INSERT INTO Business VALUES ('Briar Hall Operations LLC')
INSERT INTO Business VALUES ('Dttm Operations Managing Member Corp.')
INSERT INTO Business VALUES ('C Development Ventures Member Corp.')
INSERT INTO Business VALUES ('C Development Ventures LLC')
INSERT INTO Business VALUES ('The Caribusiness Re Corp')
INSERT INTO Business VALUES ('Caribusiness Mre LLC')
INSERT INTO Business VALUES ('Caribusiness Investments, S.R.L.')
INSERT INTO Business VALUES ('Chelsea Hall LLC')
INSERT INTO Business VALUES ('Chicago Unit Acquisition LLC')
INSERT INTO Business VALUES ('China Trademark LLC')
INSERT INTO Business VALUES ('Clyde Hall, Inc.')
INSERT INTO Business VALUES ('Coronet Hall Inc.')
INSERT INTO Business VALUES ('Country Apartments, LLC')
INSERT INTO Business VALUES ('Country Investors LLC')
INSERT INTO Business VALUES ('Country Properties, LLC')
INSERT INTO Business VALUES ('Cpw Pt Partners Gp')
INSERT INTO Business VALUES ('Crippled America')
INSERT INTO Business VALUES ('D B Pace Acquisition Member Corp.')
INSERT INTO Business VALUES ('D B Pace Acquisition, LLC.')
INSERT INTO Business VALUES ('Daewoo America Development (New York) Corp')
INSERT INTO Business VALUES ('Dj Aerospace (Bermuda) Limited')
INSERT INTO Business VALUES ('Djt Aerospace LLC')
INSERT INTO Business VALUES ('>')
INSERT INTO Business VALUES ('Djt Land Holdings Member Corp')
INSERT INTO Business VALUES ('Djt Operations Cx LLC')
INSERT INTO Business VALUES ('Djt Operations I LLC')
INSERT INTO Business VALUES ('Djt Operations Ii LLC')
INSERT INTO Business VALUES ('Donald J Trump Enterprises LLC')
INSERT INTO Business VALUES ('Donald J Trump Enterprises Ii LLC')
INSERT INTO Business VALUES ('Donald J Trump Enterprises Iii LLC')
INSERT INTO Business VALUES ('The Donald J. Trump Company LLC')
INSERT INTO Business VALUES ('The Donald J. Trump Foundation, Inc.')
INSERT INTO Business VALUES ('The Donald J. Trump Grantor Trust')
INSERT INTO Business VALUES ('Trump, Donald J.')
INSERT INTO Business VALUES ('Dsn Licensing Member Corp. (F/K/A Trump Marks Network Member Inc.)')
INSERT INTO Business VALUES ('Dsn Licensing LLC')
INSERT INTO Business VALUES ('Dt App Warrant Holding Managing Member Corp.')
INSERT INTO Business VALUES ('Dttm Operations LLC')
INSERT INTO Business VALUES ('Dt App Warrant Holding LLC')
INSERT INTO Business VALUES ('Dt Bali Golf Manager Member Corp.')
INSERT INTO Business VALUES ('Dt Bali Golf Manager LLC')
INSERT INTO Business VALUES ('Dt Bali Hotel Manager Member Corp.')
INSERT INTO Business VALUES ('Dt Bali Hotel Manager LLC')
INSERT INTO Business VALUES ('Dt Bali Technical Services Manager Member Corp.')
INSERT INTO Business VALUES ('Dt Bali Technical Services Manager LLC')
INSERT INTO Business VALUES ('Dt Connect Managing Member Corp.')
INSERT INTO Business VALUES ('Dt Connect LLC')
INSERT INTO Business VALUES ('Golf Recreation Scotland Limited')
INSERT INTO Business VALUES ('Dt Connect Europe Limited')
INSERT INTO Business VALUES ('Dt Connect Ii Member Corp.')
INSERT INTO Business VALUES ('Dt Connect Ii LLC')
INSERT INTO Business VALUES ('Dt Dubai Golf Manager Member Corp.')
INSERT INTO Business VALUES ('Dt Dubai Golf Manager LLC')
INSERT INTO Business VALUES ('Dt Dubai Ii Golf Manager Member Corp.')
INSERT INTO Business VALUES ('Dt Dubai Ii Golf Manager LLC')
INSERT INTO Business VALUES ('Dt Home Marks International Member Corp.')
INSERT INTO Business VALUES ('Dt Home Marks International LLC')
INSERT INTO Business VALUES ('Dt India Venture Managing Member Corp.')
INSERT INTO Business VALUES ('Dt India Venture LLC')
INSERT INTO Business VALUES ('Dt Jeddah Technical Services Advisor Member Corp.')
INSERT INTO Business VALUES ('Dt Jeddah Technical Services Advisor LLC')
INSERT INTO Business VALUES ('Dt Jeddah Technical Services Manager Member Corp.')
INSERT INTO Business VALUES ('Dt Jeddah Technical Services Manager LLC')
INSERT INTO Business VALUES ('Dt Lido Golf Manager Member Corp')
INSERT INTO Business VALUES ('Dt Lido Golf Manager Member Corp/')
INSERT INTO Business VALUES ('Dt Lido Golf Manager LLC')
INSERT INTO Business VALUES ('Dt Lido Hotel Manager Member Corp.')
INSERT INTO Business VALUES ('Dt Lido Hotel Manager LLC')
INSERT INTO Business VALUES ('Dt Lido Technical Services Manager Member Corp.')
INSERT INTO Business VALUES ('Dt Lido Technical Services Manager LLC')
INSERT INTO Business VALUES ('Dt Marks Baku Managing Member Corp')
INSERT INTO Business VALUES ('Dt Marks Baku LLC')
INSERT INTO Business VALUES ('Dt Marks Bali Member Corp')
INSERT INTO Business VALUES ('Dt Marks Bali LLC')
INSERT INTO Business VALUES ('Dt Marks Dubai Member Corp.')
INSERT INTO Business VALUES ('Dt Marks Dubai LLC')
INSERT INTO Business VALUES ('Dt Marks Dubai Ii Member Corp.')
INSERT INTO Business VALUES ('Dt Marks Dubai Ii LLC')
INSERT INTO Business VALUES ('Dt Marks Gurgaon Managing Member Corp.')
INSERT INTO Business VALUES ('Dt Marks Gurgaon LLC')
INSERT INTO Business VALUES ('Dt Marks Jersey City LLC')
INSERT INTO Business VALUES ('Dt Marks Jupiter LLC')
INSERT INTO Business VALUES ('Dt Marks Lido Member Corp.')
INSERT INTO Business VALUES ('Dt Marks Lido LLC')
INSERT INTO Business VALUES ('Dt Marks Products International Member Corp.')
INSERT INTO Business VALUES ('Dt Marks Products International LLC')
INSERT INTO Business VALUES ('Dt Marks Pune Managing Member Corp')
INSERT INTO Business VALUES ('Dt Marks Pune LLC')
INSERT INTO Business VALUES ('Dt Marks Pune Ii Managing Member Corp')
INSERT INTO Business VALUES ('Dt Marks Pune Ii LLC')
INSERT INTO Business VALUES ('Dt Marks Qatar Member Corp.')
INSERT INTO Business VALUES ('Dt Marks Qatar LLC')
INSERT INTO Business VALUES ('Dt Marks Rio Member Corp.')
INSERT INTO Business VALUES ('Dt Marks Rio LLC')
INSERT INTO Business VALUES ('Dt Marks VAncouver Manager Corp.')
INSERT INTO Business VALUES ('Dt Marks VAncouver Lp')
INSERT INTO Business VALUES ('Dt Marks Worli Member Corp')
INSERT INTO Business VALUES ('Dt Marks Worli LLC')
INSERT INTO Business VALUES ('Dt Tower Gurgaon Managing Member Corp.')
INSERT INTO Business VALUES ('Dt Tower Gurgaon LLC')
INSERT INTO Business VALUES ('Dt Tower I Member Corp.')
INSERT INTO Business VALUES ('Dt Tower I LLC')
INSERT INTO Business VALUES ('Dt Tower Ii Member Corp.')
INSERT INTO Business VALUES ('Dt Tower Ii LLC')
INSERT INTO Business VALUES ('Dt Tower Kolkata Managing Member Corp.')
INSERT INTO Business VALUES ('Dt Tower Kolkata LLC')
INSERT INTO Business VALUES ('Dtw Venture Managing Member Corp.')
INSERT INTO Business VALUES ('Dtw Venture LLC')
INSERT INTO Business VALUES ('Plaza Consulting Corp.')
INSERT INTO Business VALUES ('The East 61 St. Company, Lp.')
INSERT INTO Business VALUES ('Eid Venture I LLC')
INSERT INTO Business VALUES ('Eid Venture I Corporation')
INSERT INTO Business VALUES ('Eid Venture Ii Member Corp.')
INSERT INTO Business VALUES ('Eid Venture Ii LLC')
INSERT INTO Business VALUES ('Excel Venture I Corp.')
INSERT INTO Business VALUES ('Excel Venture I LLC')
INSERT INTO Business VALUES ('Fifty Seven Management Corp')
INSERT INTO Business VALUES ('The Trump Equitable Fifth Avenue Company')
INSERT INTO Business VALUES ('Fifty Seventh Street Associates LLC')
INSERT INTO Business VALUES ('First Member, Inc.')
INSERT INTO Business VALUES ('Flights Inc. (F/K/A Trump Flights Inc.)')
INSERT INTO Business VALUES ('Florida Properties Management LLC')
INSERT INTO Business VALUES ('Fontainbleu Apartments LLC')
INSERT INTO Business VALUES ('Galbreath Columbus Circle Development Associates Lp')
INSERT INTO Business VALUES ('General Services Administration')
INSERT INTO Business VALUES ('Gept Delmonico LLC')
INSERT INTO Business VALUES ('Golf Productions Member Corp.')
INSERT INTO Business VALUES ('Golf Productions LLC')
INSERT INTO Business VALUES ('Tanoesoedibjo, Hary')
INSERT INTO Business VALUES ('Helicopter Air Services, Inc.')
INSERT INTO Business VALUES ('Highlander Hall, Inc.')
INSERT INTO Business VALUES ('Holds United Technologies Corp')
INSERT INTO Business VALUES ('How To Get Rich')
INSERT INTO Business VALUES ('Hudson Waterfront Associates, Lp.')
INSERT INTO Business VALUES ('Hudson Waterfront I Corporation')
INSERT INTO Business VALUES ('Hudson Westside Associates I, L.P.')
INSERT INTO Business VALUES ('Hudson Waterfront Associates I, Lp')
INSERT INTO Business VALUES ('Hudson Waterfront Ii Corporation')
INSERT INTO Business VALUES ('Hudson Westside Associates Ii, L.P.')
INSERT INTO Business VALUES ('Hudson Waterfront Associates Ii, Lp')
INSERT INTO Business VALUES ('Hudson Waterfront Iii Corporation')
INSERT INTO Business VALUES ('Hudson Westside Associates Iii, L.P.')
INSERT INTO Business VALUES ('Hudson Waterfront Associates Iii, Lp')
INSERT INTO Business VALUES ('Hudson Waterfront Iv Corporation')
INSERT INTO Business VALUES ('Hudson Westside Associates Iv, L.P.')
INSERT INTO Business VALUES ('Hudson Waterfront Associates Iv, Lp')
INSERT INTO Business VALUES ('Hudson Waterfront V Corporation')
INSERT INTO Business VALUES ('Hudson Westside Associates V, L.P.')
INSERT INTO Business VALUES ('Hudson Waterfront Associates V, Lp')
INSERT INTO Business VALUES ('Hwa 555 Owners, LLC')
INSERT INTO Business VALUES ('Hyde Park LLC')
INSERT INTO Business VALUES ('Indian Hills Holdings LLC (F/K/A Indian Hills Development LLC)')
INSERT INTO Business VALUES ('Internal Revenue Service')
INSERT INTO Business VALUES ('Jupiter Golf Club Managing Member Corp.')
INSERT INTO Business VALUES ('Jupiter Golf Club LLC (Trump National Golf Club - Jupiter)')
INSERT INTO Business VALUES ('Ladder Capital')
INSERT INTO Business VALUES ('Lamington Family Holdings LLC')
INSERT INTO Business VALUES ('Lfb Acquisition LLC')
INSERT INTO Business VALUES ('Lamington Farm Club, LLC (Trump National Golf Club - Bedminster)')
INSERT INTO Business VALUES ('Lawrence Towers Apartments LLC')
INSERT INTO Business VALUES ('Lfb Acquisition Member Corp.')
INSERT INTO Business VALUES ('Mar-A-Lago Club, Inc.')
INSERT INTO Business VALUES ('Mar-A-Lago Club, L.L.C.')
INSERT INTO Business VALUES ('Merrill Lynch Credit Corporation')
INSERT INTO Business VALUES ('Midland Associates')
INSERT INTO Business VALUES ('Trump Pageants, Inc.')
INSERT INTO Business VALUES ('Miss Universe L.P., Lllp (F/K/A Trump Pageants, Lp.)')
INSERT INTO Business VALUES ('Mobile Payroll Construction Manager Corp.')
INSERT INTO Business VALUES ('Mobile Payroll Construction LLC')
INSERT INTO Business VALUES ('National Labor Relations Board')
INSERT INTO Business VALUES ('Nbc')
INSERT INTO Business VALUES ('Never Give Up')
INSERT INTO Business VALUES ('New Sunshine LLC')
INSERT INTO Business VALUES ('Slc Turnberry Limited (Trump Turnberry)')
INSERT INTO Business VALUES ('Nitto World Co., Limited')
INSERT INTO Business VALUES ('Ocean Development Member Inc.')
INSERT INTO Business VALUES ('Trump Central Park West Corp.')
INSERT INTO Business VALUES ('One Central Park West Associates')
INSERT INTO Business VALUES ('One Central Park West Pt Associates')
INSERT INTO Business VALUES ('Opo Hotel Manager Member Corp')
INSERT INTO Business VALUES ('Opo Hotel Manager LLC')
INSERT INTO Business VALUES ('Owo Developer LLC')
INSERT INTO Business VALUES ('Panama Ocean Club Management Member Corp.')
INSERT INTO Business VALUES ('Panama Ocean Club Management LLC')
INSERT INTO Business VALUES ('Paramount Rpv Holdings Manager Corp.')
INSERT INTO Business VALUES ('Paramount Rpv Holdings LLC')
INSERT INTO Business VALUES ('Park Briar Associates')
INSERT INTO Business VALUES ('Pine Hill Development Managing Member Corp.')
INSERT INTO Business VALUES ('Pine Hill Development LLC')
INSERT INTO Business VALUES ('Plaza Consulting Corp')
INSERT INTO Business VALUES ('Poker Venture Managing Member Corp.')
INSERT INTO Business VALUES ('Poker Venture LLC')
INSERT INTO Business VALUES ('The Police Athletic League, Inc.')
INSERT INTO Business VALUES ('Qvc')
INSERT INTO Business VALUES ('Reg-Tru Equities, Ltd.')
INSERT INTO Business VALUES ('Restaurant 40 Member Corp.')
INSERT INTO Business VALUES ('Restaurant 40 LLC')
INSERT INTO Business VALUES ('Royal Bank America')
INSERT INTO Business VALUES ('Rpv Development LLC')
INSERT INTO Business VALUES ('Scotland Acquisitions LLC')
INSERT INTO Business VALUES ('Seven Springs LLC')
INSERT INTO Business VALUES ('Shore Haven Apt#1, Inc.')
INSERT INTO Business VALUES ('Shore Haven Management Corp.')
INSERT INTO Business VALUES ('Shore Haven Shopping Center LLC')
INSERT INTO Business VALUES ('Trump Village Construction Corp.')
INSERT INTO Business VALUES ('Beach Haven Apt#1. Inc.')
INSERT INTO Business VALUES ('Spring Creek Plaza')
INSERT INTO Business VALUES ('Starrett City Associates, L.P.')
INSERT INTO Business VALUES ('Stephanie Clifford (Aka Stormy Daniels)')
INSERT INTO Business VALUES ('Storage 106 LLC')
INSERT INTO Business VALUES ('Sussex Hall, Inc.')
INSERT INTO Business VALUES ('T Express Manager Member Corp.')
INSERT INTO Business VALUES ('T Express LLC')
INSERT INTO Business VALUES ('T International Realty LLC (Dba Trump International Realty)')
INSERT INTO Business VALUES ('Tag Air, Inc.')
INSERT INTO Business VALUES ('Tc Marks Buenos Aires LLC')
INSERT INTO Business VALUES ('Thc Baku Hotel Manager Services Member Corp.')
INSERT INTO Business VALUES ('Thc Baku Hotel Manager Services LLC')
INSERT INTO Business VALUES ('Thc Baku Services Member Corp.')
INSERT INTO Business VALUES ('Thc Baku Services LLC')
INSERT INTO Business VALUES ('Thc Development Brazil Managing Member Corp.')
INSERT INTO Business VALUES ('Thc Barra Hotelaria Ltda')
INSERT INTO Business VALUES ('Thc Central Reservations Member Corp.')
INSERT INTO Business VALUES ('Thc Central Reservations LLC')
INSERT INTO Business VALUES ('Trump International Hotels Management LLC (D/B/A Trump Hotel Collection [Hawaii], Trump Hotel Collection [New York])')
INSERT INTO Business VALUES ('Thc China Development LLC (F/K/A Trump China Development LLC)')
INSERT INTO Business VALUES ('Thc China Technical Services Manager Corp.')
INSERT INTO Business VALUES ('Thc China Technical Services LLC')
INSERT INTO Business VALUES ('Thc Dc Restaurant Hospitality LLC')
INSERT INTO Business VALUES ('Thc Development Brazil LLC')
INSERT INTO Business VALUES ('Thc Dubai Ii Hotel Manager Member Corp.')
INSERT INTO Business VALUES ('Thc Dubai Ii Hotel Manager LLC')
INSERT INTO Business VALUES ('Thc Hotel Development LLC')
INSERT INTO Business VALUES ('Thc Imea Development LLC')
INSERT INTO Business VALUES ('Thc Jeddah Hotel Advisor Member Corp.')
INSERT INTO Business VALUES ('Thc Jeddah Hotel Advisor LLC')
INSERT INTO Business VALUES ('Thc Jeddah Hotel Manager Member Corp.')
INSERT INTO Business VALUES ('Thc Jeddah Hotel Manager LLC')
INSERT INTO Business VALUES ('Thc Miami Restaurant Hospitality Member Corp.')
INSERT INTO Business VALUES ('Thc Miami Restaurant Hospitality LLC')
INSERT INTO Business VALUES ('Thc Qatar Hotel Manager Member Corp.')
INSERT INTO Business VALUES ('Thc Qatar Hotel Manager LLC')
INSERT INTO Business VALUES ('Thc Rio Managing Member Corp')
INSERT INTO Business VALUES ('Thc Rio Manager LLC')
INSERT INTO Business VALUES ('Thc Sales &Amp; Marketing Member Corp.')
INSERT INTO Business VALUES ('Thc Sales &Amp; Marketing LLC')
INSERT INTO Business VALUES ('Thc Services Shenzhen Member Corp.')
INSERT INTO Business VALUES ('Thc Services Shenzhen LLC')
INSERT INTO Business VALUES ('Thc Shenzhen Hotel Manager Member Corp.')
INSERT INTO Business VALUES ('Thc Shenzhen Hotel Manager LLC')
INSERT INTO Business VALUES ('Thc VAncouver Management Corp')
INSERT INTO Business VALUES ('Thc VAncouver Payroll Ulc')
INSERT INTO Business VALUES ('Thc Venture I Managing Member Corp.')
INSERT INTO Business VALUES ('Thc Venture I LLC')
INSERT INTO Business VALUES ('Thc Venture Ii Managing Member Corp.')
INSERT INTO Business VALUES ('Thc Venture Ii LLC')
INSERT INTO Business VALUES ('Thc Venture Iii Member Corp. - N/K/A Tttt Venture Member Corp.')
INSERT INTO Business VALUES ('Thc Venture Iii LLC (N/K/A Tttt Venture LLC)')
INSERT INTO Business VALUES ('The America We Deserve')
INSERT INTO Business VALUES ('The Art Of The Comeback')
INSERT INTO Business VALUES ('The Art Of The Deal')
INSERT INTO Business VALUES ('The Best Real Estate Advice I Ever Received')
INSERT INTO Business VALUES ('The Daily Mail')
INSERT INTO Business VALUES ('The Way To The Top')
INSERT INTO Business VALUES ('Think Big And Kick Ass')
INSERT INTO Business VALUES ('Think Like A Billionaire')
INSERT INTO Business VALUES ('Think Like A Champion')
INSERT INTO Business VALUES ('Tihc Reservations LLC')
INSERT INTO Business VALUES ('Tihm Member Corp')
INSERT INTO Business VALUES ('Tiht Chicago Member Acquisition LLC')
INSERT INTO Business VALUES ('Tiht Member LLC')
INSERT INTO Business VALUES ('Tiht Commercial LLC')
INSERT INTO Business VALUES ('Tiht Holding Company LLC')
INSERT INTO Business VALUES ('Time To Get Tough')
INSERT INTO Business VALUES ('Tipperary Realty Corp.')
INSERT INTO Business VALUES ('Tmg Member, LLC')
INSERT INTO Business VALUES ('Tngc Charlotte Manager Corp')
INSERT INTO Business VALUES ('Tngc Charlotte LLC')
INSERT INTO Business VALUES ('Tngc Dutchess County Member Corp. (F/K/A Trump Marks Classic Cars Member Corp.)')
INSERT INTO Business VALUES ('Tngc Dutchess Countv LLC')
INSERT INTO Business VALUES ('Tngc Jupiter Managing Member Corp.')
INSERT INTO Business VALUES ('Tngc Jupiter Management LLC')
INSERT INTO Business VALUES ('Tngc Pine Hill Member Corp. (F/K/A Crest Court Member Court)')
INSERT INTO Business VALUES ('Tngc Pine Hill LLC (F/K/A Crest Court LLC) (Trump National Golf Club - Philadelphia)')
INSERT INTO Business VALUES ('Toronto Development LLC')
INSERT INTO Business VALUES ('Tp Cfd Manager Corp.')
INSERT INTO Business VALUES ('Tp Cfd LLC')
INSERT INTO Business VALUES ('Travel Enterprises Management Inc. (F/K/A Toys At Trump, Inc.)')
INSERT INTO Business VALUES ('Trump 101: The Way To Success')
INSERT INTO Business VALUES ('Trump 106 Cps LLC')
INSERT INTO Business VALUES ('Trump 767 Management LLC')
INSERT INTO Business VALUES ('Trump 845 Un Mgr Corp.')
INSERT INTO Business VALUES ('Trump Ac Casino Marks Member Corp')
INSERT INTO Business VALUES ('Trump Ac Casino Marks LLC')
INSERT INTO Business VALUES ('Trump Acquisition Corp.')
INSERT INTO Business VALUES ('Trump Acquisition, LLC')
INSERT INTO Business VALUES ('Trump Books Manager Corp.')
INSERT INTO Business VALUES ('Trump Books LLC (The Midas Touch)')
INSERT INTO Business VALUES ('Trump Brazil LLC')
INSERT INTO Business VALUES ('Briarcliff Properties, Inc.')
INSERT INTO Business VALUES ('Trump Briarcliff Manor Development LLC (F/K/A Briar Hall Development LLC)')
INSERT INTO Business VALUES ('Trump Canadian Services Inc.')
INSERT INTO Business VALUES ('Trump Canouan Estate Member Corp')
INSERT INTO Business VALUES ('Trump Canouan Estate LLC')
INSERT INTO Business VALUES ('Trump Caribbean LLC')
INSERT INTO Business VALUES ('Trump Carousel Member Corp.')
INSERT INTO Business VALUES ('Trump Carousel LLC')
INSERT INTO Business VALUES ('Trump Chicago Commercial Member Corp.')
INSERT INTO Business VALUES ('Trump Chicago Commercial Manager LLC')
INSERT INTO Business VALUES ('Trump Chicago Development LLC')
INSERT INTO Business VALUES ('Trump Chicago Hotel Member Corp.')
INSERT INTO Business VALUES ('Trump Chicago Hotel Manager LLC')
INSERT INTO Business VALUES ('Trump Chicago Residential Member Corp')
INSERT INTO Business VALUES ('Trump Chicago Residential Manager LLC')
INSERT INTO Business VALUES ('Trump Chicago Retail Member Corp.')
INSERT INTO Business VALUES ('Trump Chicago Retail Manager LLC')
INSERT INTO Business VALUES ('Trump Classic Cars Member Corp.')
INSERT INTO Business VALUES ('Trump Classic Cars LLC')
INSERT INTO Business VALUES ('401 North Wabash Venture LLC')
INSERT INTO Business VALUES ('Trump Commercial Chicago LLC')
INSERT INTO Business VALUES ('The Trump Corporation')
INSERT INTO Business VALUES ('Trump Cps Corp.')
INSERT INTO Business VALUES ('Trump Cps LLC')
INSERT INTO Business VALUES ('Trump Development Services Member Corp.')
INSERT INTO Business VALUES ('Trump Development Services LLC')
INSERT INTO Business VALUES ('Trump Drinks Israel Member Corp.')
INSERT INTO Business VALUES ('Trump Drinks Israel LLC')
INSERT INTO Business VALUES ('Trump Drinks Israel Holdings Member Corp.')
INSERT INTO Business VALUES ('Trump Drinks Israel Holdings')
INSERT INTO Business VALUES ('The Trump Entrepreneur Initiative LLC (NY Domestic)')
INSERT INTO Business VALUES ('Trump Education Ulc')
INSERT INTO Business VALUES ('Trump Empire State, Inc.')
INSERT INTO Business VALUES ('Trump Endeavor 12 Manager Corp.')
INSERT INTO Business VALUES ('Trump Endeavor 12 LLC (Trump National Doral)')
INSERT INTO Business VALUES ('The Trump Entrepreneur Initiative LLC (F/K/A Trump University Ca LLC)')
INSERT INTO Business VALUES ('Djt Entrepreneur Managing Member LLC (F/K/A Djt University Managing Member LLC)')
INSERT INTO Business VALUES ('Spitalny, Jonathan')
INSERT INTO Business VALUES ('Sexton, Michael')
INSERT INTO Business VALUES ('Trump Eu Marks Member Corp')
INSERT INTO Business VALUES ('Trump Eu Marks LLC')
INSERT INTO Business VALUES ('Trump Ferry Point Member Corp.')
INSERT INTO Business VALUES ('Trump Ferry Point LLC (D/B/A Trump Golf Links Ferry Point [Delaware], Trump Golf Links Ferry Point [New York], Trump Golf Links [New York])')
INSERT INTO Business VALUES ('Trump Florida Manager Corp.')
INSERT INTO Business VALUES ('Trump Florida Management LLC')
INSERT INTO Business VALUES ('The Trump Follies Member Inc.')
INSERT INTO Business VALUES ('The Trump Follies LLC')
INSERT INTO Business VALUES ('Trump Golf Acquisitions LLC')
INSERT INTO Business VALUES ('Trump Golf Coco Beach Member Corp.')
INSERT INTO Business VALUES ('Trump Golf Coco Beach LLC')
INSERT INTO Business VALUES ('Trump Golf Management LLC')
INSERT INTO Business VALUES ('Trump Home Marks Member Corp.')
INSERT INTO Business VALUES ('Trump Home Marks LLC')
INSERT INTO Business VALUES ('The Trump Hotel Corp.')
INSERT INTO Business VALUES ('Trump Hotel Rio De Janeiro')
INSERT INTO Business VALUES ('Trump International Development Member Corp.')
INSERT INTO Business VALUES ('Trump International Development LLC')
INSERT INTO Business VALUES ('Trump International Golf Club, Inc.')
INSERT INTO Business VALUES ('Trump International Golf Club Lc (Trump International Golf Club - Florida)')
INSERT INTO Business VALUES ('Trump International Golf Club Scotland Limited')
INSERT INTO Business VALUES ('Tw Venture Ii LLC')
INSERT INTO Business VALUES ('Tigl Ireland Enterprises Limited (Trump International Golf Links - Doonbeg)')
INSERT INTO Business VALUES ('Tigl Ireland Management Limited')
INSERT INTO Business VALUES ('Trump Scotland Member Inc.')
INSERT INTO Business VALUES ('Trump International Golf Links - Scotland')
INSERT INTO Business VALUES ('Trump International Hotel And Tower (Panama)')
INSERT INTO Business VALUES ('Tihh Member Corp')
INSERT INTO Business VALUES ('Tihh Member LLC')
INSERT INTO Business VALUES ('Trump International Hotel Hawaii LLC')
INSERT INTO Business VALUES ('Trump International Management Corp')
INSERT INTO Business VALUES ('Sentient Jets Member Corp.')
INSERT INTO Business VALUES ('Sentient Jets LLC (N/K/A Trump Jets LLC)')
INSERT INTO Business VALUES ('Trump Jets LLC (F/K/A Sentient Jets LLC)')
INSERT INTO Business VALUES ('Trump Korean Projects LLC')
INSERT INTO Business VALUES ('Trump Korea LLC')
INSERT INTO Business VALUES ('Trump Las Vegas Corp.')
INSERT INTO Business VALUES ('Trump Las Vegas Managing Member LLC')
INSERT INTO Business VALUES ('Trump Las Vegas Member LLC')
INSERT INTO Business VALUES ('Trump Las Vegas Development LLC')
INSERT INTO Business VALUES ('Trump Las Vegas Sales &Amp; Marketing Inc.')
INSERT INTO Business VALUES ('Trump Lntematlonal Hotel And Tower Condominium')
INSERT INTO Business VALUES ('Trump Las Olas Member Corp.')
INSERT INTO Business VALUES ('Trump Las Olas LLC')
INSERT INTO Business VALUES ('Trump Management Inc.')
INSERT INTO Business VALUES ('Trump Marketing LLC')
INSERT INTO Business VALUES ('Trump Marks Gp Corp.')
INSERT INTO Business VALUES ('Trump Marks Holdings Lp (F/K/A Trump Marks Lp)')
INSERT INTO Business VALUES ('Trump Marks LLC')
INSERT INTO Business VALUES ('Trump Marks Asia Corp.')
INSERT INTO Business VALUES ('Trump Marks Asia LLC')
INSERT INTO Business VALUES ('Trump Marks Atlanta Member Corp')
INSERT INTO Business VALUES ('Trump Marks Atlanta LLC')
INSERT INTO Business VALUES ('Trump Marks Baja Corp.')
INSERT INTO Business VALUES ('Trump Marks Baja LLC')
INSERT INTO Business VALUES ('Trump Marks Batumi Managing Member Corp.')
INSERT INTO Business VALUES ('Trump Marks Batumi LLC')
INSERT INTO Business VALUES ('Trump Marks Beverages Corp.')
INSERT INTO Business VALUES ('Trump Marks Beverages LLC')
INSERT INTO Business VALUES ('Trump Marks Canouan Corp.')
INSERT INTO Business VALUES ('Trump Marks Canouan LLC')
INSERT INTO Business VALUES ('Trump Marks Chicago Member Corp.')
INSERT INTO Business VALUES ('Trump Marks Chicago LLC')
INSERT INTO Business VALUES ('Trump Marks Dubai Corp.')
INSERT INTO Business VALUES ('Trump Marks Dubai LLC')
INSERT INTO Business VALUES ('Trump Marks Egypt Corp.')
INSERT INTO Business VALUES ('Trump Marks Egypt LLC')
INSERT INTO Business VALUES ('Trump Marks Fine Foods Member Corp.')
INSERT INTO Business VALUES ('Trump Marks Fine Foods LLC')
INSERT INTO Business VALUES ('Trump Marks Ft. Lauderdale Member Corp.')
INSERT INTO Business VALUES ('Trump Marks Ft. Lauderdale LLC')
INSERT INTO Business VALUES ('Trump Marks Hollywood Corp.')
INSERT INTO Business VALUES ('Trump Marks Hollywood LLC')
INSERT INTO Business VALUES ('Trump Marks Istanbul Ii Corp.')
INSERT INTO Business VALUES ('Trump Marks Istanbul Ll LLC')
INSERT INTO Business VALUES ('Trump Marks Jersey City Corp.')
INSERT INTO Business VALUES ('Trump Marks Jersey City LLC')
INSERT INTO Business VALUES ('Trump Marks Las Vegas Corp')
INSERT INTO Business VALUES ('Trump Marks Las Vegas LLC')
INSERT INTO Business VALUES ('Trump Marks Magazine Corp.')
INSERT INTO Business VALUES ('Trump Marks Magazine LLC')
INSERT INTO Business VALUES ('Trump Marks Mattress Member Corp.')
INSERT INTO Business VALUES ('Trump Marks Mattress LLC')
INSERT INTO Business VALUES ('Trump Marks Menswear Member Corp.')
INSERT INTO Business VALUES ('Trump Marks Menswear LLC')
INSERT INTO Business VALUES ('Trump Marks Mortgage Corp.')
INSERT INTO Business VALUES ('Trump Marks Mtg LLC')
INSERT INTO Business VALUES ('Trump Marks Mumbai Member Corp.')
INSERT INTO Business VALUES ('Trump Marks Mumbai LLC')
INSERT INTO Business VALUES ('Trump Marks New Rochelle Corp.')
INSERT INTO Business VALUES ('Trump Marks New Rochelle LLC')
INSERT INTO Business VALUES ('Trump Marks Palm Beach Corp.')
INSERT INTO Business VALUES ('Trump Marks Palm Beach LLC')
INSERT INTO Business VALUES ('Trump Marks Panama Corp.')
INSERT INTO Business VALUES ('Trump Marks Panama LLC')
INSERT INTO Business VALUES ('Trump Marks Philadelphia Corp.')
INSERT INTO Business VALUES ('Trump Marks Philadelphia LLC')
INSERT INTO Business VALUES ('Trump Marks Philippines Corp.')
INSERT INTO Business VALUES ('Trump Marks Philippines LLC')
INSERT INTO Business VALUES ('Trump Marks Products Member Corp.')
INSERT INTO Business VALUES ('Trump Marks Products LLC')
INSERT INTO Business VALUES ('Trump Marks Puerto Rico I Member Corp.')
INSERT INTO Business VALUES ('Trump Marks Puerto Rico I LLC')
INSERT INTO Business VALUES ('Trump Marks Puerto Rico Ii Member Corp.')
INSERT INTO Business VALUES ('Trump Marks Puerto Rico Ii LLC')
INSERT INTO Business VALUES ('Trump Marks Punta Del Este Manager Corp.')
INSERT INTO Business VALUES ('Trump Marks Punta Del Este LLC')
INSERT INTO Business VALUES ('The Trump Marks Real Estate Corp.')
INSERT INTO Business VALUES ('Trump Marks Real Estate LLC')
INSERT INTO Business VALUES ('Trump Marks Soho License Corp.')
INSERT INTO Business VALUES ('Trump Marks Soho LLC')
INSERT INTO Business VALUES ('Trump Marks Stamford Corp.')
INSERT INTO Business VALUES ('Trump Marks Stamford LLC')
INSERT INTO Business VALUES ('Trump Marks Sunny Isles I Member Corp.')
INSERT INTO Business VALUES ('Trump Marks Sunny Isles I LLC')
INSERT INTO Business VALUES ('Trump Marks Sunny Isles Ii Member Corp.')
INSERT INTO Business VALUES ('Trump Marks Sunny Isles Ii LLC')
INSERT INTO Business VALUES ('Trump Marks Tampa Corp.')
INSERT INTO Business VALUES ('Trump Marks Tampa LLC')
INSERT INTO Business VALUES ('Trump Marks Toronto Corp.')
INSERT INTO Business VALUES ('Trump Marks Toronto LLC')
INSERT INTO Business VALUES ('Trump Marks Waikiki Corp.')
INSERT INTO Business VALUES ('Trump Marks Waikiki LLC')
INSERT INTO Business VALUES ('Trump Marks Westchester Corp.')
INSERT INTO Business VALUES ('Trump Marks Westchester LLC')
INSERT INTO Business VALUES ('Trump Marks White Plains Corp.')
INSERT INTO Business VALUES ('Trump Marks White Plains LLC')
INSERT INTO Business VALUES ('Trump Miami Resort Management Member Corp')
INSERT INTO Business VALUES ('Trump Miami Resort Management LLC')
INSERT INTO Business VALUES ('Trump Model Management LLC')
INSERT INTO Business VALUES ('Trump Mortgage LLC')
INSERT INTO Business VALUES ('Trump National Golf Club - Charlotte')
INSERT INTO Business VALUES ('Trump National Golf Club Colts Neck Member Corp.')
INSERT INTO Business VALUES ('Trump National Golf Club Colts Neck LLC')
INSERT INTO Business VALUES ('Trump National Golf Club - Hudson VAlley')
INSERT INTO Business VALUES ('Vh Property Corp. (Trump National Golf Club - Los Angeles)')
INSERT INTO Business VALUES ('Vhps LLC')
INSERT INTO Business VALUES ('Trump National Golf Club Washington Dc Member Corp.')
INSERT INTO Business VALUES ('Trump National Golf Club Washington Dc LLC')
INSERT INTO Business VALUES ('Trump National Golf Club Member Corp.')
INSERT INTO Business VALUES ('Trump National Golf Club LLC (Trump National Golf Club - Westchester)')
INSERT INTO Business VALUES ('Trump Ocean Manager Inc.')
INSERT INTO Business VALUES ('Trump Ocean Managing Member LLC')
INSERT INTO Business VALUES ('Trump Old Post Office Member Corp.')
INSERT INTO Business VALUES ('Trump Old Post Office LLC')
INSERT INTO Business VALUES ('Trump On The Ocean LLC')
INSERT INTO Business VALUES ('The Trump Organization, Inc.')
INSERT INTO Business VALUES ('Trump Organization LLC (D/B/A The Trump Organization)')
INSERT INTO Business VALUES ('Trump Palace/Parc LLC')
INSERT INTO Business VALUES ('Trump Panama Condominium Member Corp.')
INSERT INTO Business VALUES ('Trump Panama Condominium Management LLC')
INSERT INTO Business VALUES ('Trump Panama Hotel Management Member Corp.')
INSERT INTO Business VALUES ('Trump Panama Hotel Management LLC')
INSERT INTO Business VALUES ('Trump Parc East Condominium')
INSERT INTO Business VALUES ('Trump Park Avenue Acquisition LLC')
INSERT INTO Business VALUES ('Trump Delmonico LLC')
INSERT INTO Business VALUES ('Trump Park Avenue LLC')
INSERT INTO Business VALUES ('Trump Payroll Corp.')
INSERT INTO Business VALUES ('Trump Payroll Chicago LLC')
INSERT INTO Business VALUES ('Trump Phoenix Development LLC')
INSERT INTO Business VALUES ('Trump Plaza Member Inc. (F/K/A Trump Plaza Corp.)')
INSERT INTO Business VALUES ('Trump Plaza LLC')
INSERT INTO Business VALUES ('Trump Productions Managing Member Inc.')
INSERT INTO Business VALUES ('Trump Productions LLC (F/K/A Rancho Lien LLC)')
INSERT INTO Business VALUES ('Trump Project Management Corp.')
INSERT INTO Business VALUES ('Trump Properties LLC')
INSERT INTO Business VALUES ('Trump Realty Services, LLC (F/K/A Trump Mortgage Services LLC (03) &Amp; Tower Mortgage Services LLC)')
INSERT INTO Business VALUES ('Trump Restaurants LLC')
INSERT INTO Business VALUES ('Trump Riverside Management LLC')
INSERT INTO Business VALUES ('Trump Ruffin LLC')
INSERT INTO Business VALUES ('Trump Ruffin Tower I LLC')
INSERT INTO Business VALUES ('Trump Ruffin Commercial LLC')
INSERT INTO Business VALUES ('Trump Sales &Amp; Leasing Chicago Member Corp.')
INSERT INTO Business VALUES ('Trump Sales &Amp; Leasing Chicago LLC')
INSERT INTO Business VALUES ('Trump Scotsborough Square Member Corp.')
INSERT INTO Business VALUES ('Trump Scotsborough Square LLC')
INSERT INTO Business VALUES ('Trump Soho Member LLC')
INSERT INTO Business VALUES ('Trump Toronto Development Inc.')
INSERT INTO Business VALUES ('Trump Toronto Hotel Management Corp.')
INSERT INTO Business VALUES ('Trump Toronto Member Corp. (F/K/A Trump Toronto Management Member Corp.)')
INSERT INTO Business VALUES ('Trump Tower Managing Member Inc.')
INSERT INTO Business VALUES ('Trump Tower Commercial LLC')
INSERT INTO Business VALUES ('Trump Tower Condominium Residential Section')
INSERT INTO Business VALUES ('Trump Tower Triplex')
INSERT INTO Business VALUES ('Trump Towers Istanbul')
INSERT INTO Business VALUES ('Turnberry Scotland LLC')
INSERT INTO Business VALUES ('Turnberry Scotland Managing Member Corp')
INSERT INTO Business VALUES ('Trump Vineyard Estates Manager Corp.')
INSERT INTO Business VALUES ('Trump Vineyard Estates LLC')
INSERT INTO Business VALUES ('Trump Vineyard Estates Lot 3 Owner LLC (F/K/A Eric Trump Land Holdings LLC)')
INSERT INTO Business VALUES ('Trump Virginia Acquisitions Manager Corp.')
INSERT INTO Business VALUES ('Trump Virginia Acquisitions LLC (F/K/A Virginia Acquisitions LLC)')
INSERT INTO Business VALUES ('Trump Virginia Lot 5 Manager Corp.')
INSERT INTO Business VALUES ('Trump Virginia Lot 5 LLC')
INSERT INTO Business VALUES ('Trump Wine Marks Member Corp.')
INSERT INTO Business VALUES ('Trump Wine Marks LLC')
INSERT INTO Business VALUES ('Trump World Productions Manager Corp.')
INSERT INTO Business VALUES ('Trump World Productions LLC')
INSERT INTO Business VALUES ('Trump World Publications')
INSERT INTO Business VALUES ('Trump: Surviving At The Top')
INSERT INTO Business VALUES ('Trump&#39;S Castle Management Corp.')
INSERT INTO Business VALUES ('Tw Venture I Managing Member Corp')
INSERT INTO Business VALUES ('Tw Venture I LLC')
INSERT INTO Business VALUES ('Tw Venture Ii Managing Member Corp')
INSERT INTO Business VALUES ('Ultimate Air Corp.')
INSERT INTO Business VALUES ('Unit 2502 Enterprises Corp.')
INSERT INTO Business VALUES ('Unit 2502 Enterprises LLC')
INSERT INTO Business VALUES ('West Palm Operations LLC')
INSERT INTO Business VALUES ('Wexford Hall Inc.')
INSERT INTO Business VALUES ('White Course Managing Member Corp.')
INSERT INTO Business VALUES ('White Course LLC')
INSERT INTO Business VALUES ('Why We Want You To Be Rich')
INSERT INTO Business VALUES ('William Trump Medical Fund LLC')
INSERT INTO Business VALUES ('Wilshire Hall LLC')
INSERT INTO Business VALUES ('Wmtmf LLC')
INSERT INTO Business VALUES ('Wollman Rink Operations LLC')
INSERT INTO Business VALUES ('Yorktown Real Estate LLC (F/K/A Yorktown Development Associates LLC)')
INSERT INTO Business VALUES ('Tba')
INSERT INTO Business VALUES ('(Various)')
INSERT INTO Business VALUES ('Trust U/W/O Fred C. Trump- Tiffany Ariana Trump')
INSERT INTO Business VALUES ('Bahrain')
INSERT INTO Business VALUES ('Melania Marks Skincare LLC')
INSERT INTO Business VALUES ('Melania Marks Skincare Managing Member Corp.')
INSERT INTO Business VALUES ('721 33H Holdings LLC')
INSERT INTO Business VALUES ('721 33H LLC')
INSERT INTO Business VALUES ('Dt Endeavor I Member Corp.')
INSERT INTO Business VALUES ('Dt Venture I Member Corp.')
INSERT INTO Business VALUES ('Dt Venture Ii Member Corp.')
INSERT INTO Business VALUES ('Trump Ice, Inc.')
INSERT INTO Business VALUES ('Trump Marks Golf Swing Member Corp.')
INSERT INTO Business VALUES ('Trump Marks New Orleans Corp.')
INSERT INTO Business VALUES ('Djt Entrepreneur Member LLC (F/K/A Djt University Member LLC)')
INSERT INTO Business VALUES ('Trump Soho Hotel Condominium New York')
INSERT INTO Business VALUES ('Trump Identity')
INSERT INTO Business VALUES ('Trump Lauderdale Development 2 LLC')
INSERT INTO Business VALUES ('Trump Marks South Africa Member Corp.')
INSERT INTO Business VALUES ('Identity Theft Productions LLC')
INSERT INTO Business VALUES ('Tigl Common Area Management Holdings LLC')
INSERT INTO Business VALUES ('Trump Ice LLC')
INSERT INTO Business VALUES ('Trump 845 Un Mgr LLC (F/K/A 845 Un LLC)')
INSERT INTO Business VALUES ('Trump Marks Toronto Lp (F/K/A Trump Toronto Management Lp)')
INSERT INTO Business VALUES ('Trump Lauderdale Development LLC')
INSERT INTO Business VALUES ('Dt Endeavor I LLC')
INSERT INTO Business VALUES ('Dt Venture I LLC')
INSERT INTO Business VALUES ('Dt Venture Ii LLC (F/K/A Ritz Carlton Hotel At 112 Central Park South)')
INSERT INTO Business VALUES ('New World Property Management Limited')
INSERT INTO Business VALUES ('Trump New World Property Management LLC')
INSERT INTO Business VALUES ('Trump Chicago Managing Member LLC')
INSERT INTO Business VALUES ('Trump Chicago Member LLC')
INSERT INTO Business VALUES ('401 Mezz Venture LLC')
INSERT INTO Business VALUES ('Trump Chicago Retail LLC')
INSERT INTO Business VALUES ('Trump Palace Condominium')
INSERT INTO Business VALUES ('Trump Marks Batumi Member Corp.')
INSERT INTO Business VALUES ('55 Wall Development Corp')
INSERT INTO Business VALUES ('Identity Theft Productions Member Corp.')
INSERT INTO Business VALUES ('Tigl Common Area Management Corp.')
INSERT INTO Business VALUES ('Trump Identity Member Corp.')
INSERT INTO Business VALUES ('Trump Kelowna Member Corp.')
INSERT INTO Business VALUES ('Trump Kelowna LLC')
INSERT INTO Business VALUES ('Trump Marks Golf Swing LLC')
INSERT INTO Business VALUES ('Trump Marks New Orleans LLC')
INSERT INTO Business VALUES ('Trump Marks South Africa LLC')
INSERT INTO Business VALUES ('Fred C. Trump, Grat Trust- F/B/O Elizabeth Trump Grau')
INSERT INTO Business VALUES ('Maryanne Trump Grat Trust- F/B/O Elizabeth Trump Grau')
INSERT INTO Business VALUES ('The Fred C. Trump December 16, 1976 Trust- F/B/O Donald J. Trump.')
INSERT INTO Business VALUES ('The Fred C. Trump December 16, 1976 Trust- F/B/O Elizabeth J. Trump')
INSERT INTO Business VALUES ('The Fred C. Trump December 16, 1976 Trust- F/B/O Robert S. Trump')
INSERT INTO Business VALUES ('Trust U/W/O Fred C. Trump - Elizabeth Trump Grau')
INSERT INTO Business VALUES ('Trust U/W/O Fred C. Trump - F/B/O The Grandchildren Of Fred C. Trump')
INSERT INTO Business VALUES ('Melania LLC')
INSERT INTO Business VALUES ('Melania Marks Accessories LLC')
INSERT INTO Business VALUES ('Melania Marks Accessories Member Corp.')
INSERT INTO Business VALUES ('Beach Haven Apartments #3 LLC')
INSERT INTO Business VALUES ('Beach Haven Shopping Center LLC')
INSERT INTO Business VALUES ('Screen Actors Guild')
INSERT INTO Business VALUES ('Class="S35">')
INSERT INTO Business VALUES ('Thc China Development Management Corp (F/K/A Trump China Development Management Corp)')
INSERT INTO Business VALUES ('Mz Berger &Amp; Company LLC')
INSERT INTO Business VALUES ('Russian Real Estate Investors')
