USE Trump
GO

INSERT INTO Conflict VALUES ('4 Shadow Tree Lane', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('40 Wall Street', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('809 North Canon', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('81 Pine Note Holder', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('845 Un', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('Ace Entertainment (Formerly Trump Casinos Or Trump Taj Mahal)', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('All County Building Supply &Amp; Maintenance', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('Aviation Payroll Company', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('B Plaza Realty', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('Bedford Hills', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('Mar-A-Lago', 'An Israel-focused charity, The Truth About Israel, moved its recent gala event to Pres. Trump&#39;s Mar-a-Lago resort in appreciation of the president&#39;s support for Israel.', '', '3/9/2018 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('Stephanie Clifford (Aka Stormy Daniels)', 'Pres. Trump allegedly paid a former porn star to keep quiet about their affair in 2006. She is now suing Trump, claiming the non-disclosure agreement is invalid.', '', '3/9/2018 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('Trump Briarcliff Manor Development (F/K/A Briar Hall Development)', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('Trump International Hotel And Tower (Panama)', 'Ethics experts say their &#39;fear has been realized&#39; as Trump faces one of his most consequential conflicts of interest yet: The Panamanian government has pledged to investigate the Trump Organization for resisting eviction from the Trump International Hotel and Tower. That dispute arose after the hotel&#39;s majority owner cancelled the Trump Organization&#39;s management contract for the hotel.', '', '3/9/2018 12:00:00 AM', GetDate(), 1)
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = '4 Shadow Tree Lane'), (SELECT ID FROM Business WHERE Name = '4 Shadow Tree Lane LLC'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = '40 Wall Street'), (SELECT ID FROM Business WHERE Name = '40 Wall Development Associates LLC'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = '809 North Canon'), (SELECT ID FROM Business WHERE Name = '809 North Canon LLC'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = '81 Pine Note Holder'), (SELECT ID FROM Business WHERE Name = '81 Pine Note Holder Inc'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = '845 Un'), (SELECT ID FROM Business WHERE Name = '845 UN Limited Partnership'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'Ace Entertainment (Formerly Trump Casinos Or Trump Taj Mahal)'), (SELECT ID FROM Business WHERE Name = 'Ace Entertainment Holdings Inc. (F/K/A Trump Casinos, Inc., F/K/A Trump Taj Mahal, Inc.)'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'All County Building Supply &Amp; Maintenance'), (SELECT ID FROM Business WHERE Name = 'All County Building Supply &amp; Maintenance Corp.'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'Aviation Payroll Company'), (SELECT ID FROM Business WHERE Name = 'Aviation Payroll Company'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'B Plaza Realty'), (SELECT ID FROM Business WHERE Name = 'B Plaza Realty Corp.'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'Bedford Hills'), (SELECT ID FROM Business WHERE Name = 'Bedford Hills Corp'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'Mar-A-Lago'), (SELECT ID FROM Business WHERE Name = 'Mar-a-Lago'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'Stephanie Clifford (Aka Stormy Daniels)'), (SELECT ID FROM Business WHERE Name = 'Stephanie Clifford (aka Stormy Daniels)'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'Trump Briarcliff Manor Development (F/K/A Briar Hall Development)'), (SELECT ID FROM Business WHERE Name = 'Trump Briarcliff Manor Development LLC (F/K/A Briar Hall Development LLC)'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'Trump International Hotel And Tower (Panama)'), (SELECT ID FROM Business WHERE Name = 'Trump International Hotel and Tower (Panama)'))
