USE Trump
GO

INSERT INTO Conflict VALUES ('4 Shadow Tree Lane', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('40 Wall Street', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('809 North Canon', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('81 Pine Note Holder', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('845 Un', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('Ace Entertainment (Formerly Trump Casinos Or Trump Taj Mahal)', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('All County Building Supply &Amp; Maintenance', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('Aviation Payroll Company', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('B Plaza Realty', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('Bedford Hills', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO Conflict VALUES ('Trump Briarcliff Manor Development (F/K/A Briar Hall Development)', '', '', '7/5/2017 12:00:00 AM', GetDate(), 1)
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = '4 Shadow Tree Lane'), (SELECT ID FROM Business WHERE Name = '4 Shadow Tree Lane LLC'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = '40 Wall Street'), (SELECT ID FROM Business WHERE Name = '40 Wall Development Associates LLC'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = '809 North Canon'), (SELECT ID FROM Business WHERE Name = '809 North Canon LLC'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = '81 Pine Note Holder'), (SELECT ID FROM Business WHERE Name = '81 Pine Note Holder Inc'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = '845 Un'), (SELECT ID FROM Business WHERE Name = '845 UN Limited Partnership'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'Ace Entertainment (Formerly Trump Casinos Or Trump Taj Mahal)'), (SELECT ID FROM Business WHERE Name = 'Ace Entertainment Holdings Inc. (F/K/A Trump Casinos, Inc., F/K/A Trump Taj Mahal, Inc.)'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'All County Building Supply &Amp; Maintenance'), (SELECT ID FROM Business WHERE Name = 'All County Building Supply &amp; Maintenance Corp.'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'Aviation Payroll Company'), (SELECT ID FROM Business WHERE Name = 'Aviation Payroll Company'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'B Plaza Realty'), (SELECT ID FROM Business WHERE Name = 'B Plaza Realty Corp.'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'Bedford Hills'), (SELECT ID FROM Business WHERE Name = 'Bedford Hills Corp'))
INSERT INTO BusinessConflict VALUES ((SELECT ID FROM Conflict WHERE Name = 'Trump Briarcliff Manor Development (F/K/A Briar Hall Development)'), (SELECT ID FROM Business WHERE Name = 'Trump Briarcliff Manor Development LLC (F/K/A Briar Hall Development LLC)'))
