USE Trump
GO

INSERT INTO MediaOutlet VALUES ('Wall Street Journal')
INSERT INTO MediaOutlet VALUES ('New York Times')
INSERT INTO MediaOutlet VALUES ('Center for Public Integrity')
INSERT INTO MediaOutlet VALUES ('Office of Government Ethics')
INSERT INTO MediaOutlet VALUES ('CNN')
INSERT INTO MediaOutlet VALUES ('Huffington Post')
INSERT INTO MediaOutlet VALUES ('General Services Administration')
INSERT INTO MediaOutlet VALUES ('Government Executive')
INSERT INTO MediaOutlet VALUES ('Indy Star')
INSERT INTO MediaOutlet VALUES ('Newsweek')
INSERT INTO MediaOutlet VALUES ('Mother Jones')
INSERT INTO MediaOutlet VALUES ('The Real Deal')
INSERT INTO MediaOutlet VALUES ('Washington Post')
INSERT INTO MediaOutlet VALUES ('NYS Department of State')
INSERT INTO MediaOutlet VALUES ('McClatchy')
INSERT INTO MediaOutlet VALUES ('National Labor Relations Board')
INSERT INTO MediaOutlet VALUES ('Variety')
INSERT INTO MediaOutlet VALUES ('New York Post')
INSERT INTO MediaOutlet VALUES ('Vanity Fair')
INSERT INTO MediaOutlet VALUES ('MNC Newsroom')
INSERT INTO MediaOutlet VALUES ('BuzzFeed')
INSERT INTO MediaOutlet VALUES ('ProPublica')
INSERT INTO MediaOutlet VALUES ('Forbes')
INSERT INTO MediaOutlet VALUES ('Associated Press')
INSERT INTO MediaOutlet VALUES ('Business Insider')
INSERT INTO MediaOutlet VALUES ('Bloomberg Politics')
INSERT INTO MediaOutlet VALUES ('Economic Times')
INSERT INTO MediaOutlet VALUES ('Shanghaiist')
INSERT INTO MediaOutlet VALUES ('Politico')
INSERT INTO MediaOutlet VALUES ('@realDonaldTrump')
INSERT INTO MediaOutlet VALUES ('NPR')
INSERT INTO MediaOutlet VALUES ('La Nacion')
INSERT INTO MediaOutlet VALUES ('Fox News')
