USE Trump
GO

INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = '4 Shadow Tree Lane Member Corp'), (SELECT ID FROM Business WHERE Name = '4 Shadow Tree Lane LLC'), '1')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Djt Holdings LLC'), (SELECT ID FROM Business WHERE Name = '4 Shadow Tree Lane LLC'), '99')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Djt Holdings Managing Member LLC'), (SELECT ID FROM Business WHERE Name = '4 Shadow Tree Lane Member Corp'), '100')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Parc Consulting, Inc.'), (SELECT ID FROM Business WHERE Name = '40 Wall Development Associates LLC'), '0.1')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'The Donald J. Trump Revocable Trust'), (SELECT ID FROM Business WHERE Name = '40 Wall Development Associates LLC'), '99.9')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = '40 Wall Development Associates LLC'), (SELECT ID FROM Business WHERE Name = '40 Wall Street Commercial LLC'), '100')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = '40 Wall Street Member Corp'), (SELECT ID FROM Business WHERE Name = '40 Wall Street LLC'), '0.1')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = '40 Wall Development Associates LLC'), (SELECT ID FROM Business WHERE Name = '40 Wall Street LLC'), '99.9')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = '40 Wall Development Associates LLC'), (SELECT ID FROM Business WHERE Name = '40 Wall Street Member Corp'), '100')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Trump Chicago Managing Member LLC'), (SELECT ID FROM Business WHERE Name = '401 Mezz Venture LLC'), '1')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Trump Chicago Member LLC'), (SELECT ID FROM Business WHERE Name = '401 Mezz Venture LLC'), '49')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Tiht Chicago Member Acquisition LLC'), (SELECT ID FROM Business WHERE Name = '401 Mezz Venture LLC'), '50')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = '401 Mezz Venture LLC'), (SELECT ID FROM Business WHERE Name = '401 North Wabash Venture LLC'), '100')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = '809 North Canon Member Corporation'), (SELECT ID FROM Business WHERE Name = '809 North Canon LLC'), '1')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Djt Holdings LLC'), (SELECT ID FROM Business WHERE Name = '809 North Canon LLC'), '99')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Djt Holdings Managing Member LLC'), (SELECT ID FROM Business WHERE Name = '809 North Canon Member Corporation'), '100')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Djt Holdings LLC'), (SELECT ID FROM Business WHERE Name = '81 Pine Note Holder Inc'), '100')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Trump 845 Lp LLC'), (SELECT ID FROM Business WHERE Name = '845 Un Limited Partnership'), '60')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Trump 845 Un Gp LLC'), (SELECT ID FROM Business WHERE Name = '845 Un Limited Partnership'), '40')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Djt Holdings LLC'), (SELECT ID FROM Business WHERE Name = 'Ace Entertainment Holdings Inc. (F/K/A Trump Casinos, Inc., F/K/A Trump Taj Mahal, Inc.)'), '100')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Djt Holdings LLC'), (SELECT ID FROM Business WHERE Name = 'All County Building Supply &Amp; Maintenance Corp.'), '25')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Trump Family Members'), (SELECT ID FROM Business WHERE Name = 'All County Building Supply &Amp; Maintenance Corp.'), '75')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Djt Holdings Managing Member LLC'), (SELECT ID FROM Business WHERE Name = 'Aviation Payroll Company'), '100')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Donald J. Trump'), (SELECT ID FROM Business WHERE Name = 'B Plaza Realty Corp.'), '100')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'The Donald J. Trump Revocable Trust'), (SELECT ID FROM Business WHERE Name = 'Beach Haven Apartments #3 LLC'), '25')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Trump Family Members'), (SELECT ID FROM Business WHERE Name = 'Beach Haven Apartments #3 LLC'), '75')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'The Donald J. Trump Revocable Trust'), (SELECT ID FROM Business WHERE Name = 'Beach Haven Apt#1. Inc.'), '25')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Trump Family Members'), (SELECT ID FROM Business WHERE Name = 'Beach Haven Apt#1. Inc.'), '75')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Djt Holdings LLC'), (SELECT ID FROM Business WHERE Name = 'Beach Haven Shopping Center LLC'), '25')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Trump Family Members'), (SELECT ID FROM Business WHERE Name = 'Beach Haven Shopping Center LLC'), '75')
INSERT INTO BusinessOwnership VALUES ((SELECT ID FROM Business WHERE Name = 'Djt Holdings LLC'), (SELECT ID FROM Business WHERE Name = 'Bedford Hills Corp'), '100')
